### ISSUE TITLE
🐛TokenViewer shows no information

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1002]
#### Describe your issue

![tokenviewer_bug](https://user-images.githubusercontent.com/17065920/46596916-4c82ef80-cade-11e8-98e4-7575ea32d0f6.gif)

If you first select an element which has an token and then one without, the token viewer shows no information. 
Thats a bug because the token viewer should display `There is no token for this element.`

#### How can others reproduce the issue?

- follow the steps from the gif above

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
There is no token for "flows". But there is no text that gets displayed in the case that it get selected.
Add the appropriate if-clause to the text and this should be fine.

**Comment by SteffenKn** [comment]
The problem is not about flows. This also exists when you click on tasks that were not executed yet.
This is because in this cases the backend returns an error that does not seem to be handled.
