### ISSUE TITLE
🐛 Multiple BPMNJS Viewer Get Created When Changing Between the Heatmap And The Inspect Correlation

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1004]
#### Describe your issue

Every time when changing between e.g. the heatmap and the inspect correlation, a new viewer will be created by the diagram viewer of the inspect correlation.

This is because in the inspect.html a show bind was changed to an if bind.

#### Possible solution

- Change the if-bind back to a show-bind
- Or add an early exit in the attached function when the diagram viewer is already set.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
You could try to destroy the viewer in the detached function then, that would be the expected behaviour anyway.

**Comment by SteffenKn** [comment]
But then you would always create a new viewer when changing between the heatmap and the inspect correlation.
I would more expect that only when leaving the inspect the viewer gets destroyed, since this seems more efficient.

**Comment by Vyperus** [comment]
This ties to the show.bind/if.bind bug you two found.

The view "heatmap" or "inspect correlation" shouldn't be attached or loaded when they are not displayed. The efficiency was never a problem and i wouldn't take it as an argument if you are creating side effects with it, which this is probably doing.

If you can get it running nice and save with show.bind I am fine with it for now but this is subject to be refactored in the future.
