### ISSUE TITLE
🐛After Logging in the SolutionExplorer gets cleared

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1006]
#### Describe your issue

After you have been logged in, the previous opened solutions from the filesystem disappear.

#### How can others reproduce the issue?

- open one ore more solutions from the filesystem
- login with identity server
- see that the solutions are disappeared

#### Possible solution

- save opened solutions in the localstorage

quick fix: Display a notification before logging in which links to this issue. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Quickfix will be released in v4.6.0
