### ISSUE TITLE
🐛Only one opened single diagram after reload

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1016]
#### Describe your issue

If you had opened several single diagrams and reload your bpmn-studio (CTRL/CMD+R) only one random diagram stays opened

#### How can others reproduce the issue?

- open some diagrams
- reload bpmn-studio
- look at the solution explorer

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I cannot reproduce this issue.

**Comment by robpal94** [comment]
This only happens when you open a diagram via the file association.
