### ISSUE TITLE
🐛 Error When Closing the Solution While Creating a Diagram

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1023]
#### Describe your issue

When closing the solution while creating a diagram I get the following error message on every click:

<img width="197" src="https://user-images.githubusercontent.com/20394992/46807783-19a15b80-cd6b-11e8-83e7-116b4821ddd1.png">

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Open a solution
- Click on the add diagram button
- Close the solution
- **Notice that when clicking anywhere an error will be thrown**

#### Possible solution

- Cancel the creation when closing the solution

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Nice catch!
