### ISSUE TITLE
🐛 BPMN-Studio Crashes When Opening Diagrams Too Fast or at the Same Time

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1026]
#### Describe your issue

When opening a diagram while the BPMN-Studio is starting by opening another diagram.

![fast](https://user-images.githubusercontent.com/20394992/46811741-a05a3680-cd73-11e8-9af5-3f12b13b47cd.gif)

When opening more than two diagrams the BPMN-Studio just crashes immediately.

![multiple](https://user-images.githubusercontent.com/20394992/46811920-fa5afc00-cd73-11e8-8918-b6599688ceac.gif)

#### How can others reproduce the issue?

- Open two or more diagrams at the same time.
- 2 Diagrams:
	- **Notice that an error is shown**
- More than 2 Diagrams:
	- **Notice that the BPMN-Studio immediately closes after starting**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Auch interessant: Was passiert, wenn ich mehrere Diagramme in ein geöffnetes Studio dragge und droppe?

**Comment by alexanderkasten** [comment]
> Auch interessant: Was passiert, wenn ich mehrere Diagramme in ein geöffnetes Studio dragge und droppe?

Dann werden alle Diagramme den `Open Diagrams` hinzugefügt und eins davon geöffnet.

**Comment by alexanderkasten** [comment]
Tritt nicht mehr auf.
