### ISSUE TITLE
Diagram names are not validated when opening a solution

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1028]
#### Describe your issue

Currently, we limiting the characters when creating a new diagram to prevent characters that may break the diagram itself or enable attacks such as xss. 

The problem is, that you can rename a diagram on the filesystem and open the folder with the solution explorer, the diagram names are not validated anymore. 

Fun fact: Every slash in the diagrams name gets replaced with a double dot for whatever reason (maybe some kind of _emergency escape_ from aurelia or electron?). 

#### How can others reproduce the issue?

* Create a diagram on the file system
* Rename the diagram to an illegal name
* Open the Folder that contains the diagram with the solution explorer

#### Possible solution

Before loading the diagrams into the SolutionExplorer, the names of the diagrams should be validated. If a Diagram with an invalid filename was found, this diagram should not be added to the opened solution and the user should get notified about that. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Das Problem mit den illegalen Charactern geht zurück auf die Identität von Dateinamen und Prozess-ID.
