### ISSUE TITLE
Add first diagram after installation (initial solution)

### ISSUE THREAD

**Issue by nox-do** [process-engine/bpmn-studio#1030]
#### Describe your issue

With a fresh installation of BPMN-Studio it's not intuitive on how to start the "thinking" process. It's somehow hidden to the user that it's required to "open" a solution first  to actually "create" one

#### How can others reproduce the issue?
Fresh installation with no solution (folder) selected

#### Possible solution
- Guide user through the need of creating a solution folder the first time
- Add a "+" in the UI of the solution explorer that allows to add a folder

- Ask UX team

#### What's your setup

- BPMN-Studio Version (`4.6.0`):
- OS (`Windows`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
This is indeed true. And sadly: tricky.

We discussed something like VS Code does:

https://github.com/process-engine/bpmn-studio/issues/942

This is something I would like to see.

But simply open a default diagram to start thinking could be a first solution.  ;)

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt.
