### ISSUE TITLE
🐛Nightly build on master fails on publish

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1033]
#### Describe your issue

Currently the nightly build of the master branch fails in the publish step.

https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/master/299/pipeline

#### Possible solution

This is most likely a problem in the jenkins file since jenkins shouldn't even try to publish on the master branch in nightly builds.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
The build got deleted by somebody.... I cant check why this failed.

**Comment by SteffenKn** [comment]
This happened again. Here is the error message:

<img width="783" src="https://user-images.githubusercontent.com/20394992/47990045-cbbc1100-e0e6-11e8-9483-d817275d395c.png">

**Comment by Paulomart** [comment]
This is a problem with npm. We can just do a `npm publish || true`, but this is kinda of a hack.

**Comment by SteffenKn** [comment]
Can't we just check which npm version is released?
If the version is already released, we can't release it anyway, but if npm, for whatever reason, erroneously says that it has successfully released a version, even though that's not the case, it could be re-published in a later build.

**Comment by Paulomart** [comment]
The package was not published before, its a problem with the cli.

1. Jenkins runs npm publish
2. CLI get 500 from registry for PUT request
3. CLI retries PUT request 
4. Registry returns 403, CLI fails
