### ISSUE TITLE
New diagram with same name as existing one causes diagram to be overwritten

### ISSUE THREAD

**Issue by nox-do** [process-engine/bpmn-studio#1035]
#### Describe your issue

By adding a new diagram with same name or name with trailing or ending blank overwrites existing diagram with new default

#### How can others reproduce the issue?

In BPMN-Studio
- Design a diagram (at least do a change that you recognize
- Safe diagram
- Add diagram with same name (In addition tray it out with trailing / ending blanks)

#### Possible solution

Deny name with note to end-customer. eg. "Diagram with this name already exists

#### What's your setup

- BPMN-Studio Version (`4.6.0`):
- OS (`Windows`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
With version 4.7.0 those leading or trailing whitespaces are not allowed during diagram creation.
With this in mind it shouldn't be possible anymore to write diagrams with the default diagram from inside BPMN-Studio.
I will close this Issue since the bug is fixed.

**Comment by Vyperus** [comment]
@nox-do Ah ok I didn't know you meant the actual "deployment" of the diagram. Yes that's totally right. The diagram gets overwritten without a warning.
This will be solved when we get a complete and thought through deploy mechanism but for now a simple modal telling the user that this action will overwrite the existing diagram on the PE database will do the trick imo.
I will open another Issue for that.
