### ISSUE TITLE
Include documentation in deploy package (Release)

### ISSUE THREAD

**Issue by nox-do** [process-engine/bpmn-studio#1036]
#### Describe your issue

Idea would be to include either:
- a link to the online documentation in BPMN Studio 
- or include the documentation delivered with release

#### How can others reproduce the issue?

n.a.

#### Possible solution

Place "Help" or "online Documentation" in main navigation
Including the documentation within the release would ease up maintenance
#### What's your setup

- BPMN-Studio Version (`4.6.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
Refers to https://github.com/process-engine/bpmn-studio/issues/951 somehow
- [x] I've included all the information that i think is relevant

**Comment by cmg-dev** [comment]
@Vyperus What is left? We include a Link now; shall we break this down into smaller issues?
