### ISSUE TITLE
After deploy of diagram user get's redirected (almost) without notice

### ISSUE THREAD

**Issue by nox-do** [process-engine/bpmn-studio#1037]
#### Describe your issue

- After deploying a diagram the BPMN-Studio redirect the user to the PE Server view. Potentially ok. 
- But no information is provided beside the little database icon on top of the diagram instead of the folder symbol before,

#### How can others reproduce the issue?
Draw diagram or modify a (local) existing one.
Press "Deploy to process engine"

#### Possible solution

- Either do not redirect
- Or (what I prefer) highlight the selected or active diagram in solution explorer

#### What's your setup

- BPMN-Studio Version (`4.6.0`):
- OS (`Windows`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by farmanp** [comment]
Does this require help? Would love to help out make this usable and improve the experience

**Comment by Vyperus** [comment]
@farmanp Sure! :) 

But first of all you will need a little setup. Fork the repository and follow these instructions.

https://github.com/process-engine/bpmn-studio#setupinstallation

Then feel free to propose a PR, if you need any help just ask!

**Comment by cmg-dev** [comment]
@nox-do Great issue.
@farmanp Thanks for your interest :) 

Here some additional information:

We thought it would be a good thing to smoothly start editing, deploy the first Version  and then be able to hit the Play button.

That is the explanation for the silent redirect.

To implement this holistic:

1. Implement a **new** route in the processmodel-execution-part of the Management API

   This route would be able to allow deploy and immediately play a diagram.
   I believe we would need to touch [Management API HTTP](https://github.com/process-engine/management_api_http) and [Management API Core](https://github.com/process-engine/management_api_core).


Things I do not have considered:

1. How the proposed solution interacts with the INSPECT functions.
