### ISSUE TITLE
Auto update message 

### ISSUE THREAD

**Issue by nox-do** [process-engine/bpmn-studio#1039]
#### Describe your issue

With windows. But I guess there might be other reasons the message 
"The autoupdater is currently unavailable."

#### How can others reproduce the issue?

Install BPMN-Studio on Windows. (There might be several server side reasons which trigger this message also).

#### Possible solution

Show message just once. Or give the option by checkbox to not show again.

#### What's your setup

- BPMN-Studio Version (`4.6.0`):
- OS (`Windows`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant

**Comment by Vyperus** [comment]
With version v4.7.0 this message won't show up anymore. And when version 4.8.0 is released the auto updater should work on windows as well as on macOS.
I will close this for now :)
