### ISSUE TITLE
🐛 Uninstaller does not Remove Local PE Instance

### ISSUE THREAD

**Issue by nox-do** [process-engine/bpmn-studio#1041]
#### Describe your issue
At least with the Windows Version the installer routine does not remove the local PE server and diagrams from the system during uninstall

#### How can others reproduce the issue?
1. Install BPMN-Studio
2. Create a diagram
3. Deploy diagram to PE
4. Close and uninstall BPMN Studio
5. install again and start BPMN Studio.
- Server still holds the former diagrams 

#### Possible solution
Potentially ask user during uninstall to optionally remove server components and deployed Diagrams
If no diagram is deployed uninstall completely without extra question

#### What's your setup
- BPMN-Studio Version (`4.6.0`):
- OS (`Windows`): ##Not tested, but could be on Mac too

#### Issue checklist
Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant

**Comment by cmg-dev** [comment]
This happens on all platforms.

The BPMN-Studio uses a ProcessEngine which is configured to use a SQLite Database.

More precise: the SQLite file ist what is not removed!

Installing the BPMN-Studio again, will just pick up the present SQLite file.

@Vyperus Can you add an issue that explains how to delete the SQLite file.
Please include the location of the files on all systems.
We will link to the issue in several places.

**Comment by nox-do** [comment]
@cmg-dev  Why shouldn't we ask the user in _addition_ to optionally remove "All **locally** deployed processes)" during the un-install? Also I could imaggine to open the folder containing the SQLite in eg. finder/explorer at the end of the un-install routine. Then the user could decide later but than he get's directed to the correct location already.

**Comment by cmg-dev** [comment]
@nox-do Actually this is a good solution ;) We already discussed this, but:

1. We will search for a mechanism to reasonably bring this to ALL platforms.
1. Doing this in uninstall might not be easy, as you could have used a different type of Database-- like PostgreSQL.
1. As you know the Windows platform is heavy with wizards for installation, but linux/macOS are not.

But we will have another look at this.
I think we will find this soon in the Studio.

👍

**Comment by Vyperus** [comment]
@cmg-dev @nox-do 
I provided some simple instructions to delete the SQLite files manually here: https://github.com/process-engine/bpmn-studio/issues/1056

Please feel free to ask any questions if you have problems with that instructions.
