### ISSUE TITLE
🐛Diagram on PE gets overwritten without warning

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1050]
#### Describe your issue

Relates to #1035. 

When you deploy a diagram to the connected PE and it has the same name as an already deployed diagram, the deployed diagram gets overwritten without warning. This gets increasingly confusing as the PE shows the process name and not the file name in the Solution Explorer.

#### How can others reproduce the issue?

- Start BPMN-Studio; Open a Solution.
- Create a diagram; Name it `test`.
- Deploy it.
- Now close and open BPMN-Studio again; Open a different solution.
- Create a diagram; Name it `test` again.
- Make a change to it.
- Deploy it.

#### Possible solution

Add a modal that shows up when the user will overwrite an existing diagram on the PE with the deploy mechanism.

#### What's your setup

- BPMN-Studio Version (`4.7.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
Would the Diagram would also be overwritten on the ProcessEngine even when we use the Diagram name instead of the ProcessName? I don't think that changing the name of the uploaded Diagram alone to the actual Diagram name would fix this issue.
