### ISSUE TITLE
🐛Docker Image Broken

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1052]
#### Describe your issue

If you manage to find the bundle on docker hub, download it and start it BPMN-Studio is available on port 9000 on your machine.
This works but every link to an icon or assets is broken.

#### How can others reproduce the issue?

- Download latest docker container
- Start it

#### Possible solution

1. Fix the docker container.
2. Add a description on how to find the docker container to the README.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
https://hub.docker.com/r/5minds/bpmn-studio-bundle/

**Comment by Vyperus** [comment]
Is it fixed? Or is that the fix? IF I pull the latest version of the docker container now the start screen logo still doesn't gets displayed.

**Comment by dominikkaminski** [comment]
@Vyperus This issue occours also in NPM Package if you install bpmn-studio globally.
This is not a Docker issue-

**Comment by Vyperus** [comment]
Even though this might not be a docker problem the issue still exists.
Please stop closing not solved issues without any replacement.
Relates to: #1113

**Comment by alexanderkasten** [comment]
Fixed now.
