### ISSUE TITLE
🐛Process name used instead of file name when deploying

### ISSUE THREAD

**Issue by DevBastiS** [process-engine/bpmn-studio#1060]
#### Describe your issue

When uploading a diagram to a PE the process name is used instead of the file name.
This leads to confusion since the file name can be hugely different to the process name.
Then you got the same diagram with different names.
And what makes this even worse we are overwriting a diagram on the PE by deploying.
That diagram on the PE sometimes does not have the name as the file but gets overwritten when you deploy it.

Relates to #1050 

#### How can others reproduce the issue?

- Create a diagram called `test`.
- Edit the diagram and name the process `test2`.
- Deploy the diagram.
- See how it gets displayed with `test` in the solution section of Solution Explorer and `test2` on the PE section.

#### Possible solution

Take the file name to upload the diagram to the PE.

#### What's your setup

- BPMN-Studio Version (`4.7.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
The problem is, that the consumer api offers no direct way to return a process model with a given name.

* The Consumer API receives the ProcessModel from the Process Engine using the `getProcessModels()` Method.
     * The Return Type is an Array of type `Model.Types.Process`
     * This type contains the Process Name
* Then the the Consumer API retrieves the raw XML of the ProcessModel by using `convertProcessModel()` 
     * This Method takes the `ProcessModel` Object and converts them into an internal `ProcessModel` Object

The problem is, that the name gets lost in the convertProcessModel() Method https://github.com/process-engine/consumer_api_core/blob/develop/src/converters/process_model_converter.ts#L40.

**Comment by robpal94** [comment]
Another Problem is that, altough the ProcessEngine returns the `id` and a name, it seems that the `name` field is always the same as the id field. Furthermore, the ProcessEngine does not seems to case about the internal _name_ column at all. Rather, it seems to parse the ID from the _xml_.

**Comment by rrrene** [comment]
Das wird im Rahmen von OKR jetzt angegangen. :+1:

**Comment by ElRaptorus** [comment]
Dabei sollte aber erwähnt werden, dass das backendseitig nur für die AtlasEngine implementiert wird, nicht mehr für die ProcessEngine. Das wäre einfach viel zu viel Aufwand das in die PE noch einzubauen.
