### ISSUE TITLE
`SendEmail` example no longer reproducible with bpmn-studio

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#1083]
#### Describe your issue

ServiceTasks have been hardcoded to HttpService and ExternalTaskService.
Mentioned example(which you can find both in the examples and in the documentation repo) requires the mailservice.

#### Possible solution

Add mail service as option for service task.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I think we should allow calling generic services.

**Comment by LeoTT** [comment]
I think the processEngine should expose the information which services are callable with which parameters instead.

**Comment by SteffenKn** [comment]
But what if you are not connected to a ProcessEngine?
We should still have some default services and maybe add some extra services if the ProcessEngine supports more than just the default services.

**Comment by LeoTT** [comment]
ServiceTasks do support the old configuration again. Will therefore close this.
