### ISSUE TITLE
Copy from XML View is not possible 

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1102]
#### Describe your issue

It's not possible to copy the content of the xml view into the systems clipboard. Althogh you can select it, `ctr/cmd + c` has no effect at all. 

#### How can others reproduce the issue?

*  Try to copy something from the XML View and Paste it.
* See, that this is not possible

#### Possible solution

It may be the modeler, which overrides the Copy and Paste Shortcuts, since it does not get unbind from the dom. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
👍 I like it.

This also re-enables `cmd-f` in xml view (at least with browser, electron has no `cmd-f`). 
Fixes #289 too.
