### ISSUE TITLE
🐛Diagram elements are not colored in the inspect correlation view

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1121]
#### Describe your issue

Elements, which where colored in the detail view, do not have any colored elements in the inspect correlation view.

<img width="1412" alt="screenshot 2018-11-08 at 13 07 46" src="https://user-images.githubusercontent.com/38498731/48197930-86eae100-e357-11e8-807b-bd6c5fb91fa7.png">

<img width="1412" alt="screenshot 2018-11-08 at 13 07 59" src="https://user-images.githubusercontent.com/38498731/48197935-894d3b00-e357-11e8-863f-9c21b5e0e2b4.png">

#### How can others reproduce the issue?

* Set a color to an element
* Execute the process
* Switch over to the inspect correlation view and select the last corrlelation
* See that no element is colored in the viewer. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This was done by purpose to make it easier to see which element is selected.
If one would have a diagram with grey elements it would be really hard to see which element is highlighted.
