### ISSUE TITLE
🐛Dropdown menu on Windows looks broken

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1122]
#### Describe your issue

The Dropdown Menu on windows looks kinda broken. 

![screenshot 2018-11-08 at 13 54 34](https://user-images.githubusercontent.com/38498731/48203678-6f682400-e368-11e8-84ee-18d3b8a08cd1.png)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
When i run the BPMN-Studio on windows it does not look that broken:
<img width="232" src="https://user-images.githubusercontent.com/20394992/48269965-216f2100-e439-11e8-844a-f53d93dc1fa3.png">
But it still looks like a default windows dropdown.

**Comment by Vyperus** [comment]
I will close this for now.
