### ISSUE TITLE
Studio does not wait until the internal ProcessEngine is ready 

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1129]
#### Describe your issue

Sometimes, the internal ProcessEngine takes too long to start. So when the Studio tries to initially query the ProcessModels of the internal ProcessEngine, the Studio only gets a
```
Connection Refused
```
error, since the internal ProcessEngine is not ready to accept requests yet. 

This happens more often when trying to start the ProcessEngine with an initial state (when the databases needs to be created).

#### How can others reproduce the issue?

* Grab a slower machine (or a VM)
* Remove the Databases, used by bpmn studio
* Start the Studio
* See, that there is no connected ProcessEngine in the Solution Explorer shown

#### Possible solution

* Wait a bit before querying the internal ProcessEngine for the ProcessModels.
* Let bpmn studo wait, until the internal ProcessEngine is ready and then update the SolutionExplorer / Query the internal ProcessEngine.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Wir sollten den vorgeschlagenen Polling-Mechanismus implementieren, um die ersten bspw. 10 Sekunden alle 50 ms zu prüfen, ob die PE da ist (bspw. über eine Health-Check-Route).
