### ISSUE TITLE
Cancel in form-UIWidget does same as Continue

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#113]
#### Describe your issue
Cancel button in UIWidget does not cancel but continue.
#### How can others reproduce the issue?
You could use the Prozess-erstellen-process.
Fill in name and key, click on cancel-Button and you will receive a confirm message that the process was created (which is obviously not expected).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
This seems to be an upstream issue in consumer_client.

**Comment by LeoTT** [comment]
What I would expect when clicking on cancel is that the forms disappears(probably return to process list) and I could reopen it whenever in the process instance list.

> abort, the UserTask will be submited but with empty contents (this is the case here)

@Paulomart is this desired behaviour? Would never expect that. If i wanted to send an empty form, I would not fill it and click on continue.

**Comment by Vyperus** [comment]
This Issue is out of date. The cancel button now cancels the user-task as expected.
