### ISSUE TITLE
Web version should display release version

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/bpmn-studio#1130]
#### Describe your issue

When opening BPMN-Studio as web version, it is not possible to see a release version.

#### Possible solution

Display release version f.e. in footer or in settings section

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Sobald das Menü, dass in der Electron-Variante nativ eingebettet wird, auch in der Web-Version verfügbar ist, wird hier ebenfalls ein `Help -> About`-Punkt sein, der die Version wiedergibt :+1:
