### ISSUE TITLE
Receiving an error when aborting user task

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/bpmn-studio#1133]
#### Describe your issue

Error receiving task list: ProcessModel with id undefined not found!

#### How can others reproduce the issue?

1. Start a process including a user task
2. Click abort

#### What's your setup

- BPMN-Studio Version (`4.10.0`):
- OS (`Linux`):
- Node (`8`):
- WEB

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Do you mean `cancel`?
I can not reproduce this. Can you send me your database?

**Comment by SteffenKn** [comment]
@dominikkaminski

**Comment by alexanderkasten** [comment]
@dominikkaminski

**Comment by dominikkaminski** [comment]
Fixed in current Version.
