### ISSUE TITLE
Backup Database And Write Last Version When Upgrading

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#1137]
#### Describe your issue

Currently is very hard to debug issues with the migration and update mechanism.

It would be easier if we had some data about it.

#### Possible solution

When upgrading to a another version the autoupdater should:

- Take a backup (zip) of the database folder
- Name it like this `database-backup_from_1.2.0_to_1.3.1.zip`.

This will help us to understand this kind of errors better.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
We should also think about removing old backups from time to time.

**Comment by Paulomart** [comment]
Why was this closed?

**Comment by alexanderkasten** [comment]
We have closed all issues with the `Triage Prio 2` label @Paulomart
