### ISSUE TITLE
♻️ Move ManualTasks into Own Component

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1138]
#### Describe your issue

Currently ManualTasks get displayed via the dynamic-ui.
Since ManualTasks are not as configurable as UserTasks they should be moved into their own component.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by MaFa961** [comment]
ManualTasks now have their own component like UserTasks.

**Comment by cmg-dev** [comment]
Thanks
