### ISSUE TITLE
✨"Date" and "Number" Is Not Supported in Dynamic UI.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1145]
#### Describe your issue

Currently the `date` and `number` form field type are not supported in the dynamic ui.
That means when adding a user task to a process with a form field of type `date` or `number` the BPMN-Studio is no longer able to run this process.

#### How can others reproduce the issue?

- Open up the BPMN-Studio
- Go to the Detail View of any diagram
- Add a UserTask with a form field of type `date` or `number`
- Run the diagram

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
I guess the best way to handle this is to show a warning when deploying the diagram (or saving ?). 
We shouldn't simply remove the options because they are specified in the bpmn standard.

**Comment by SteffenKn** [comment]
IMO it's not too hard to implement it so it would be more efficient to implement this in order to show a warning or so.

**Comment by MaFa961** [comment]
This issue is deprecated. Both form fields are supported.
The `number` form field is split into `Decimal` and `Integer`
