### ISSUE TITLE
🐛SolutionExplorer lets the User Delete Diagrams from FileSystem and ProcessEngine

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1165]
#### Describe your issue

After the architecture refactoring part 1 the SolutionExporer allows the user to delete diagrams from the ProcessEngine and from the file system.

Thats not bad, but the user should get a modal which asks whether the user is sure to delete the diagram, before deleting continues or gets aborted.

#### How can others reproduce the issue?

- click on the `x` while hovering over a diagram

#### Possible solution

- add a modal which allows to continue or to abort

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
@Paulomart I'm not quite sure what you're trying to sa<, but I can't remember a modal that warned me when I removed a diagram via the solution explorer.
