### ISSUE TITLE
🐛 LET: Boundary Event and Gateway Colorization Is Wrong

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1198]
#### Describe your issue

**Have a look at https://github.com/process-engine/process_engine_runtime/issues/187 as well.**

When using boundary events in some cases they get colored even though they should not.

This is because the boundary events do not have a token history, instead the let kind of guesses if the boundary event was used or not.

**To be exact:**
If the element after the boundary event has a token and the task on which the boundary event sticks has no token history or is still active the boundary event will be marked.

#### How can others reproduce the issue?

- Run [this](https://github.com/process-engine/bpmn-studio/files/2676438/LET-test-Boundary.bpmn.zip) diagram
- **Notice that the Boundary Event will be marked even though it should not.**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Same problem appears to happen with gateways.

Here's an example:
<img width="863" alt="bug" src="https://user-images.githubusercontent.com/21304781/50217061-e6d99c00-0387-11e9-9407-a617dab61f20.png">

Diagrams for that example can be found here: https://github.com/process-engine/example_processes/pull/31
