### ISSUE TITLE
🐛No Correlation Selected Even Though a Correlation Is Selected

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1206]
#### Describe your issue

<img width="873" alt="bildschirmfoto 2018-12-17 um 16 43 20" src="https://user-images.githubusercontent.com/17065920/50097876-1d45d880-021b-11e9-8974-2cb9fe112af8.png">

#### How can others reproduce the issue?

- Open the inspect correlation view with a process which has no correlation
- use the solution explorer to switch to a process which has some
- switch back to the first selected process
- switch back again
- see that a correlation is selected, and the message still appears

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Will be fixed in v4.14.0
