### ISSUE TITLE
💄 LET: Dynamic UI Modal: Improve Design

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1208]
#### Describe your issue

The dynamic ui modal title should contain the name of the task and an x button.
The dynamic ui should not contain the task name if it is opened by a modal.

Then only the modal body should be scrollable.

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Run a process with a User-/ManualTask
- Click on the User-/ManualTask
- **Notice that there is no modal title yet.**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by MaFa961** [comment]
This issue is out dated because of the new dynamic ui.

**Comment by SteffenKn** [comment]
This issue is not outdated.
Only the last point was solved.
The modal has still no title, but the dynamic UI.
