### ISSUE TITLE
Is a Process with an untyped ServiceTask valid? 

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1211]
#### Describe your issue

This is more a question: Should it be possible to execute a Process which contains a CallActivity that is only described with their properties but does not have any _Kind_?

Currently, there is no validation if the Kind of a service Task is set. So you can just define a ServiceTask and left the _Kind_ Dropdown in the default _-Choose Kind-_ state. 

(You can find this in the MailService example because otherwise, there is no way to call the MailService).

#### How can others reproduce the issue?

* Add a ServiceTask
* Left the Kind to _-Choose Kind-_
* Define the ServiceTask Properties like in the old way
* Execute the Process

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
The section in the PP about the service tasks is nothing more and nothing less than a help for users to configure their service tasks. You can ALWAYS just type your wanted properties in the properties section of the PP. 

So.. No, a diagram with a service task that has no kind is not invalid.

**Comment by cmg-dev** [comment]
@robpal94 Kind is a comfort feature for adding properties.

Kind is nothing, the BPMN-Specifies; yes, ist is possible to add ServiceTasks with no further configuration; this is consistent with the standard AFAIK, sadly :(
