### ISSUE TITLE
🐛 TimerEvents are still highlighted as active in the LiveExectution Tracker

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1227]
#### Describe your issue

A TimerEvent is still highlighted as Active, even when the Process finished.

![screenshot 2019-01-03 at 09 46 29](https://user-images.githubusercontent.com/38498731/50629354-80827b00-0f3c-11e9-91e1-f4db20a9e051.png)

#### How can others reproduce the issue?

* Load up this Process: [asdfa.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/2723077/asdfa.bpmn.zip)

* Execute the Process
* See, that the TimerEvent is still marked as being executed.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
With the develop version of the runtime, this issue seems to be fixed. However, I would let this issue open until we release the current develop runtime version and use them in bpmn studio.

**Comment by Vyperus** [comment]
With that logic we would have to leave every issue open until we release a new version ;)
Since we are closing issues when they are fixed on develop I will close this for now.
