### ISSUE TITLE
✨ Jenkins shall Build and Provide Artifact of Electron App

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#123]
## Describe your issue

1. The ProcessEngine Jenkins shall be able to build and provide the electron app.

1. Needs to push it to Github Releases IF the App gets a new release.

## Things to evaluate

Check if we can do:

1. Stable
1. Unstable
1. Nightly

Releases, that notifies the Electron App.

## What is to do?

?

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by MiguelACarballo** [comment]
https://github.com/process-engine-pro/organization/issues/42
