### ISSUE TITLE
🐛 When deploying a Diagram, the user does not get redirected to the Detail view on the ProcessEngine

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1230]
#### Describe your issue

When a diagram gets deployed, the user will not be redirected to the diagram's detail view on the ProcessEngine. 

Instead, the buttons on the navbar disappear and the following errors are thrown: 
```
index.js:17 Uncaught TypeError: Cannot read property 'trim' of undefined
    at a (index.js:17)
    at s (index.js:17)
    at index.js:17
```

Related: https://github.com/process-engine/bpmn-studio/issues/1228

#### How can others reproduce the issue?

* Open a Solution
* Try to deploy a Diagram 
* See, that the navbar buttons have been disappeared
* See also, that you where not redirected to the Detail View of the ProcessEngine

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Probably related to https://github.com/process-engine/bpmn-studio/issues/1228
