### ISSUE TITLE
🐛 Single Diagrams are still highlighted, if one Solution contains a Diagram with the same Name

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1231]
#### Describe your issue

If a single diagram and a solution which contains a diagram with the same name as the single opened diagram, both diagrams still get highlighted, if the user clicks on the diagram of the solution. 

**This only happens, when you open the diagram from the solution. Not from the single diagrams list!**

#### How can others reproduce the issue?

* Open a Solution
* Open a Single Diagram with the same name
* Open the Diagram with the same Name from the Solution
* See, that both entries get highlighted. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
So if you open the same file, in a solution and via drag&drop, they both get highlighted?

Well that doesn't sound like an Issue to me since it is the same file.
/cc @cmg-dev
