### ISSUE TITLE
🐛 Changing Diagram Does Not Always Work Correctly.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1241]
#### Describe your issue

When changing from a local stored diagram to a deployed diagram with the same name, the BPMN-Studio will not change the Diagram. Instead it just keeps working as if the diagram was never changed.

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Open a local diagram
- Deploy the diagram
- Change the deployed diagram
- Change back to the local diagram
- **Notice that the BPMN-Studio will neither show the 'Document Contains Changes'-Modal nor change the diagram.**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
Fixed by #1239

**Comment by Vyperus** [comment]
So what is the status here?
@alexanderkasten @SteffenKn 

Please don't just reopen and close and reopen issues without writing any comment.

**Comment by SteffenKn** [comment]
Alex closed this by accident and we both reopened this at the same time.
