### ISSUE TITLE
✨ Implement the new PropertyPanel as Plugin

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#128]
#### Describe your issue

Implement the new PropertyPanel as a plugin and let Charon consume it.
Now let it display the property panel.

#### How can others reproduce the issue?

Extract the PropertyPanel out of Charon and make it a plugin.
Now let Charon consume and use this plugin.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by MiguelACarballo** [comment]
https://github.com/process-engine-pro/organization/issues/42

**Comment by Vyperus** [comment]
Closed due to architectural changes.
