### ISSUE TITLE
🐛 `Inspect Correlation` view doesn't display the full ProcessModel initially

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1288]
#### Describe your issue

When switching to the `Inspect Correlation` view, the ProcessModel is partially located outside the views boundary. 

![bildschirmfoto 2019-01-17 um 13 09 26](https://user-images.githubusercontent.com/15343316/51317919-25cb4200-1a59-11e9-8b22-f36b48592c7d.png)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
We need to add the 'fit to viewport' functionally in the inspect correlation as well. 👍
