### ISSUE TITLE
🚸Validate the Identity Server Address

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1289]
#### Describe your issue

The Address of the Identity Server configuration should be validated before it gets applied. This way we can ensure that the Address of the Identity Server is always valid. 

In the current state, a not very helpful error message will be displayed if the user tries to connect to an Identity Server with a malformed URL. 

#### Possible solution

* Validate the URL of the Identity before applying it.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
It gets validated now.
