### ISSUE TITLE
✨ Contracts zur PluginAPI

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#129]
#### Describe your issue

Charon should offer all contracts needed to implement a plugin for certain tasks, for example the PropertyPanel.

#### What is to do?

Describe what contracts are needed to make it as easy as possible to develop new Plugins for Charon.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by MiguelACarballo** [comment]
https://github.com/process-engine-pro/organization/issues/42
