### ISSUE TITLE
🐛Creation of a new Diagram with ctrl + n hotkey does not work

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1292]
#### Describe your issue

When trying to create a new Diagram with the `ctrl + n ` hotkey, the following error is thrown: 

```
Uncaught TypeError: Cannot read property 'startCreationOfNewDiagram' of undefined
    at solution-explorer-list.ts:209
(anonymous) @ solution-explorer-list.ts:209
```

Another (maybe unrelated to the above) issue is, that there is no static `Desktop` directory in the users home directory. 

A few Examples:
* On the most Ubuntu Distributions, all folders in the users directory are translated into the System language. Example: _Schreibtisch_ instead of _Desktop_

* On Plain Debian Systems which where installed without a Desktop Enviromenent, there is no `Desktop` Folder in the users home directory at all. 

#### How can others reproduce the issue?

* Start bpmn Studio
* Make sure, that no Solution except the Solution from the internal ProcessEngine is opened
* Press ctrl + n 

#### Possible solution

At least on Linux, the default Directory for new Diagrams should be somewhere else (maybe a temp directory would be nice, also for other operation systems). 

Another alternative would be to open newly created diagrams as a SingleDiagram Solution instead of open a default Solution.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
I was not able to reproduce this. But I will wait for https://github.com/process-engine/bpmn-studio/pull/1394 to fix this entirely.

**Comment by robpal94** [comment]
Keep in mind that this depends on the system language you use. If you use english, this bug will not be reproducible since the _Desktop_ Folder is named so. 

As I described above, this issue appears, them the _Desktop_ Folder is not available (or named differently such as _Schreibtisch_.
