### ISSUE TITLE
🐛 Linux: Drag and Drop does not work

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1293]
#### Describe your issue

When dropping a bpmn File into BPMN Studio on Linux, only the file content will be displayed and the Diagram is not imported.

#### How can others reproduce the issue?

* Drop a bpmn File in the open Studio

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
This issue seems kinda hard to reproduce. For some reason, this will only happen if you drop the file at a specific place.

**Comment by Vyperus** [comment]
What place? Please provide more info or this issue will stay here forever.

**Comment by robpal94** [comment]
I wish I could tell. This issue seems to happen kinda random.

**Comment by Vyperus** [comment]
I failed to reproduce this Issue. Closing this for now.
