### ISSUE TITLE
✨ Display the version of the connected Runtime in the SolutionExplorer

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1296]
#### Describe your issue

The Version of the connected Runtime should be displayed in the SolutionExplorer. 

#### Possible solution

Display the version of the connected ProcessEngineRuntime when hovering (if the version string is available). 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
The problem with this is, that we don't actually can send http requests with the Studio natively. The only instance which can archive this is the `ManagementAPIClient` but Im not sure if it belongs there.

I would also hold back this feature, until we have some kind of dedicated route to ask only for the version (such as `localhost:8000/version`).

**Comment by Vyperus** [comment]
The Version is now displayed in a tooltip on the SolutionName.
