### ISSUE TITLE
✨ Replace PropertyPanel

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#130]
#### Describe your issue

Replace the standard PropertyPanel of bpmn.io with a self implemented solution.

#### What is to do?

The new PropertyPanel has to have this functionality: https://github.com/process-engine-pro/organization/pull/37

- [x] General
- [x] Pool
- [x] Message Event
- [x] Signal Event
- [x] Error Event
- [x] Escalation Event
- [x] Error End Event
- [x] Flow
- [x] Script Task
- [x] Call Activity
- [x] Forms
- [x] Extensions
- [x] Unify style for sections
- [x] Unify style for registers

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
#58

**Comment by LeoTT** [comment]
Had a look at the feature branch and might be able to give a tip.
For some functions you will need to access dependency injection system of the bpmn modeler.
It's using [didi](https://www.npmjs.com/package/didi).

Here's how I connected the didi dependency injection with aurelia ioc.
```typescript
...
const modeler: IBpmnModeler = new BpmnModeler({
    additionalModules: [IOCHook],
  });
...
```
```typescript
class IOCConnector {

  constructor(eventBus: IEventBus,
              canvas: ICanvas,
              commandStack: ICommandStack,
              bpmnFactory,
              elementRegistry: IElementRegistry) {
    this.registerInstances([
      [BPMN.eventBus, eventBus],
      [BPMN.canvas, canvas],
      [BPMN.commandStack, commandStack],
      [BPMN.bpmnFactory, bpmnFactory],
      [BPMN.elementRegistry, elementRegistry],
    ]);
  }

  private registerInstances(registrationTupels: [any, any]): void {
    const container: Container = Container.instance;

    registrationTupels.forEach((registration: [string, string]) => {
      container.registerInstance(registration[0], registration[1]);
    });
  }
}
const IOCHook: IDependencyHook = {
  __depends__: [],
  __init__: ['IOCHook'],
  IOCHook: ['type', IOCConnector],
};
```
Interesting question is, how does didi know which things (and in which order) to inject into my IOCConnector?
Didi checks the args of the constructor, so if you have a parameter called `commandStack` in the constructor it will look for registered CommandStack (and you will need to use the commandStack if you want to edit the diagram as far as I know).

**Comment by Vyperus** [comment]
Sadly the constructor gets handled before the aurelia-bind. Since the sections in the Propertypanel is handling all writing and editing of the properties i need
`this.moddle = model.modeler.get('moddle')`
to happen after the binding.
