### ISSUE TITLE
✨ Rename Charon itself

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#131]
#### Describe your issue

The scoping of charon (@process-engine) leads to the electron-builder not working properly, since 7z sees files with an @ as listfiles.
Also charon seems to be a hard part of the process-engine, which is not the case.

This is why we need to rename the package "charon" to "bpmn-studio".

This needs to be done before we can start implementing on https://github.com/process-engine/charon/milestone/1

#### What need to be done?

Rename Charon in every repo that has links to charon and charon itself.
Then rename the repository.

#### Related PR's

- [x] https://github.com/process-engine/skeleton/pull/27
- [ ] https://github.com/process-engine/charon/pull/132
- [ ] https://github.com/process-engine/consumer_client/pull/13
- [ ] https://github.com/process-engine/process_engine_meta/pull/23

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
We should _move_ the repository this time: https://help.github.com/articles/about-repository-transfers/
