### ISSUE TITLE
🐛 When being redirected from the Task View to the LET, clicking the LET's back button directs to the ended Task

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1311]
#### Describe your issue

When open a pending task using the Dashboard's Task view, the UserTask can be finished the _oldscool way_ (not via the LET). 

After finishing the Task, you get redirected to the let. You can now click on the _Back_ Button but it always tires to display the finished User Task, which is not available. 

![screen recording 2019-01-24 at 15 13 47](https://user-images.githubusercontent.com/38498731/51683879-23ce2980-1feb-11e9-91be-8f336aed31a9.gif)

#### How can others reproduce the issue?

* Start a ProcessInstance
* Navigate to the Dashboard
* Navigate to the Waiting Task List
* Click on the Waiting user Task
* Finish the Task
* Click on the _Back_ Button in the LET.

#### Possible solution

Do not just navigate back using the routers `back` instruction. Instead, try to navigate somewhere else. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This has already been fixed in #1225
