### ISSUE TITLE
♻️Refactor oidcConfig Usage

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1313]
#### Describe your issue

Currently the `electron.js` uses the `oidc-config.js` as oidcConfig, but the `app.ts and main.ts` are using the `open-id-connect-configuration`.
Both of them are containing some settings which are the same.

Maybe we could remove one file?

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
The oidc-config.js can be deleted if you make it possible to insert the config upon creation of the service. 

This shouldn't be too hard.

I updated the issue accordingly.

**Comment by alexanderkasten** [comment]
@Vyperus Weißt du zufällig noch welchen Service du meinst?

Ich hab mir das heute mal angeschaut und wie es aussieht kann die electron.js und app.ts/main.ts nicht die selbe oidc Kofiguration benutzen, da in der Konfig der WebstorageStateStore gesetzt wird auf window.localStorage. Da es in Node.js kein window Element gibt, kann Electron die vorher als JS gebaute open-id-connect-configuration Datei nicht richtig importieren/requiren.
