### ISSUE TITLE
♻️Refactor Using of Fetch Clients

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1314]
#### Describe your issue

We have 

- whatwg-fetc,
- fetch-ponyfill,
- aurelia-fetch-client,
- node-fetch

in our package.json.

We should refactor the usage of this packages and whether it is necessary to have four instead of having one or two (node & browser).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
These are never really directly used by us. Instead, they are some dependencies of other dependencies. 

`whatwg-fetc`:
* fetch-ponyfill

`fetch-ponyfill`
* Does not seems to be directly needed anywhere.

`aurelia-fetch-client`:
* `aurelia-open-id-connect`

`node-fetch`
* `fetch-ponyfill`
* `solutionexplorer.repository.management.api`

**Comment by rrrene** [comment]
Dependencies sollten nicht Dinge sein, die "einfach passieren". Lasst uns das analysieren :+1:
