### ISSUE TITLE
:sparkles: enable resizing of tasks

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#1320]
#### Describe your issue

It should be possible to resize tasks to support longer names for tasks.

#### How can others reproduce the issue?

Create a task with long name.

#### Possible solution

Enable resizing

#### What's your setup

- BPMN-Studio Version (`4.18.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
What exactly do you mean? Resize the task in the diagram?
If so there is no way I know of to enable this since this isn't a feature in bpmn-io.

See:
https://demo.bpmn.io/s/start

**Comment by SteffenKn** [comment]
BPMN-JS-Nyan also supports resizing, so it should not be that hard to implement this.
https://github.com/bpmn-io/bpmn-js-nyan

**Comment by roblen45** [comment]
I'm not exactly sure what it does, but I think that's how it can be done:

https://github.com/bpmn-io/bpmn-js-nyan/blob/master/lib/resize-all-rules/ResizeAllRules.js
