### ISSUE TITLE
Prompt before deleting a diagram

### ISSUE THREAD

**Issue by demdh** [process-engine/bpmn-studio#1321]
#### Describe your issue

The user should be prompted to confirm the deletion of a diagram.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Thanks for this suggestion.

I updated the Issue accordingly.

**Comment by Vyperus** [comment]
@demdh This was included by the mentioned PR and will be included in the v4.20.0 (next) release of BPMN-Studio.
