### ISSUE TITLE
🐛 Ignore the validation of a diagram when saving on FileSystem

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1348]
#### Describe your issue

Currently it is not possible to save "invalid" diagrams on the FileSystem even though the validation shouldn't have any effect here.

#### How can others reproduce the issue?

1. Create a diagram with two pools. (Currently not supported)
2. And try to save it on the FileSystem.

#### Possible solution

Don't check the validation when saving on FileSystem.

Generally Refactor the Validation into a service to get better error messages to show the user.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
I wonder if we even need some kind of _validation service_ since we now have implemented the _bpmn - Validator/Linter_.

**Comment by Vyperus** [comment]
The day the linter is able to check all rules correctly (not today) we won't need the validation service anymore and can refactor this into using the linter.
