### ISSUE TITLE
It is possible to select the current Process as a CallActivity target

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1364]
#### Describe your issue

You can select the currently opened ProcessModel as a target for a CallActivity in the same model.
This results in an endless loop when executing the Process.

#### How can others reproduce the issue?

* Create a new ProcessModel
* Add a CallActivity
* Set the target to the same ProcessModelId

#### Possible solution

Do not show the currently opened ProcessModel in the target list when adding a CallActivity.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Will be fixed in release v4.22.0.
