### ISSUE TITLE
Add colors to the bpmn-modeler

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#138]
#### Describe your issue

Maybe we should implement colors into the bpmn-modeler like https://github.com/bpmn-io/bpmn-js-in-color ?

#### Possible solution

Add the bpmn-js-color package to the bpmn-js-custom-bundle.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
After reviewing the colors of the mentioned additional Module i would like to add our own color functionallity, more oriented at the camunda modeler colors.
