### ISSUE TITLE
User has to Double Click on Cancel when the Save Unsaved Changes Modal is Shown

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1384]
#### Describe your issue

The user has to double click on the _Cancel_ Button from the _Save unsaved changes_ dialog. 
This only happens, when the target diagram name contains a character, which needs to be escaped in the destination url such as spaces.

#### Explanation

The Routing procedure has the following Steps: 

1. When navigating away from the detail view, the router creates a new `RouterInstruction` and pushes it to the router stack.

2. Now aurelia calls the `canDeactivate` method from the current view. This method displays the _Save Unsaved Changes_ modal and wait for the User decision. 
   * aka if we should navigate away or not

3. Because of this issue: https://github.com/aurelia/router/issues/302 we redirect the current routing instruction to the same route as we are coming from, if the User clicks on _Cancel_.
    * Basically, this is needed because otherwise, the history would be inconsistent. 

For some reason, the Aurelia Router creates duplicate `RoutingInstructions` in the first step, and buts both of then onto the router's instruction stack. 
This only seems to happen, if the target uri contains a character which needs to be escaped. Because of this, the whole routing away procedure is effectively executed twice.

#### How can others reproduce the issue?

* Create two diagrams.
    * Name one _diagram_ and the other one _diagram one_
* Make some changes in _diagram_
* Without saving your changes, try to navigate to _diagram one_
* See, that the _Save Unsaved Changes_ Modal is displayed.
* Try to click on _Cancel_
* See, that nothing happens (visually)
* Click on _Cancel_ again

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Do we encode the characters? Maybe Aurelia fixes the character encoding and creates a redirect.

**Comment by robpal94** [comment]
> Maybe Aurelia fixes the character encoding and creates a redirect.

Probably. But there are still questions about the routers behavior: 
1. Why does aurelia creates a whole new routing instruction for the redirect and does not
encode the characters before even creating the initial instruction? 
2. Why does this happen so irregular? 
Try to navigate to a route containing the character 'Ä' three times. In two of three cases, the router does not create the new instruction with the encoded characters. In one case, it does.

**Comment by robpal94** [comment]
Related Bug Report: https://github.com/aurelia/router/issues/630
