### ISSUE TITLE
Add Minimap to BPMN Modeler

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#139]
#### Describe your issue

We could add a minimap to BPMN-Studio.

![jan -24-2018 15-37-30](https://user-images.githubusercontent.com/17065920/35338021-0e8212d2-011d-11e8-851e-059a80372386.gif)

https://github.com/process-engine/bpmn-io_custom-bundle/pull/4

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@alexanderkasten @Vyperus 

Let's continue like this:

1. Please add a MiniMap.

   Make it **not** foldable; so that we have a minimap at all!

1. Then make if foldable with an icon.

   @alexanderkasten please create a separate issue for the foldability.

/cc @moellenbeck
