### ISSUE TITLE
👷 Sporadic build failures caused by NodeJS plugin

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1391]
#### Describe your issue

We are experiencing frequent build failures on the develop and master branches during the `build electron / Build on MacOS` step.

Sometimes the system cannot find an npm package:
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/master/499/pipeline/100#step-129-log-3

At other times, complains about a binary file that cannot be executed:
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/develop/703/pipeline#step-146-log-2

Since these errors do not occur with any kind of predictability, we have to re-run the builds until they succeed. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
This is an upstream issue: https://issues.jenkins-ci.org/browse/JENKINS-55961

**Comment by ElRaptorus** [comment]
@Paulomart I see, thx for the info.

**Comment by Paulomart** [comment]
The release for the bugfix is now pending.

**Comment by Paulomart** [comment]
The plugin was released and updated on jenkins.
