### ISSUE TITLE
✨ Add "Deploy" Button to Solution Explorer for quick access

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1395]
#### Describe your issue

It would be nice to have a "deploy" button in the solution explorer, which would pop up when you hover over a diagrams name.
Right next to the "edit" and "delete" buttons.

When deploying multiple diagrams from a large solution, it can get really tiresome if you always have to move to the top-right corner to click that "deploy" button.

This could look like so, for example:

![bildschirmfoto 2019-03-05 um 13 53 33](https://user-images.githubusercontent.com/15343316/53807013-cb296f00-3f4e-11e9-8d11-7c5dc2fcf24c.png)

I got no real preference for the order of the buttons, but at first glance I'd say placing it at the far left, as illustrated in the screenshot, would be best.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
We should wait with the implementation of this until this https://github.com/process-engine/bpmn-studio/pull/1416 is finished.
Then we can add a simple new entry to the context menu.
