### ISSUE TITLE
🐛Bug With Single Diagrams of Other Paths

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1397]
#### Describe your issue

If you have opened several single diagrams which comes from another path than the other single diagrams, they get lost after a reload or restart of BPMN-Studio.

#### How can others reproduce the issue?

- drag and drop a diagram from e.g. your desktop to the studio
- drag and drop a diagram from another directory to the studio
- reload it
- see that only one diagram is opened

#### What's your setup

- BPMN-Studio Version (`4.23.2`):
- OS (`OS X` + `version`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Do they have the same name?

**Comment by alexanderkasten** [comment]
@Vyperus No

**Comment by alexanderkasten** [comment]
Der fix befindet sich schon auf develop.
