### ISSUE TITLE
Check the Runtime Version on Connect

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1400]
#### Describe your issue

Currently we don't have any mechanism in place that tells the user that the PE he is trying to connect with has or has not the right Version.

For Example:
A breaking change in the PE, lets say version 6.0.0 to 7.0.0, often leads to some adjustments in the Studio as well.
But with that change the Studio would not be able to work with a PE of version 6.0.0.

We should show that information to the user if he tries to connect the Studio with an out dated PE.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Zusätzlich benötigen wir ein Konzept zu Abwärts- und Aufwärtskompatibilität.

**Comment by rrrene** [comment]
Plan für Skateboard-Version:

Vergleich mit der im Studio gebundelten PE-Version (also der in `package.json`)

- [ ] für höhere Versionen der PE ein blaues Info-Icon, das auf Klick erklärt, dass die PE neuer ist als das Studio
- [ ] für PE-Versionen mit der gleichen Major wie die gebundelte PE-Version kein Icon
- [ ] für ältere Versionen der PE, die eine niedrigere Major-Version haben, ein gelbes Info-Icon, das auf Klick erklärt, dass die PE wesentlich älter ist als das Studio
- [ ] für PE-Versionen, die ihre Version nicht mitteilen können, wird keine Verbindung angeboten
