### ISSUE TITLE
Newly created diagrams should be stored in memory

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1401]
#### Describe your issue

Currently the newly created diagram are directly stored on the desktop of each OS.

It would be nice if the diagram wouldn't be stored anywhere but the memory of the application until the user tells the Studio to save it and where.

#### How can others reproduce the issue?

Create a new diagram.
See where it is located.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
> but the memory of the application

Im Speicher geht nicht, weil die "neuen" Diagramme dann keinen Neustart überleben würden, aber Alex implementiert das in dem referenzierten PR #1394 :+1:
