### ISSUE TITLE
Parent Node Required

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1402]
#### Describe your issue

There seems to be an error on the heatmap.

![bildschirmfoto 2019-03-07 um 09 20 51](https://user-images.githubusercontent.com/17248802/53942225-7b67b680-40ba-11e9-975e-c2946f0d0daf.png)

This doesn't break anything but it is a strange behavior that we should solve.

#### How can others reproduce the issue?

I produced it like this:

1. Open a diagram that is deployed on an PE.
2. Open the Inspect View.
3. Open the Heatmap.
4. Open the Inspect Correlation.

#### What's your setup

- BPMN-Studio Version (`4.23.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
I can reproduce this error when navigating away from the heatmap.

I also get the following error (twice) when navigating to the heatmap.

<img width="530" src="https://user-images.githubusercontent.com/20394992/53944864-89203a80-40c0-11e9-89e7-59a7375c7a9d.png">
