### ISSUE TITLE
Cannot read property 'base' of undefined

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1403]
#### Describe your issue

Currently this is what happens when you open the LET:
![bildschirmfoto 2019-03-07 um 09 27 10](https://user-images.githubusercontent.com/17248802/53942491-33955f00-40bb-11e9-8446-f9bbfd7763e6.png)

#### How can others reproduce the issue?

1. Deploy a diagram.
2. Start it.

#### What's your setup

- BPMN-Studio Version: `4.23.0`

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
I cannot reproduce this with the current develop version.

**Comment by Vyperus** [comment]
Me neither. Closing this for now.

**Comment by SteffenKn** [comment]
I still get this error a lot.

**Comment by MaFa961** [comment]
I cannot reproduce this on develop with version 5.1.2.

Is this issue still up to date?

**Comment by robpal94** [comment]
@SteffenKn

**Comment by SteffenKn** [comment]
I can still reproduce this.
