### ISSUE TITLE
TimerEvent definition is reset when clicking away

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1404]
#### Describe your issue

Its not possible to add a new either Boundary or Intermediate TimerEvent because its defintion gets
reset when clicking away. 
Because of this, the bpmn Linter will prevent the diagram from beeing saved, since a Diagram which contains a TimerEvent without a definition is invalid.

#### How can others reproduce the issue?

* Create a new Process
* Add a TimerEvent (either Boundary or IntermediateCatch)
* Try to add a Defintion
* Click away
* See, that the Definition got reset
* Try to save the Process and see, that this is not possible.

#### What's your setup

- BPMN-Studio Version (`4.x.x`):
- OS (`Windows/OS X/Linux` + `version`):
- Node (`node --version`):
- NPM (`npm --version`):
- Docker (`docker version --format '{{.Server.Version}}'`):

> You can remove this section if it's irrelevant to the issue
> (for example for certain questions or feature requests).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Will be Fixed in 4.25.0
