### ISSUE TITLE
🚸 If the Linter Is Disabled and There Is an Error in the Diagram, the Deploy Button Is Disabled, but the User Cannot Really Tell Why.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1405]
#### Describe your issue

When there is an error in the diagram the deploy button is deactivated.
When the linter is activated the user might realize why the button is disabled, but as soon as the linter is disabled there is no hint that tells the user why he can not deploy the diagram.

#### How can others reproduce the issue?

- Open a diagram
- Add some lint errors
- Disable the linter
- **Notice that one can not really say why the deploy button is disabled.**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Should be a part of #1399

**Comment by ElRaptorus** [comment]
@SteffenKn There is a tooltip in place that tells the user why deployment is not allowed.

![Bildschirmfoto 2019-03-18 um 11 47 54](https://user-images.githubusercontent.com/15343316/54525298-2e19fd80-4974-11e9-8f7e-3f0ef6f1bdc8.png)

So the user does get an info about it. But I'd agree that this should be a lot more visible.
Perhaps we should make that linter icon a little more prominent, if the diagram does contain linting errors. Dunno, maybe paint it red? It would be pretty hard to miss it then.

**Comment by ElRaptorus** [comment]
So I've been experimenting a little and came up with this:

![Bildschirmfoto 2019-03-18 um 12 29 34](https://user-images.githubusercontent.com/15343316/54527242-97503f80-4979-11e9-9507-80e9ef501339.png)

The diagram has a misconfigured gateway, thus provoking a linter error.

I think that shiny red is kinda hard to miss now.

@Vyperus @cmg-dev @SteffenKn @alexanderkasten

**Comment by SteffenKn** [comment]
@ElRaptorus The tooltip was added after I opened up this issue.

When the issue was created there was no tooltip or anything else that told the user to use the linter.

**Comment by ElRaptorus** [comment]
@SteffenKn Ah, I see.
I still think making the linter button more prominent is a good idea. 
This won't leave the user hanging until he sees the tooltip (which takes far too long to load anyway, ihmo).
