### ISSUE TITLE
🐛 Linter Does Not Get Updated in Some Cases

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1406]
#### Describe your issue

For example, if you add a form field to a UserTask with the same ID as the UserTask, the Save or Deploy button, depending on if the diagram is a local diagram or a deployed one, is disabled, but the linter does not display an error until it is disabled and re-enabled.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
The described faulty behavior should be fixed with: https://github.com/process-engine/bpmn-studio/commit/a84bde535a84f6002c4ae480eae3c60b0e173d12.

This corrects the faulty behavior of checking form field ids to be unique along with all other elements in the diagram.
