### ISSUE TITLE
🔧Remove build from Post Install Hook

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1410]
#### Describe your issue

Currently, we always build the packages after installing them. Since the defined script also use the `build` script, we effectively build the packages twice. 

This is a bit time consuming and kinda unnecessary.

#### How can others reproduce the issue?

* Run `npm install` 
* See, that after the install, the build step is executed
* Run `npm start`
* See, that the build step is executed again

#### Possible solution

Remove the `build` step form the post install hook. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I think it is perfectly valid for both UseCases to have the build step.
Remember, installing and starting the Studio are very different things.

When I reinstall the Studio I'd very much like to see if it is ready to use after the installation has finished, or if any updates, which may have been installed with the reinstall, are causing trouble.
Running the build right after the installation will tell me that.

Besides, just how often do you actually run a reinstall before starting your application? 
If you say "every time" now, you may want to consider rethinking that practice. 😉
