### ISSUE TITLE
🐛The process name is always truncated

### ISSUE THREAD

**Issue by demdh** [process-engine/bpmn-studio#1418]
#### Describe your issue

The process name is truncated both in the Solution Explorer and in the window header. This means that the process name is nowhere completely visible for processes with longer names.

![image](https://user-images.githubusercontent.com/13077985/54183822-65386c80-44a5-11e9-8f44-f7fe5561ddc7.png)

#### How can others reproduce the issue?

Use a longer process name (>30 characters).

#### What's your setup

- BPMN-Studio Version (`4.x.x`): 4.24.1

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Thanks for pointing that out.
We will try to fix this as soon as possible maybe even put that fix in the release of v4.25.0 this week.
Stay tuned!

**Comment by Vyperus** [comment]
@demdh A fix for this was added with this PR: #1419

This Fix will be included in the Release v5.0.0 tomorrow.
