### ISSUE TITLE
Linter sometimes throws an Exception

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1427]
#### Describe your issue

In some cases, the following exception is thrown by the linter: 

```
Unhandled rejection TypeError: Cannot read property 'IntermediateThrowEvent_1i3zhyy' of null    at file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:44517:34From previous event:    at Linting.update (file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:44493:14)    at file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/app-bundle.js:2596:40    at file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:20658:17    at importBpmnDiagram (file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:15516:9)    at Modeler.Viewer.importDefinitions (file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:20811:16)    at file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:20655:18    at file:///Users/robin/Documents/process_engine/bpmn-studio/scripts/vendor-bundle.js:14376:13
```

This happens kinda random and is really hard to reproduce.

#### Possible solution

You can try to do one of the following things: 
* Rename a UserTask
* Toggle the TimerDefinition Type 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Fixed in Release v5.0.0
