### ISSUE TITLE
Update "aurelia-route-recognizer" 

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1432]
#### Describe your issue

The current version of `aurelia-route-recognizer` the not the latest one.

We should update the package to solve some faulty behavior like this here:
https://github.com/process-engine/bpmn-studio/pull/1385

Updating `aurelia-route-recognizer` to `1.3.1` would solve this.
However this comes with other behavior we need to address when updating this.

For example it seems to me that either the wildcard notation in the route settings have changed or they are not allowed anymore since our normal "params" like "diagramName" have moved to the "queryParams" leading to faulty behavior mainly in the navbar.

#### How can others reproduce the issue?

1. Update `aurelia-route-recognizer`.
2. Run `npm run reinstall`.

#### Possible solution

Update it and address the needed changes to our code.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Schließe in favor of #1384
