### ISSUE TITLE
🐛 PageSize in ProcessInstance list gets circumvented, when dealing with correlations with multiple ProcessInstances

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1436]
#### Describe your issue

When displaying correlations with multiple process instances, the number of ProcessInstances is not accounted for by pagination.

#### How can others reproduce this issue

This was discovered by setting the Page-Size to 1 and then starting multiple Correlations with CallActivities.

![Bildschirmfoto 2019-03-15 um 11 03 09](https://user-images.githubusercontent.com/15343316/54423865-ef850880-4711-11e9-871a-14e2757cb99d.png)

- In this example, I set the page size to 1. 
- Then I started the `CallActivityTest` process twice  - [Download diagrams here](https://github.com/process-engine/bpmn-studio/files/2970453/diagrams.zip).
- Each of these processes created a Subprocess that runs in the same correlation (because of the CallActivity used)
- since `PageSize` is set to 1, I'd have expected only one ProcessInstance to be shown here.
- But since the Correlation has multiple instances, I got two per page.

So if I had a correlation with a hundred ProcessInstances, I'd get a page size of 100, regardless of what is configured with pagination.

This effect occurs, because the data model looks like so:
```js
Correlation: {
  id: 'abc',
  [....]
  processModels: [{
    id: 'hello'1,
    [....]
  }, {
    id: 'hello2',
    [....]
  }]
}
```

The binding of the view regards each correlation as a page entry, not the processModels associated with that correlation.

#### Possible solution

Easiest way would be to flatten all the ProcessModels into a single Array and then use that Array as a BindingSource for the view.

My preferred solution would be to hide all ProcessInstances of a correlation in a collapsible sub panel within the correlation entry.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
We refactor this table.
Showing only the active correlations and on a click on a correlation we could display the running Instances below it.
Kinda like a foldable table.

**Comment by ElRaptorus** [comment]
That'd be my preferred solution as well. 👍
