### ISSUE TITLE
🐛When Logging in to a Remote Solution, All Remote Solutions with the Same Authority Are Logged In.

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1443]
#### Describe your issue

After login to a remote solution, the user is logged in to all opened remote solutions with the same user.
If you log the user out from the solution which you haven't tried to log in, the user gets logged out from all opened solutions.

#### How can others reproduce the issue?

- start the web version
- open two remote solutions
- log in to one of them
- after a redirect, you should see that you both solutions are logged in 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
If the Solutions (ProcessEngines) have the same Authority this should happen in the Electron version as well. Can you confirm that? 

Otherwise we need to discuss if there is a Use Case of a user that wants to log in onto the same Authority with two different Accounts.

**Comment by rrrene** [comment]
@Vyperus Alex hat recht. Dass die Benutzer für zwei verschiedene PEs durch die gleiche Authority authentifiziert werden, ist ja ein Implementierungsdetail der Infrastruktur. Der Benutzer des Studios (egal, ob Web-Version oder Electron), sollte hiervon in keinster Weise etwas mitkriegen. :+1:

> Otherwise we need to discuss if there is a Use Case of a user that wants to log in onto the same Authority with two different Accounts.

Den gibt es definitiv (bspw. eine PE, an der ich aus Kontrollgründen als Admin eingeloggt sein muss und eine andere PE, an der ich als "ich" eingeloggt sein muss).

**Comment by rrrene** [comment]
> If the Solutions (ProcessEngines) have the same Authority this should happen in the Electron version as well. Can you confirm that?

Betrifft tatsächlich nur Webversion und wird daher hinten angestellt.

**Comment by SteffenKn** [comment]
Das Gleiche gilt für die Electron Variante auch, jedoch zeigt sich das ganze ein wenig anders.
Beispiel:

Ich verbinde PE A und PE B mit dem Studio, die beide den gleichen IdentityServer verwenden.
Ich melde mich für PE A an und das Modal zum Anmelden wird angezeigt. Wenn ich mich erfolgreich angemeldet habe verwendet das Studio für PE A den erhaltenen Access Token und für PE B weiterhin den dummy Token.
Jetzt versuche ich mich für PE B anzumelden. Das Modal erscheint ganz kurz und schliesst sich sofort wieder - das Anmelden ist automatisch passiert und ich bin nun mit dem gleichen Account bei PE A und PE B angemeldet.

Wenn ich mich von PE B nun abmelde bin ich laut Studio immer noch für PE A angemeldet und er nutzt weiterhin den Access Token den er am Anfang bekommen hab. Für PE B kann ich mich jetzt mit einem anderen Account anmelden.
Für den Identity Server bin ich jedoch für beide PEs abgemeldet, sobald ich mich einmal abmelde (dies wird nochmal deutlicher wenn man #1916 testet, da das erneuern des Tokens deswegen nicht mehr möglich ist).

**Comment by SteffenKn** [comment]
@rrrene 
Scheinbar ist es nicht vorgesehen dass man sich mit verschiedenen Accounts am IdentityServer anmelden kann: https://github.com/IdentityServer/IdentityServer4/issues/717
