### ISSUE TITLE
Copy and Paste Does Sometimes Break the Modeler

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1445]
#### Describe your issue

When editing [this Process](https://github.com/process-engine/bpmn-studio/files/2992837/alpha.bpmn.txt), `ctrl + c` and ` ctrl + s` on the UserTask breaks the modeller.

![clipboard](https://user-images.githubusercontent.com/38498731/54765386-b230e700-4bf9-11e9-8581-7cea026b9093.gif)

#### How can others reproduce the issue?

* Open the linked Process
* Copy the UserTask
* Try to paste it
* See that the modeler is now broken.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
You can reproduce this behavior by:

1. Create a diagram.
2. Create a UserTask.
3. Try to copy it.

I think this is problem with the handling of the form field, most likely a simple check that is missing.
