### ISSUE TITLE
💄Bad UX when stoppig process

### ISSUE THREAD

**Issue by demdh** [process-engine/bpmn-studio#1452]
When you stop a process, in the dashboard, via the Stop button, there is no feedback whatsoever. The corresponding entry simply disappears after a short time.
An indicator that the processing is running is missing here. A fadeout animation would also be useful. This would help if you stop process in a long list.

- BPMN-Studio Version: 5.1.2

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
Great suggestion 🙂 We will have no release this week, due to internal things, but this will probably be in for next week.

**Comment by KaiLuettmann** [comment]
A section with "processes executed in the past" would be interesting, too. This could be a entryoint to view the terminated processinstance in the view of the "Live-Execution Tracker".
This would help to discover why a processinstance is errorneous or see the executed paths in successful execution
