### ISSUE TITLE
LiveExecutionTracking shows a green REST task although a error occured

### ISSUE THREAD

**Issue by KaiLuettmann** [process-engine/bpmn-studio#1460]
#### Describe your issue

LiveExecutionTracking shows a green REST task although a error occured
![LiveExecutionTrackerTaskIsGreenOnError](https://user-images.githubusercontent.com/33122946/56722030-79c78000-6746-11e9-90a8-3738449049b5.png)
![LiveExecutionTrackerTaskIsGreenOnError_LogViewer](https://user-images.githubusercontent.com/33122946/56722042-7f24ca80-6746-11e9-96e6-7010cc74de12.png)

#### How can others reproduce the issue?

* Open BPMN File in [LiveExecutionTrackerTaskIsGreenOnError.zip](https://github.com/process-engine/bpmn-studio/files/3115979/LiveExecutionTrackerTaskIsGreenOnError.zip) with BPMN-Studio
* Deploy the process on localhost
* perform a custom start without any parameter

#### Possible solution

* Task is displayed red on error in "Live Execution Tracker"

#### What's your setup

- BPMN-Studio Version (`5.2.0`):
- OS (`Windows 10`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
:+1: Wir sollten diese Tasks im LET in "rot" kennzeichnen.
