### ISSUE TITLE
Erroneous TimerStartEvent: Processinstance is not stopable or deletable

### ISSUE THREAD

**Issue by KaiLuettmann** [process-engine/bpmn-studio#1461]
#### Describe your issue

A running processinstance with a errorneous TimerStartEvent the stop-button in the dashboard takes no effect

#### How can others reproduce the issue?

* open BPMN Process in [ErroneousTimerStartEvent_ProcessIsNotStopableOrDeletable.zip](https://github.com/process-engine/bpmn-studio/files/3116061/ErroneousTimerStartEvent_ProcessIsNotStopableOrDeletable.zip)
* deploy process to localhost
* take a custom start of the process without any parameter
* processinstance is running like: 
** ![ErroneousTimerStartEvent_ProcessIsNotStopableOrDeletable](https://user-images.githubusercontent.com/33122946/56723639-aaf57f80-6749-11e9-90b1-b591d5eebe5b.PNG)
** ![ErroneousTimerStartEvent_ProcessIsNotStopableOrDeletable_LogViewer](https://user-images.githubusercontent.com/33122946/56723694-c1034000-6749-11e9-8a90-0115ea8edfdc.PNG)
* in the dashboard the stop button does not terminate the processinstance see ![ErroneousTimerStartEvent_ProcessIsNotStopableOrDeletable_Dashboard](https://user-images.githubusercontent.com/33122946/56723759-ded0a500-6749-11e9-841b-3b3fe6577011.PNG)

#### Possible solution

While the process is not startet jet it couldn't be stopped. Another option is to delete the processinstance

#### What's your setup

- BPMN-Studio Version (`5.2`):
- OS (`Windows 10`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that I think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
@ElRaptorus Bitte verifizieren, ob dies ein Backend-Fehler ist.

**Comment by ElRaptorus** [comment]
@rrrene @KaiLuettmann Definitiv ein Problem mit der ProcessEngine.ts

Der Cyclic timer (welche wir aktuell noch nicht unterstützen), wird bei der FlowNode Validierung nicht erkann. Eigentlich sollte da ein Fehler geworfen werden, allerdings passiert das gerade nicht.

Werde ich untersuchen.

**Comment by ElRaptorus** [comment]
@KaiLuettmann This issue is fixed with #1465.

**Comment by KaiLuettmann** [comment]
thank you :-)
