### ISSUE TITLE
"Navigate to called process" deaktivieren, wenn Prozess nicht gewählt

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#1463]
Der Button "Navigate to called process" sollte deaktiviert und ausgegraut sein, wenn ich keinen Prozess gewählt habe.

![image](https://user-images.githubusercontent.com/311914/57617537-4fb4f100-7581-11e9-9105-eb355a508dea.png)

**Comment by ElRaptorus** [comment]
In BPMN Studio v5.4.0 ist das bereits implementiert.

![Bildschirmfoto 2019-06-07 um 11 39 17](https://user-images.githubusercontent.com/15343316/59095515-fbe7be80-8918-11e9-81d6-7cae4f5dadda.png)
![Bildschirmfoto 2019-06-07 um 11 39 24](https://user-images.githubusercontent.com/15343316/59095516-fc805500-8918-11e9-9c62-328dda664b70.png)
