### ISSUE TITLE
🐛 "Unsaved Changes" dialog is shown when clicking on Error Events

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1483]
## Description

Whenever you click on an `ErrorBoundaryEvent` or `ErrorEndEvent`, BPMN Studio will regard the BPMN file as modified. 

So when you try switching to a different diagram, you'll get the `Unsaved changes` dialog shown, even if you haven't changes anything.

I haven't noticed this effect on Signal- or Message Events. Timers also seem to be unaffected.

## Reproduction

(Updated 2019-06-03):
- Take [this diagram](https://github.com/process-engine/bpmn-studio/files/3241449/merge_feature_to_beta.bpmn.zip) and [this one](https://github.com/process-engine/bpmn-studio/files/3246326/merge_beta_to_develop.bpmn.zip)
- Open both in the studio
- Select any of the two
    - Clicking on `ErrorBoundaryEvents` or `ErrorEndEvents` will *not* cause this issue
- Switch to the second diagram
- Click on the `ErrorEndEvent` or `ErrorBoundaryEvent` (don't do anything else)
- The file will be marked as "edited"

**Comment by alexanderkasten** [comment]
Can't reproduce that with BPMN-Studio v5.3.0

**Comment by ElRaptorus** [comment]
@alexanderkasten I tried reproducing it again. At first I couldn't reproduce it either, but apparently, for this effect to occur, you'll have to switch to another diagram first.

So the correct reproduction steps would be:

- Take [this diagram](https://github.com/process-engine/bpmn-studio/files/3241449/merge_feature_to_beta.bpmn.zip) and [this one](https://github.com/process-engine/bpmn-studio/files/3246326/merge_beta_to_develop.bpmn.zip)
- Open both in the studio
- Select any of the two
    - Clicking on `ErrorBoundaryEvents` or `ErrorEndEvents` will *not* cause this issue
- Switch to the second diagram
- Click on the `ErrorEndEvent` or `ErrorBoundaryEvent` (don't do anything else)
- The file will be marked as "edited"

I'll update the reproduction steps in the issue description.

**Comment by SteffenKn** [comment]
Might be the same bug we had with the MessageEvents.
