### ISSUE TITLE
♻️ Prevent usage of cyclic timers on Boundary- and Intermediate events

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1493]
## Description

Using cyclic timers on `TimerBoundaryEvents` and `IntermediateCatchEvents` doesn't make any sense.
In fact, it is not even supported by the ProcessEngine.

## Reproduction

See Screenshots.

![Bildschirmfoto 2019-06-06 um 13 47 45](https://user-images.githubusercontent.com/15343316/59030594-af8d7780-8861-11e9-8c2c-9d6237424240.png)
![Bildschirmfoto 2019-06-06 um 13 36 07](https://user-images.githubusercontent.com/15343316/59030527-8b319b00-8861-11e9-91a0-bd1211e818fd.png)

## Possible solution

Cyclic timers (aka cronjobs) only make sense on `TimerStartEvents`.
Therefore, it should only be possible to configure cyclic timers on StartEvents.

*Note:*
Can't disable Cyclic TimerStartEvents entirely, because they are already supported by the .NET Engine.

**Comment by rrrene** [comment]
Für Boundary- und Catch-Events sollten wir die Option schlicht nicht anzeigen, weil sie keinen Sinn macht (hier **nicht** nur ausgrauen, sondern einfach nicht anzeigen, denn für die betreffenden Elemente kann die Option ja nie "eingegraut" werden).

Die Option bei TimerStartEvents zu verhindern ist problematisch, da bspw. das Team Hyperion diese Option bereits nutzen kann.

"Unsinnige Kombinationen" wie zyklische Catch-Events sollten wir verhindern, aber wir sollten nicht das Erstellen von validen BPMN-Konstrukten verhindern, nur weil die TS-Runtime sie (noch) nicht beherrscht. Hier wäre ein Hinweis besser.
