### ISSUE TITLE
🚸 Allow a user to assign aliases to a solution

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1513]
## Description

If I have multiple solutions that are located in a folder with the same name, it can sometimes be difficult to tell where these respective solutions are located, especially if their contents are similar.

Consider the following setup:

![Bildschirmfoto 2019-06-17 um 14 10 53](https://user-images.githubusercontent.com/15343316/59603442-bf327900-9109-11e9-9ebc-977ce3dc5e17.png)

Here I have three solutions that are located at three different locations. The first two even have identical content. 

I cannot tell instinctively where each of these solutions is located. I have to hover over the name and wait a couple of seconds until the tooltip appears, before I can see the full location.

## Possible solution

It would be helpful, if a user could assign a name (or alias) to a solution. 
This would also have the advantage that a user wouldn't have to rename the actual folder, which may not be desirable, if you are opening diagrams that are actively used by applications.

**Comment by rrrene** [comment]
Wie im Daily besprochen.
