### ISSUE TITLE
🐛 Process flies out of the window after start

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1515]
## Description

See attached clip

![bpmn-studio-start-bug](https://user-images.githubusercontent.com/15343316/59614146-6fab7780-9120-11e9-908d-750c6e17c959.gif)

ProcessModel used:

[token history.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/3297539/token.history.bpmn.zip)

**Comment by SteffenKn** [comment]
This seems to be an issue with the `zoom('fit-viewport', 'auto');`.
We should check that out.
