### ISSUE TITLE
🐛 The Empty Camunda Properties are Back

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1525]
## Description

Im creating a new Issue for this since the old one (https://github.com/process-engine/bpmn-studio/issues/531) is over a year old and will probably not be seen. 

As stated in the referenced issue, the studio kinda randomly generates empty camunda properties in the process model's xml. The generated xml tags looks like so: 

```
<camunda:properties />
```

**Issue Description from #531**:

Offenbar ist es durch die Modellierung im BPMN-Studio möglich, zahlreiche leere Extension Properties an beliebigen FlowNode-Typen zu produzieren.

Diese leeren Properties werden nicht im Property Panel angezeigt und der Benutzer kann somit nicht sehen, dass diese unnötigen Angaben im Diagramm existieren.

```
        <bpmn:serviceTask id="MyServiceTask" name="My Service Task">
            <bpmn:extensionElements>
                <camunda:executionListener class="" event="" />
                <camunda:properties />
                <camunda:properties />
                <camunda:properties>
                    <camunda:property name="module" value="MyService" />
                    <camunda:property name="method" value="myMethod" />
                    <camunda:property name="params" value="[&#39;1234&#39;]" />
                </camunda:properties>
            </bpmn:extensionElements>
            <bpmn:incoming>
                    SequenceFlow_03ab5x2
                </bpmn:incoming>
            <bpmn:outgoing>
                    SequenceFlow_144j7k7
                </bpmn:outgoing>
        </bpmn:serviceTask>
```

## Reproduction

As mentioned above, the properties are spawned kinda randomly.

**Comment by alexanderkasten** [comment]
@robpal94 Weißt du zufällig in welcher Version oder welchem Branch das auftritt?

**Comment by robpal94** [comment]
Ich benutze aktuell BPMN - Studio 5.4.0. Das mit den leeren Camunda Properties ist allerdings auch bei manchen Prs von @Vyperus aufgefallen.

**Comment by alexanderkasten** [comment]
@robpal94 Siehst du die leeren Properties erst wenn du das Diagramm gespeichert hast und Änderungen hattest, oder kannst du die leeren Properties schon nach dem Öffnen in der XML-View sehen?

**Comment by robpal94** [comment]
Also die Properties werden schon generiert, wenn man einfach nur ein Diagramm erstellt, eine (zum Beispiel?) External Task hinzufügt und ohne vorher zu speichern die XML - View öffnet.

**Comment by robpal94** [comment]
Das Problem wird evtl. mit dieser Zeile hier zu tun haben: https://github.com/process-engine/bpmn-studio/blob/develop/src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.ts#L81

Beim init der Service Task wird geprüft, ob es ein Property Element gibt. Falls nicht, wird ein leeres erzeugt (obwohl dies doch eigentlich schon nicht sein müsste, oder?).

Das Problem ist, dass wenn ein neues extension element ohne properties erzeugt wird, dies keine Values enthält (`values` ist also `undefined`). Die obige Methode welche prüft, ob die Service Task schon ein extension element erhält, liefert allerdings auch `undefined` zurück, wenn die ServiceTask ein Properties Element enthält, dies allerdings einfach nur über keine Werte verfügt.

**Comment by ElRaptorus** [comment]
@robpal94 Ich hab mal die Issue Beschreibung von 531 hier hin übernommen und das alte issue wieder geschlossen.
Wie du ja richtig fest gestellt hast, wird dieses Issue vermutlich eh nicht sonderlich sichtbar sein, daher ist es ausreichend, wenn dieses Issue hier besteht.
