### ISSUE TITLE
Cant Display a UserTask which Contains a preferredControl Property

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1539]
## Description

When trying to execute a User task with the `preferredControl: confirm` property value pair, the following error is thrown: 

```
dynamic-task-components.59nt2eu8.js:122 TypeError: Cannot read property 'label' of undefined
```

## Reproduction

* Add a new UserTask
* Add a Property with the key `preferredControl` and the value `confirm`
* Deploy and execute the Process
* Click on the active UserTask

**Comment by SteffenKn** [comment]
You have to add a form field of type `Truth Value` in order to use `prefferedControl: confirm`.

**Comment by robpal94** [comment]
Ah right, I forgot about that 😄 .
