### ISSUE TITLE
✨ Display list of a remote solution's active cronjobs

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1546]
## Description

Now that the ProcessEngine supports Cronjobs, it would be really cool, if we could provide an overview of the cronjobs that are currently running on the remote solutions.

## Possible solution

This could probably be a new section for the inspect view?

First, we need to add corresponding routes to the ProcessEngine though.

The internal CronjobService groups its crontabs by the ProcessModels to which they belong. I think the view should to the same.

**Comment by SteffenKn** [comment]
IMO we should add a table in the dashboard for this.
In the table there should be an entry for every cronjob, with the following properties:
`cronjob`, `processModelId`, `enabled`, `time until next start?`

Also we could add a icon to the solution explorer, if a deployed processModel has an enabled cronjob, for example:
<img width="156" src="https://user-images.githubusercontent.com/20394992/60717727-09499600-9f23-11e9-9a19-d3e1eae6faf0.png">

**Comment by ElRaptorus** [comment]
That sounds even better. 👍 

We should plan this in detail on monday.

**Comment by rrrene** [comment]
Hier offenbaren sich viele Verbesserungspotentiale im Bereich Usability. Bitte nur die Tabelle für's Dashboard umsetzen. :+1:

**Comment by ElRaptorus** [comment]
Mit dem PR hier gibts einen neuen Management API UseCase `getAllActiveCronjobs`, der alle gerade aktiven Cronjobs ausliest. 
Da stehen drin:
- processModelId
- startEventId
- crontab
- nextExecution

"Enabled" sind die alle, da die Liste exakt das reflektiert, was gerade im CronjobService läuft.
