### ISSUE TITLE
🐛 Process Lists Pagination Does Not Work Correctly

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1548]
## Description

The process list should be limited to 10 entries per page.
To do so only 10 correlations get displayed.
The problem is, that the process list displays every process instance of a correlation. For that reason, if a correlation contains 100 process instances the process list will get really long.

## Reproduction

- Run many processes with the same correlation id.

## Possible solution

Fix the filtering.

**Comment by ElRaptorus** [comment]
I opened an issue for this some time ago:

https://github.com/process-engine/bpmn-studio/issues/1436
