### ISSUE TITLE
🐛 Properties-Section Does Not Get Updated

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1553]
## Description

For example:

When selecting 'HTTP REST Service' in the service task section the properties section does not get updated.

This leads to some bugs:

- When adding properties the properties of the 'HTTP REST Service' get overwritten
- You can add multiple properties and the following error gets logged:
Uncaught TypeError: Cannot read property 'value' of undefined

## Reproduction

1. Bug:
![Bug](https://user-images.githubusercontent.com/20394992/60795954-e1e60980-a16c-11e9-914e-4da34a6efc41.gif)

2. Bug:
![Bug](https://user-images.githubusercontent.com/20394992/60796412-9aac4880-a16d-11e9-8946-38c44725c2aa.gif)

**Comment by alexanderkasten** [comment]
Das gilt nicht nur für einen ServiceTask. Die Properties section wird generell nicht aktualisiert wenn man nicht aktiv etwas daran verändert, nur beim erstmaligen selektieren eines Tasks.

Der zweite Bug entsteht dadurch das die XML schon drei Properties enthält sobald HTTP Rest Service ausgewählt wurde, diese allerdings noch nicht in der Properties section angezeigt werden. 

Sollte beides jetzt in #1534 gefixt sein.
