### ISSUE TITLE
✨ Open Diagrams: Änderungshistorie wird nicht beibehalten

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1554]
## Description

> Die "Rückgängig"-Funktionalität sollte sich dann auf den jeweiligen Prozess beschränken, so dass ich in jedem Prozess individuelle Schritte rückgängig machen kann (wie ich es auch bei Photoshop kann, wenn ich verschiedene Grafiken bearbeite).

Siehe https://github.com/process-engine/bpmn-studio/issues/373

**Comment by SteffenKn** [comment]
Scheinbar ist das von bpmn-js nicht vorgesehen:
https://forum.bpmn.io/t/how-to-conditionally-reset-the-command-stack/3685

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt, das Atlas Studio stellt allerdings "Undo" und "Redo" bereit.
