### ISSUE TITLE
If a process is started over the detail-view, it is started twice

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#156]
#### Describe your issue

If a process is started over the detail-view, it is started twice.

#### How can others reproduce the issue?

First start a process over the `Start`button of the detail-view.
Then navigate to the `Task List` and see that there are two tasks.

https://github.com/process-engine/bpmn-studio/blob/cf56a5d0b3a9dbd999c257e9c250aebe401ac5d9/src/modules/processdef-detail/processdef-detail.ts#L84-L87

shows, that the consumer client starts also the process.

#### Possible Solution

Check if, at this point, it is necessary to start it with the consumer client, since it will be refactored soon. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
I updated the Issue and offered a possible solution.
