### ISSUE TITLE
Display the Download Speed of an Update in MB/s

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1575]
## Description

When downloading a new Version of the Bpmn - Studio, the Download speed is always displayed in KB/s. However, the displayed download speed should be displayed in MB/s, if its higher than 999KB/s for a certain amount of time (just like in the most download managers). 

<img width="324" alt="Screenshot 2019-07-11 at 09 40 26" src="https://user-images.githubusercontent.com/38498731/61031639-3a611500-a3c0-11e9-90e8-c61c8630c462.png">

## Reproduction

* Update the BPMN - Studio using the internal updater
* See, that the download speed is always displayed in KB/s

## Possible solution

* Display the download speed in MB/s, if its higher than 999KB/s for a certain amount of time.

**Comment by rrrene** [comment]
@robpal94 Danke für deinen Vorschlag. 

Als kleines fokussiertes Team müssen wir verstärkt darauf achten, an Features und Verbesserungen zu arbeiten, welche ein "Wow"-Erlebnis beim Benutzer auslösen (oder Fehler beheben, die zu einem geschmälertem Erlebnis führen). 

Leider werden wir das vorgeschlagene Feature nicht umsetzen können, da das Verhältnis von Programmieraufwand zu "tangiblen Nutzen für den Endnutzer" bzw. "Wow"-Erlebnis mMn nicht gegeben ist. Tatsächlich wollte ich die Downloadgeschwindigkeit sogar entfernen, da sie für Nicht-Techniker keine hilfreiche Information darstellt.

Bitte fühl dich durch diese "Absage" nicht entmutigt, uns auch in Zukunft auf Verbesserungsmöglichkeiten des Studios hinzuweisen. :+1:
