### ISSUE TITLE
🐛 Canceling and Restarting of a Download is not Possible

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1576]
## Description

When canceling and retrying the download of a new bpmn - studio Release, the downloader seems to go crazy. 

## Reproduction

* Start to download a new Update of the BPMN - Studio
* Cancel the Download
* Try to start it again

**Comment by alexanderkasten** [comment]
![Jul-12-2019 11-20-24](https://user-images.githubusercontent.com/17065920/61117583-19b7be80-a497-11e9-8059-797c590d14fc.gif)

What do you mean with `seems to go crazy`?
I can not reproduce a cazy behaviour

**Comment by Paulomart** [comment]
This happend to me: 
![grafik](https://user-images.githubusercontent.com/4148404/61117813-ac585d80-a497-11e9-9f2f-4059e306f495.png)

**Comment by ElRaptorus** [comment]
Fixed by https://github.com/process-engine/bpmn-studio/pull/1578
