### ISSUE TITLE
🐛BPMN-Studio Doesn't Show Correct Called Process in Call Activity

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1588]
## Description

BPMN-Studio overwrites the called process in CallActivities when the process gets opened via "Opened Diagrams.

## Reproduction

Follow this step by step guide to reproduce the bug:

1. Create a diagram with more than one CallActivity (I don't know if this happens with one as well)
2. Save the diagram and close it.
3. Now open it again.
4. Open another diagram via the "Opened Diagrams" Tab in the Solution Explorer.
5. Open the first diagram (the one with the CallActivities) via the "Opened Diagrams"-Tab again.
6. See that it is a) edited and b) the called processes in the CallActivities are gone.

## My setup

- BPMN-Studio: v5.6.2
- OS: macOS

**Comment by Vyperus** [comment]
After further observation I can conclude that this behavior is rooted in the CallActivity Section of the Property Panel.

I was able to observe that the called Process is not overwritten but isn't displayed when the process is not inside the same solution. This counts for "Opened Diagrams" as well.

**Comment by SteffenKn** [comment]
The problem is that the selected process is not in the dropdown, because the dropdown only displays processes from the current solution.
