### ISSUE TITLE
📝  💄  Add docs and/or UI hints for payload of external tasks

### ISSUE THREAD

**Issue by FrankVonDerHoeh** [process-engine/bpmn-studio#1589]
## Description

The format required for the payload of external tasks should be documented. It is not immediately obvious that executable JavaScript code creating an object (e.g. { myFieldName = token.history.someTask.someFieldName}) must be used.

## Possible solution

* Add this to new documentation
* Add a hint in the UI (possibly using a generic mechanism for providing descriptions of properties in the UI)

**Comment by alexanderkasten** [comment]
Done by v5.13.0
