### ISSUE TITLE
Errors (return ExternalTaskBpmnError) from external tasks aren't handled correct

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/bpmn-studio#1593]
If you create a ExternalTaskBpmnError from a external task aren't handled unclear.

<img width="975" alt="Bildschirmfoto 2019-07-28 um 22 05 18" src="https://user-images.githubusercontent.com/169372/62012295-c6c35400-b184-11e9-8133-e120e1e0f67b.png">

<img width="1135" alt="Bildschirmfoto 2019-07-28 um 22 16 52" src="https://user-images.githubusercontent.com/169372/62012350-7698c180-b185-11e9-8256-f0e8aa9dbdbc.png">

BPMN siehe https://github.com/moellenbeck/papermill_with_external_task/blob/master/sample_papermill.bpmn

Code siehe https://github.com/process-engine/getting-started/blob/feature/handle_bpmn_error/DotNet/ExternalTask/Program.cs

**Comment by rrrene** [comment]
Vielleicht ist es noch zu früh, aber ich werde aus diesem Issue noch nicht ganz schlau.

Kannst du nochmal beschreiben, was du getan hast, was dann passiert ist und was du erwartet hättest?

**Comment by ElRaptorus** [comment]
> Vielleicht ist es noch zu früh, aber ich werde aus diesem Issue noch nicht ganz schlau.
> 
> Kannst du nochmal beschreiben, was du getan hast, was dann passiert ist und was du erwartet hättest?

Dito.

**Comment by Vyperus** [comment]
Hmm I think this is about that the External Task clearly ended with an error here. (See Log and onExit Token) Also the BoundaryEvent was executed. But this is not clearly visible because the LET doesn't "update" the path to the Error End Event.

I saw this some times now but wasn't able to reproduce this correctly. But it seems that "sometimes" the process ends and the LET just stops coloring the paths instead of checking and updating it one last time when the process ends.

**Comment by moellenbeck** [comment]
Was habe ich gemacht:

- Prozess erstellt (siehe oben) mit ExternalTask und einem ErrorBoundaryEvent
- Worker in C# (und Python) erstellt, der immer einen Fehler "ExternalTaskBpmnError" provoziert
- Prozess aus dem Studio gestartet
- Erwartet: BoundaryEvent behandelt den Fehler und der Prozess läuft zum "End with Error"-Event
- Passiert: BoundaryEvent "bekommt den Fehler?" und Prozess wird mit Error beendet?

so zumindest sieht es bei den Logs aus ;-(

@rrrene @ElRaptorus (@Vyperus)

**Comment by moellenbeck** [comment]
@rrrene @ElRaptorus reichen euch diese Infos?

**Comment by ElRaptorus** [comment]
> @rrrene @ElRaptorus reichen euch diese Infos?

Ich denke schon. 

@alexanderkasten @SteffenKn ?

**Comment by SteffenKn** [comment]
Ich habe das ganze mal nachgestellt und kam dabei zu diesem Bild:

<img width="660" src="https://user-images.githubusercontent.com/20394992/62200156-1ff9d600-b385-11e9-99e8-67d45a70895b.png">

Mir ist dabei auch aufgefallen:

Das Error End Event wird scheinbar nicht ausgeführt (besitzt keinen Token und es wird kein Log Eintrag dazu erstellt) und es wird kein Event vom Backend geworfen, dass der Process beendet ist.

**Comment by ElRaptorus** [comment]
> Das Error End Event wird scheinbar nicht ausgeführt (besitzt keinen Token und es wird kein Log Eintrag dazu erstellt) und es wird kein Event vom Backend geworfen, dass der Process beendet ist.

Interessant.
Ich werde mal versuchen zu verifizieren, ob das tatsächlich ein Bug in der PE ist.

**Comment by moellenbeck** [comment]
@ElRaptorus Gibt es hier schon eine Idee ob und wann es gelöst sein könnte? Danke //cc @rrrene

**Comment by ElRaptorus** [comment]
@moellenbeck Noch nicht. Wird das nächste sein, was ich mir anschaue.

**Comment by ElRaptorus** [comment]
@SteffenKn @rrrene @moellenbeck 
Ich habe das ganze mit v5.6.2 vom Studio nachgestellt und hab folgendes raus bekommen:

![Bildschirmfoto 2019-08-06 um 14 34 06](https://user-images.githubusercontent.com/15343316/62540195-576df400-b857-11e9-8c91-7153d07c1c34.png)

Ich hab dabei 2 Probleme erkannt:

1.:
 Nach erreichen des ErrorEndEvents wird der State der Prozessinstanz nicht aktualisiert. Diese behält weiter den "running" state, weshalb der Prozess weiter im Dashboard auftaucht.

Die FlowNodes der Prozessinstanz erhalten allerdings alle den jeweils korrekten state, d.h. da besteht ein Sync Problem zwischen den Tabellen `FlowNodeInstances` und `Correlations`.

2.:
> Das Error End Event wird scheinbar nicht ausgeführt (besitzt keinen Token und es wird kein Log Eintrag dazu erstellt) und es wird kein Event vom Backend geworfen, dass der Process beendet ist.

Ich glaub hier gabs ein Missverständnis. 
Ein `ErrorEndEvent` löst beim Eintreten einen Fehler aus. D.h. als Konsequenz, dass der Prozess nicht regulär beendet wird, sondern ein Fehler geworfen wird.
Dementsprechend muss hier nicht auf `onProcessEnded` gehört werden, sondern auf `onProcessError`.

Das EndEvent erhält auch einen `onExit` token. Dass der fehlen soll, konnte ich bei mir nicht reproduzieren.

**Comment by moellenbeck** [comment]
@ElRaptorus ich bekomme da irgendwie kein Ergebnis. Es ging nicht um den ErrorEnd-Event, sondern eher um das ErrorBoundaryEvent :-( - und der Prozess "hört immer auf". Vor allem ist es für mich nicht nachvollziehbar was da passiert. //cc @rrrene 

<img width="1098" alt="Bildschirmfoto 2019-08-06 um 14 58 08" src="https://user-images.githubusercontent.com/169372/62542496-2a701000-b85c-11e9-9691-bd5df154c271.png">
<img width="1124" alt="Bildschirmfoto 2019-08-06 um 15 08 21" src="https://user-images.githubusercontent.com/169372/62542498-2a701000-b85c-11e9-886d-6854f03fbb8b.png">
<img width="1129" alt="Bildschirmfoto 2019-08-06 um 15 08 52" src="https://user-images.githubusercontent.com/169372/62542499-2b08a680-b85c-11e9-86ad-4ac98ba769b0.png">

**Comment by moellenbeck** [comment]
und ich kann den Fehler definieren wie ich will `undefined` oder `"undefined"`, es gibt kein Matching.

**Comment by moellenbeck** [comment]
Studio ist auch 5.6.2

**Comment by ElRaptorus** [comment]
> und ich kann den Fehler definieren wie ich will `undefined` oder `"undefined"`, es gibt kein Matching.

Das hat 2 Gründe warum das nicht klappt:
1. Die Werte für Code sind **String** Werte. D.h. wenn du da als Wert `undefined` reinschreibst, dann ist das so, als würdest du erwarten, dass der abzufangene Fehler einen Code mit dem String-Wert `undefined` hat.
Wenn du ausdrücken willst, dass der Code nicht gegeben sein muss, dann lass das Feld einfach leer.
2. Der `Error Name` wird ebenfalls gematched. 
Heisst, wenn der geworfene Error einen anderen Namen hat, als der, der vom BoundaryEvent abgefangen werden soll (in diesem Fall `Error Name`, dann passiert natürlich nichts.
Da gilt das gleiche wie bei `Code`, wenn keine Name vorgegeben sein soll, dann lass das Feld einfach leer.


Wenn Code **und** Name am BoundaryEvent definiert sind, dann wird auch ein Matching für Code **und** Namen ausgeführt.

Versuch einfach mal ein ErrorBoundaryEvent mit leerem Namen und Code anzuhängen und schau was passiert.

Dass das BoundaryEvent eine State-Transition macht, obwohl es den Fehler nicht fangen kann, ist allerdings ein Bug.
Eigentlich sollte hier nach dem Fehler beim ExternalTask schluss sein.

**Comment by moellenbeck** [comment]
Krass - aber jetzt geht es. Müssen wir nur dringend erklären, oder? 

<img width="849" alt="Bildschirmfoto 2019-08-06 um 15 25 57" src="https://user-images.githubusercontent.com/169372/62543673-a703ee00-b85e-11e9-92cd-9e5f46f09504.png">
<img width="817" alt="Bildschirmfoto 2019-08-06 um 15 26 08" src="https://user-images.githubusercontent.com/169372/62543674-a703ee00-b85e-11e9-8fae-b4081e08cb6a.png">

**Comment by ElRaptorus** [comment]
> Krass - aber jetzt geht es. Müssen wir nur dringend erklären, oder?

Absolut.

**Comment by ElRaptorus** [comment]
Da das hier ja jetzt gelöst werden konnte, mach ich das Issue mal zu.
