### ISSUE TITLE
Studio sehr langsam

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#1594]
Ich habe ca. 150 wartende Prozessinstanzen (das ist meiner Einschätzung nach nicht "viel" - man stelle sich vor, die PE würde zum Managen von Anträgen bei der Stadt oder einer Personalverwaltung eingesetzt, mit Einspruchsfristen oder ähnlichen "delays" in den Prozessen, dann kommen dort schnell ein paar hundert oder auch tausend zusammen).

Das Studio ist, nachdem ich einmal auf "Inspect" war, unbenutzbar. Bitte die Tatsache beheben, dass wir bei 150 Prozessinstanzen immer 150 Requests zur REST-API machen.

- Warum holen wir die Informationen für jede Prozessinstanz einzeln? [N+1 Query-Problem](https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping)!
- Warum holen wir Informationen für alle Prozessinstanzen vom Server, wenn wir nur 10 anzeigen?
- Sollten wir nicht auch hier die Socket-Verbindung nutzen und das Polling nur als Fallback?

Das folgende, etwas lang geratene, Video illustriert die langen Wartezeiten:

![Kapture 2019-07-24 at 11 36 19](https://user-images.githubusercontent.com/311914/62021142-18d89980-b1c6-11e9-8a1a-12df13df165c.gif)

*Edit:* In der ersten Variante dieses Bug-Reports schrieb ich von 1.000 Prozessinstanzen, aber das Log in #1600 zeigt, dass es nur 147 sind. Ich habe den Text oben entsprechend angepasst.

**Comment by ElRaptorus** [comment]
> Warum holen wir die Informationen für jede Prozessinstanz einzeln? N+1 Query-Problem!

Die ProcessEngine stellt aktuell noch keine Schnittstelle a la "Hol mir alle aktiven Prozessinstanzen" bereit. 
Wäre eine gute Idee für einen weiteren UseCase.

> Warum holen wir Informationen für alle Prozessinstanzen vom Server, wenn wir nur 10 anzeigen?

Die ProcessEngine unterstützt derzeit weder Ranges, noch Pagination für ihre Requests. 
Leider hat man da aktuell keine andere Wahl, als das so zu machen. 

> Sollten wir nicht auch hier die Socket-Verbindung nutzen und das Polling nur als Fallback?

Ich bin mir gerade nicht sicher worauf sich der Punkt bezieht. 
Beim LET werden die Socket-Verbindungen bereits benutzt. Ich bin mir nicht sicher wo wir diese sonst noch effektiv einsetzen können, da hierüber ja lediglich Notifications verschickt werden (z.B. UserTask finished, ProcessInstance finished, etc).

**Comment by ElRaptorus** [comment]
Siehe:
https://github.com/process-engine/process_engine_runtime/issues/377
https://github.com/process-engine/process_engine_runtime/issues/379
https://github.com/process-engine/process_engine_runtime/issues/380

**Comment by rrrene** [comment]
> Ich bin mir gerade nicht sicher worauf sich der Punkt bezieht.
> Beim LET werden die Socket-Verbindungen bereits benutzt. Ich bin mir nicht sicher wo wir diese sonst noch effektiv einsetzen können, da hierüber ja lediglich Notifications verschickt werden (z.B. UserTask finished, ProcessInstance finished, etc).

Dann habe ich hier vermutlich etwas missverstanden: Ich habe gedacht, dass wir die Socket-Verbindung üperspektivisch auch zur Aktualisierung des Dashboards verwenden können/wollen, um Datensparsamkeit zu üben.

Wenn ich an einen Kunden denke, der drei Betriebsumgebungen mit eigenen PEs hat (`test`, `staging` und `prod`), dann hätte unser Teamleiter wahrscheinlich ich insgesamt vier PEs im Studio verbunden, die das Studio sekündlich per Polling updated. 

Ich hatte - vielleicht unbegründet - das Gefühl, dass wir auch dies auf Events basieren lassen wollen (und wenn es nur eine Lösung wäre, die eine Veränderung in den PEs per Socket wahrnimmt, bevor sie per REST den Roundtrip macht).

Wir sollten nochmal "brainstormen", wie wir das schlanker machen können :+1:

**Comment by ElRaptorus** [comment]
> Ich hatte - vielleicht unbegründet - das Gefühl, dass wir auch dies auf Events basieren lassen wollen (und wenn es nur eine Lösung wäre, die eine Veränderung in den PEs per Socket wahrnimmt, bevor sie per REST den Roundtrip macht).

Ich kann grad ehrlicherweise nicht sagen, ob das ursprünglich so vorgesehen war, aber ich finde, dass das eine gute Idee ist. 👍 

> Wir sollten nochmal "brainstormen", wie wir das schlanker machen können 👍

Ich schieß jetzt einfach mal ins Blaue und behaupte, dass es theoretisch nicht so schwierig sein sollte das Dashboard auf events umzubauen. 
Es gibt ja bereits Notifications für "ProcessInstanceStarted", "ProcessInstanceFinished", "ProcessInstanceTerminated" und "ProcessInstanceError". 
Man könnte das Dashboard so umbauen, dass es nur dann die Liste refreshed, wenn eine dieser Notifications empfangen wird. 

Oder was meint ihr @alexanderkasten @SteffenKn ?

**Comment by alexanderkasten** [comment]
> > Ich hatte - vielleicht unbegründet - das Gefühl, dass wir auch dies auf Events basieren lassen wollen (und wenn es nur eine Lösung wäre, die eine Veränderung in den PEs per Socket wahrnimmt, bevor sie per REST den Roundtrip macht).
> 
> Ich kann grad ehrlicherweise nicht sagen, ob das ursprünglich so vorgesehen war, aber ich finde, dass das eine gute Idee ist. 👍
> 
> > Wir sollten nochmal "brainstormen", wie wir das schlanker machen können 👍
> 
> Ich schieß jetzt einfach mal ins Blaue und behaupte, dass es theoretisch nicht so schwierig sein sollte das Dashboard auf events umzubauen.
> Es gibt ja bereits Notifications für "ProcessInstanceStarted", "ProcessInstanceFinished", "ProcessInstanceTerminated" und "ProcessInstanceError".
> Man könnte das Dashboard so umbauen, dass es nur dann die Liste refreshed, wenn eine dieser Notifications empfangen wird.
> 
> Oder was meint ihr @alexanderkasten @SteffenKn ?

Klar das würde gehen und würde wahrscheinlich schon ein bisschen helfen. Haben wir solche Events auch für Tasks und Cronjobs?

**Comment by ElRaptorus** [comment]
> Klar das würde gehen und würde wahrscheinlich schon ein bisschen helfen. Haben wir solche Events auch für Tasks und Cronjobs?

Tasks: Ja.

Cronjobs: Nein.

**Comment by alexanderkasten** [comment]
> > Klar das würde gehen und würde wahrscheinlich schon ein bisschen helfen. Haben wir solche Events auch für Tasks und Cronjobs?
> 
> Tasks: Ja.
> 
> Cronjobs: Nein.
Okay 👍 

Würde aber erst nach dem hier funktionieren https://github.com/process-engine/process_engine_runtime/issues/346.

**Comment by alexanderkasten** [comment]
> > Ich bin mir gerade nicht sicher worauf sich der Punkt bezieht.
> > Beim LET werden die Socket-Verbindungen bereits benutzt. Ich bin mir nicht sicher wo wir diese sonst noch effektiv einsetzen können, da hierüber ja lediglich Notifications verschickt werden (z.B. UserTask finished, ProcessInstance finished, etc).
> 
> Dann habe ich hier vermutlich etwas missverstanden: Ich habe gedacht, dass wir die Socket-Verbindung üperspektivisch auch zur Aktualisierung des Dashboards verwenden können/wollen, um Datensparsamkeit zu üben.
> 
> Wenn ich an einen Kunden denke, der drei Betriebsumgebungen mit eigenen PEs hat (`test`, `staging` und `prod`), dann hätte unser Teamleiter wahrscheinlich ich insgesamt vier PEs im Studio verbunden, die das Studio sekündlich per Polling updated.
> 
> Ich hatte - vielleicht unbegründet - das Gefühl, dass wir auch dies auf Events basieren lassen wollen (und wenn es nur eine Lösung wäre, die eine Veränderung in den PEs per Socket wahrnimmt, bevor sie per REST den Roundtrip macht).
> 
> Wir sollten nochmal "brainstormen", wie wir das schlanker machen können 👍

Der letzte Punkt von dir ist nun auf Develop und hat die Performance schon gut verbessert.
Wenn die oben von @ElRaptorus referenzierten Issues fertig sind kann man den Rest auch umbauen. Ich würde das Issue hier solange offen lassen.
