### ISSUE TITLE
Inkonsistentes Hightlighting der Haupt-Navigation

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#1596]
Im Video in #1594 sieht man auch, dass meine Hauptnavigation die Reiter "Design" und "Inspect" gleichzeitig markiert.

![image](https://user-images.githubusercontent.com/311914/62021419-6c97b280-b1c7-11e9-9cc9-38218229fb9c.png)

**WICHTIG**: Nach dem aktuellen Design muss man immer in **einem** der Reiter sein (man ist aber manchmal in keinem oder, wie im Screenshot, in zwei).

**Comment by alexanderkasten** [comment]
Hast du eine Step by Step Anleitung um das zu reproduzieren?

**Comment by rrrene** [comment]
Leider nicht. Mir ist aber aufgefallen, dass dieses Highlighting der Navigation sehr regelmäßig nicht funktioniert (häufig habe ich den Fall, dass keiner der drei Modi markiert ist).

**Comment by alexanderkasten** [comment]
Keiner der drei Modi sollten markiert sein wenn

- die `Start Page`,
- der `Live Execution Tracker`
- die gefilterte `Process List`
- die gefilterte `Task-list`

angezeigt wird.

Einer der drei Modi sollten markiert sein wenn

- die Think Ansicht (Liste aller Diagramme für eine Solution)
- die Design Ansicht (XML, Modeler, Diff)
- die Inspect Ansicht (Dashboard, Inspect-Correlation, Heatmap)

angezeigt wird.

Zwei Navbar Elemente sollten niemals angezeigt werden und das bekomme ich auch leider nicht hin.

**Comment by rrrene** [comment]
Ich will gar nicht sagen, dass das "technisch" falsch ist, aber als unbedarfter Benutzer verstehe ich nicht, warum ich nicht immer in einer der drei Modi bin. Bei `Start Page` kann ich eventuell noch irgendwie verstehen.

Aber warum ich nach Klick auf `Live Execution Tracker` nicht mehr in "Inspect" bin, obwohl ich doch grade etwas "inspiziere", verstehe ich dann nicht.

Ich denke aber, dass diese Fundamentalkritik auf die größere Diskussion hinaus läuft, ob "Think", "Design", "Inspect" zwar sehr gute Marketingbegriffe, aber schlechte UI-Metaphern sind. Und "Modale Editoren" sind nicht ohne Grund auch unter Entwicklern umstritten (siehe vi vs emacs).

Ich würde vorschlagen: Wir behalten dieses Issue als Erinnerung an den "Zwei sind gleichzeitig markiert"-Bug.

**Comment by alexanderkasten** [comment]
@SteffenKn @rrrene @ElRaptorus Konnte von euch noch jemand den "Zwei sind gleichzeitig markiert"-Bug reproduzieren?
