### ISSUE TITLE
Fehlermeldung „Could not colorize XML“ nach Deployment auf interne PE

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#1598]
Im Video in #1594 sieht man nach dem Deployment auf die interne PE eine Fehlermeldung

```
Could not colorize XML
```

Guckt mal bitte, was es damit auf sich hat.

**Comment by alexanderkasten** [comment]
Könntest du uns deine DB zur Verfügung stellen, auf die du das Diagramm deployst?
Ich konnte das Verhalten bis jetzt nicht reproduzieren, auch mit dem selben Diagramm nicht.

**Comment by SteffenKn** [comment]
Bei mir passiert das nur bei manchen Diagrammen, aber bei denen dann auch konsistent.
