### ISSUE TITLE
Fehlermeldungen bei Beenden des Studios

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#1599]
Ich bekomme immer häufiger mehrere Fehlermeldungen hintereinander bei Beenden des Studios. Die folgenden Meldungen sind nicht aus verschiedenen Vorfällen sondern kommen alle hintereinander:

![image](https://user-images.githubusercontent.com/311914/62021643-8ede0000-b1c8-11e9-8df9-12ab613f93ae.png)
![image](https://user-images.githubusercontent.com/311914/62021645-91405a00-b1c8-11e9-878e-f43655703106.png)
![image](https://user-images.githubusercontent.com/311914/62021647-92718700-b1c8-11e9-8861-06e0dfd12376.png)

**Comment by alexanderkasten** [comment]
Vielleicht hängen diese Exceptions auch mit dem Issue zusammen: #1574 , https://github.com/process-engine/process_engine_runtime/issues/374

**Comment by ElRaptorus** [comment]
> Vielleicht hängen diese Exceptions auch mit dem Issue zusammen: #1574 , [process-engine/process_engine_runtime#374](https://github.com/process-engine/process_engine_runtime/issues/374)

Jein. 
Ich denke was hier passiert ist, dass hier beim Beenden des BPMN Studios die FileHandles der ProcessEngine, die gerade noch aktive Metriken und/oder Logs schreiben, forciert beendet werden. 
Wenn die dann gerade noch dabei sind eine Operation auszuführen, dann scheint das zu einem Fehler zu führen. 
Das war vermutlich schon immer so und tritt jetzt nur häufiger in Erscheinung, seit wir mit den Cronjobs regelmäßig neue Prozessinstanzen generieren können. 
Je mehr Prozessinstanzen laufen, desto größer ist die Wahrscheinlichkeit, dass so ein FileHandleError auftritt. 

`ECANCELED` deutet da sehr stark drauf hin.

**Comment by ElRaptorus** [comment]
See: https://github.com/process-engine/process_engine_runtime/issues/378

**Comment by ElRaptorus** [comment]
@rrrene @alexanderkasten @SteffenKn 
Bekommt noch jemand diese Fehler?
Ich hab das nun länger nicht mehr beobachten können.

**Comment by alexanderkasten** [comment]
Ich hab es auch schon länger nicht mehr gesehen @ElRaptorus

**Comment by alexanderkasten** [comment]
Wenns noch mal auftaucht dann bitte wieder eröffnen.
