### ISSUE TITLE
✨ Baukastensystem für Expressions & Activity Payloads

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1601]
## Description

Aktuell werden Payloads und Expressions jeder Art (z.B. Conditions an ExclusiveGateway-Flows oder ExternalTask payloads) über JSON Objekte, bzw. JS Snippets erstellt. 

Das ist nicht nur immens fehleranfällig, da sich schnell mal Typos oder Syntaxfehler einschleichen können, sondern es erschwert auch Nutzern den Zugang zum System, die vllt. nicht so technikaffin sind - man *muss* wissen, wie man ein korrektes JSON schreibt, um diese Features nutzen zu können. 
Auch sind Expressions wie `token.history.FlowNodeXYZ.someValue` wenig intuitiv für User, die nicht bereits wissen, was es damit auf sich hat.

## Possible Solution

Würden wir eine Art Baukastensystem bereit stellen, mit der sich Benutzer z.B. einen ServiceTask Payload zusammen"bauen" können, würden wir viele dieser Probleme lösen. 

Etwas vergleichbares wird bereits für das Konfigurieren von UserTask FormFields verwendet.
So ein System könnte man denke ich auch für andere Komponenten verwenden, die mit JSON expressions arbeiten. 

In der ersten Ausbaustufe könnte dieser Baukasten einfache Felder bereit stellen (number, bool, string, etc.).
Ein zusätzliches Feld "FlowNode" könnte es Benutzern erlauben die ID einer FlowNode einzutragen, deren finalen Wert man verwenden will. 

D.h. man würde keine Token Expression a la `token.history.FlowNode1.abc` mehr in JSON Form eintragen müssen, sondern könnte über den Baukasten den Feldtyp "FlowNode" auswählen und als Value dann die ID der FlowNode eintragen (optional dann vllt. noch konkrete Feldnamen aus dem token). 

Das Studio kann dann hinterher beim Speichern das tatsächliche JSON erstellen. 

In späteren Ausbaustufen könnte man dann noch darüber nachdenken vllt. verschachtelte Objekte anlegen zu können.

Oder man könnte vllt. so eine Art "Backtracking" entwickeln, welches es Nutzern ermöglicht aus einer Liste vorheriger FlowNodes direkt auszuwählen. Damit könnte man vermeiden, dass Nutzer ungültige FlowNodeIds angeben.
 
Gibt sicherlich auch noch mehr Möglichkeiten...

Meinungen?

**Comment by moellenbeck** [comment]
Ich finde die Idee gut. @rrrene und ich haben über etwas "was man als Nachfolger der Developer Days" bezeichnen kann nachgedacht und ggf. wäre die Idee ein möglicher Inhalt für dies neue Format.

**Comment by rrrene** [comment]
@ElRaptorus @moellenbeck Das ist :+1:

Wieder so ein cooles, exploratives Thema, wo wir ruhig die ganze Mannschaft einladen sollten und dann gucken, was Teams aus zwei, drei Leuten an interessanten Prototypen bauen.

Müssen mal mit den Terminen gucken. Lasst uns mal einen Hackathon-Kalender machen, weil das werden langsam echt viele (und wir haben ja im Rahmen der OKR-Planung gelernt, wo der Unterschied zwischen "ambitioniert" und "zu viel" ist 😆)
