### ISSUE TITLE
"Open Diagrams" are not sorted by name

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#1607]
# Description

The "Open Diagrams" are not sorted by name, instead they are sorted by opening time.

See attached screenshot:

<img width="248" alt="grafik" src="https://user-images.githubusercontent.com/4148404/62190759-6bef4f80-b372-11e9-98e9-1409f7f587b2.png">

## Reproduction

1. Open some diagrams in random order
2. See that they are not sorted by name

## Possible solution

Sort diagrams by name. **Like all other diagram lists**

## My setup

<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/4148404/62190865-a822b000-b372-11e9-84c2-eced461ada83.png">

**Comment by SteffenKn** [comment]
This is the way it's supposed to work.

**Comment by ElRaptorus** [comment]
Ist doch bei VSCode genauso.
Wenn du mehrere Tabs nacheinander aufmachst, dann sind die auch nicht nach Namen sortiert, sondern nach der Reihenfolge in welcher sie geöffnet wurden (was effektiv ja der Öffnungszeitpunkt ist).

Man könnte vllt. als zukünftiges Feature dem User erlauben die Diagramme selbst zu ordnen (wie die tabs in VSCode), aber @SteffenKn hat recht damit, dass das Ganze derzeit so funktioniert wie beabsichtigt.

**Comment by Paulomart** [comment]
Okay then.

**Comment by rrrene** [comment]
@Paulomart @SteffenKn @ElRaptorus Wir setzen das um, sobald wir "richtige" Tabs implementieren. Für den jetzigen Zeitpunkt ist die aktuelle Umsetzung genau richtig, unser "Skateboard" auf dem Weg zu Tabs :+1:
