### ISSUE TITLE
✨Add XML View of Process Definition into Detail View

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#161]
#### Describe your issue

It would be nice to have a XML viewer like the camunda modeler.

#### Possible Solution

Add a button in the upper toolbar above the diagram itself. Then create a new module and load it into the view when the button ist clicked.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
I updated the Issue and offered a possible solution.
