### ISSUE TITLE
🐛npm package is not installable 

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1612]
## Description

The bpmn-studio npm package is not installable.

```
> npm rebuild && electron-builder install-app-deps

sh: electron-builder: command not found
npm WARN sequelize-typescript@1.0.0-beta.3 requires a peer of @types/bluebird@* but none is installed. You must install peer dependencies yourself.
npm WARN sequelize-typescript@1.0.0-beta.3 requires a peer of @types/validator@* but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bpmn-studio@5.6.2 postinstall: `npm rebuild && electron-builder install-app-deps`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bpmn-studio@5.6.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
## Reproduction

`npm i -g bpmn-studio`

**Comment by rrrene** [comment]
@alexanderkasten mMn sieht das so aus, als wäre das seit einem Jahr kaputt: 2bf411f (denn `electron-builder` ist eine `devDependency`)

Kann das denn sein? 😳

**Comment by alexanderkasten** [comment]
> @alexanderkasten mMn sieht das so aus, als wäre das seit einem Jahr kaputt: [2bf411f](https://github.com/process-engine/bpmn-studio/commit/2bf411f3ac5e65784cd10f442f8f50251bcab48d) (denn `electron-builder` ist eine `devDependency`)
> 
> Kann das denn sein? 😳

Ich denke schon. Die Web Version des Studios (npm package) wird wahrscheinlich von niemanden benutzt und falls doch, dann nicht über npm installiert. 
Das ist mir letztens aufgefallen als ich das Studio auf einem Server installieren wollte ohne das Repository zu clonen.
