### ISSUE TITLE
🐛No Error Message When Connection to PE Fails

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1651]
## Description

If you enter a faulty address while connecting to a ProcessEngine instance you get no error message indicating that something went wrong.

## Reproduction

![Aug-13-2019 10-39-43](https://user-images.githubusercontent.com/17248802/62927410-c4810c80-bdb6-11e9-9ee0-2d8d49062f6b.gif)

## Possible solution

Add an error message.

## My setup

- BPMN-Studio: 5.7.0-beta.1

**Comment by SteffenKn** [comment]
There is an error message if the connection to the PE fails.
The problem is that in this case the request takes an extremely long time.
We should probably display a notification if there was no response after a few seconds.

**Comment by rrrene** [comment]
@SteffenKn Wir können nicht das Dialogfeld ausblenden und dann passiert nichts in der UI.

> The problem is that in this case the request takes an extremely long time.

Die Schwelle sind 100ms. Alles über 100ms Reaktionszeit ist inakzeptabel. Wenn ich nach 100ms keine sinnvolle, antizipierbare Rückmeldung von der App kriege, fühlt sich das erst falsch an und bei > 1s denke ich, die App ist kaputt.

Das heisst nicht, dass nach 100ms die PE connected sein muss. Sondern nach 100ms muss Studio mir sagen, was es tut (oder schon fertig sein).

> We should probably display a notification

Eine Notification sollte eine Ausnahme sein. Bei dem "Ach, ich zeig halt ne Notification an"-Vorgehen vertippt sich der User mich, kriegt nach 3 Sekunden eine Notification, in der er die Adresse, bei der er sich evtl. vertippt habe, nicht einmal sieht.

Die Interaktion "Eine PE connecten" muss in dem dafür vorgesehenen Dialogfeld stattfinden. Es sollte sich erst schließen, wenn die PE erfolgreich connected ist oder ich auf "Abbrechen" drücke.

Vorgehen:

```
Klick auf Button 
-> irgendeine Art von Indikator, dass die PE geladen wird 
-> entweder aussagekräftige Fehlermeldung (Schlechtfall) 
    oder Dialogfeld verschwindet, sobald Connect erfolgreich (Gutfall)
```

**Comment by SteffenKn** [comment]
> Eine Notification sollte eine Ausnahme sein. Bei dem "Ach, ich zeig halt ne Notification an"-Vorgehen vertippt sich der User mich, kriegt nach 3 Sekunden eine Notification, in der er die Adresse, bei der er sich evtl. vertippt habe, nicht einmal sieht.

Die Adresse steht in der Notification.
Soll die Notification auch weiterhin angezeigt werden wie aktuell oder soll die Nachricht auch im Modal angezeigt werden?
 
> Die Interaktion "Eine PE connecten" muss in dem dafür vorgesehenen Dialogfeld stattfinden. Es sollte sich erst schließen, wenn die PE erfolgreich connected ist oder ich auf "Abbrechen" drücke.

Was soll denn passieren wenn während sich das Studio versucht mit der PE zu verbinden der User auf Abbrechen klickt?
Soll dann das Verbinden abgebrochen werden, das Verbinden im Hintergrund geschehen oder soll das gar nicht möglich sein?


> Vorgehen:
> 
> ```
> Klick auf Button 
> -> irgendeine Art von Indikator, dass die PE geladen wird 
> -> entweder aussagekräftige Fehlermeldung (Schlechtfall) 
>     oder Dialogfeld verschwindet, sobald Connect erfolgreich (Gutfall)
> ```

👍

**Comment by rrrene** [comment]
> Soll die Notification auch weiterhin angezeigt werden wie aktuell oder soll die Nachricht auch im Modal angezeigt werden?

Jein. Eine Notification sollte immer dann angezeigt werden, wenn es keine andere kontextuelle Möglichkeit zur User-Ansprache gibt.

Also im Modal anzeigen. Außer, wenn eine PE beim Neustart wiederhergestellt wird und nicht re-connected werden kann. Dann ist eine Notification die einzig sinnvolle Möglichkeit.

Beispiele: 

- Ich drücke in VS Code die Tastenkombination für "Code formatieren", habe aber keinen Formatter hinterlegt. 
- Ich starte VS Code und ein Plugin stürzt beim Start ab.

In beiden Fällen kommt eine Notification in VS Code, weil das Programm keinen anderen Kontext hat, mir seine Not mitzuteilen.

Gegenbeispiel: 

Wenn ich einen String in VS Code suche, der in meinem Projekt nicht existiert, bekomme ich keine Notification, sondern innerhalb des "Suche"-Komponente eine entsprechende Meldung:

![image](https://user-images.githubusercontent.com/311914/63031464-4440d100-beb4-11e9-89c8-61e32a167ebe.png)

Ich erhalte diese Information aber in dem Kontext, in den ich meine Aufmerksamkeit richte.
