### ISSUE TITLE
🐛BPMN-Studio Scans Ports and does not Handle Errors

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1652]
## Description

We noticed that BPMN-Studio throws a bunch of errors, while checking ports on localhost.

<img width="544" alt="Bildschirmfoto 2019-08-13 um 10 42 22" src="https://user-images.githubusercontent.com/17248802/62927710-656fc780-bdb7-11e9-8e88-80f4959e8aca.png">

## Reproduction

- Open BPMN-Studio
- Open Dev Tools
- Open Console

## My setup

- BPMN-Studio: 5.7.0-beta.1

**Comment by SteffenKn** [comment]
@Vyperus 
Unfortunately these errors are emitted by chrome and it seems that they cannot be silenced.

However, you can hide network messages via the developer console settings
- Click on the gear in the upper right corner of your developer console
![icon](https://user-images.githubusercontent.com/20394992/62929275-73731780-bdba-11e9-863a-e39d19d0c037.jpeg)
- Click on 'Hide network'
![hide network](https://user-images.githubusercontent.com/20394992/62929309-84bc2400-bdba-11e9-94ca-81de2aad15aa.jpeg)
- The errors are now hidden
<img width="556" alt="Bildschirmfoto 2019-08-13 um 11 06 25" src="https://user-images.githubusercontent.com/20394992/62929334-91d91300-bdba-11e9-94af-6b59cae329e9.png">

You may also have a look at:
https://stackoverflow.com/questions/43012334/silence-neterr-connection-refused
