### ISSUE TITLE
🐛Comparing Diagrams Does Not Always Work Correctly

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1670]
## Description

For example:
If you switch between different Open Diagrams without changing something, sometimes it gets marked as an unsaved diagram.
Also the diff view will display changes or even says the diagrams are incomparable even though the diagrams look the same.

## Reproduction

 Open several diagrams and follow the gif below
![Aug-21-2019 09-29-56](https://user-images.githubusercontent.com/17065920/63411855-ba828d80-c3f6-11e9-8093-32f678446002.gif)

## My setup

- develop 151337bdbe161e2e2cbc4ca39eeda3cab1de70bd
Release v5.7.0-alpha.33

**Comment by SteffenKn** [comment]
I can't reproduce this in any way.
Are you sure that the diagrams had no state and were not changed by another Studio version?

**Comment by alexanderkasten** [comment]
yes

**Comment by SteffenKn** [comment]
After doing some research,  we found out that this problem occurs when opening an old diagram, because the modeler changes the xml during import.
