### ISSUE TITLE
BPMN-Studio (Beta) verwendet eine Alpha-Version der ProcessEngine

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/bpmn-studio#1692]
Die Beta-Version des BPMN-Studio verwendet eine Alpha-Version der ProcessEngine ... würde ich so nicht erwartet haben.

<img width="894" alt="screenshot_23" src="https://user-images.githubusercontent.com/169372/63608353-0854ec80-c5d5-11e9-8e1f-96cbe69e4a18.png">

**Comment by rrrene** [comment]
Im Grundsatz gebe ich dir Recht. 

Wir haben das im Team damals besprochen und entschieden, dass eine Harmonisierung der Release-Kanäle über alle Dependencies hinweg für die Alpha/Beta-Versionen nicht dogmatisch *zwingend* ist. Im Falle der Runtime ist das natürlich augenfällig und im Rahmen des zweiwöchigen Feature-Freezes sollte auch die Runtime ab nächster Woche eine Beta haben (die aber natürlich inhaltlich der `alpha.5` entspricht, es geht hier nur um Namen, nicht um Inhalte). 

Die Regel ist: `stable`-Pakete dürfen nur `stable`-Pakete referenzieren (wichtig!), `alpha`- und `beta`-Pakete müssen fixe Versionen referenzieren (keine dist-tags), so dass jeder Stand der Software im Zeitablauf reproduzierbar ist.

Würden wir jedoch über alle 67 Pakete hinweg dauerhaft eine Regel berücksichtigen wollen, dass alle `beta`-Pakete nur `beta`-Pakete und alle `alpha`-Pakete nur `alpha`-Pakete referenzieren dürfen, wäre das machbar, aber wir beim Release-Aufwand etwa wieder dort, wo wir gestartet haben.

**Comment by moellenbeck** [comment]
Ich denke nicht, dass wir alle Pakete auf die "gleiche" Version bringen müssen. Mir ist es nur aufgefallen, da ich für Python an einem "neuen" ProcessEngineClient arbeite und `/` für mich die "Echo"- bzw. -Route ist. Nach der ersten Ausgabe war ich dann deutlich unsicher, ob ich die richtige ProcessEngine-Version verwende. Wenn es mit vertretbarem Aufwand geht, sollte die "Embedded-PE" sagen: "Ja ich bin die richtige PE". Nicht mehr und sicher auch nicht weniger.

**Comment by rrrene** [comment]
Wir werden in Zukunft mehr Rücksicht darauf nehmen.
