### ISSUE TITLE
Laufzeitinformationen in der Heatmap 

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1716]
## Description

Aktuell sieht man in der Heatmap nur ob ein Task in der erwarteten Zeit erfolgreich abgearbeitet wurde oder nicht.
Es wäre schön zu sehen, wie lange der Task genau gebraucht hat.

## Possible solution

1. Man könnte vielleicht einen Viewer einbauen der je nach klick auf ein Element die Informationen anzeigt, ähnlich wie der TokenViewer.

2. Tooltips 

3. Infotext unterhalb des Diagramms der sich je nach selektiertem Element aktualisiert und die Informationen darstellt.

**Comment by ElRaptorus** [comment]
> Man könnte vielleicht einen Viewer einbauen der je nach klick auf ein Element die Informationen anzeigt, ähnlich wie der TokenViewer.

Die Lösung find ich am besten. An einer Runtime Info hängen ja auch noch weitere Infos, wie z.B. Median, Max. Laufzeit, Min. Laufzeit, Durchschnittliche Laufzeit, etc. 
Das könnte man über so ein Seitenpanel denke ich am besten darstellen.

> Infotext unterhalb des Diagramms...

So einen Text könnte man auch verwenden. In diesem würde ich dann die Laufzeitinfo für das Prozessmodell, bzw. die Prozessinstanz darstellen.
Aus den Metriken könnte man diese auch bereits generieren, da die Infos auch in den Logs bereits erfasst werden.
Da müssten nur ggf. neue Endpunkte für die Management API her. Glaub die bisherigen reichen da nicht aus um das auf effektive Art zu berechnen.

**Comment by rrrene** [comment]
Dem grundsätzlichen Sentiment, dass die Heatmap noch viel Potential hat, stimme ich zu. Der erste praktische Schritt zur Vorbereitung ist die Anpassung der Log-Formate (siehe Backlog in factro).

Das Thema wird dann im Rahmen eines unserer OKRs ("Hackathon") behandelt, dafür müssen wir noch einen Termin machen. Da können wir diese Ansicht dann ganz mutig neu "denken". :+1:

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt, mit dem neuen Atlas Engine + Atlas Studio Setup lassen sich allerdings entsprechende Extensions realisieren.
