### ISSUE TITLE
✨ "Deploy Solution" Feature

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1717]
## Description

Aktuell kann man Prozessmodelle immer nur einzeln deployen.
Das kann u.U. zeitintensiv werden, wenn man große Mengen an BPMNs deployen will.

Ein "Deploy Solution" Feature könnte dem Abhilfe schaffen.

## Possible solution

Zu allererst muss die Runtime die nötigen Endpunkte bereit stellen:
https://github.com/process-engine/process_engine_runtime/issues/395

Wenn das erledigt ist, dann könnte man dieses Feature im Studio z.B. in Form eines neuen Icons im Solution Explorer umsetzen (neben den bisherigen `Create new Diagram` und `Close this solution` Optionen).

**Comment by rrrene** [comment]
Ich finde das einen guten Vorschlag, da wir so auch dahinkommen, "Solutions" mehr als ganzheitliche Einheiten der Entwicklung, des Testens (Prozessmodelle testen wird ja auch noch ein Thema) und des Deployments zu sehen :+1:

P.S.: @ElRaptorus wann kriege ich meinen Step-Debugger für Prozesse? 😝

**Comment by ElRaptorus** [comment]
> P.S.: @ElRaptorus wann kriege ich meinen Step-Debugger für Prozesse? 😝

Wenn du genug Treuepunkte gesammelt hast. 😜

**Comment by ElRaptorus** [comment]
Update:
Das Feature kommt für die AtlasEngine, aber nicht mehr für die ProcessEngine.
