### ISSUE TITLE
🐛BPMN-Studio requests `test_resource` as API Resource

### ISSUE THREAD

**Issue by DevBastiS** [process-engine/bpmn-studio#1747]
## Description

Currently BPMN-Studio requests an API Resources when connecting with an IdentityServer.
This is hardcoded I think.
The requested API Resource is called "test_resource".

Since I am not sure about the reasoning I would like to ask to either remove this or make it configureable or if this is necessary give it a better name.

## Reproduction

Log In via an IdentityServer and check the logs (in the IdentityServer) for the requests made.

## Possible solution

Discuss the reasoning behind this resource and come up with a plan for it.
Maybe we can discuss this together?

**Comment by rrrene** [comment]
Wie hoch ist denn die "Severity" dieses Issues für dich? Der Spam im Log ist sicherlich ein Grund, sich das anzugucken. 

Habt ihr durch diesen Effekt auch funktionale Einschränkungen?
