### ISSUE TITLE
🐛 BPMN Studio Only Works When "Internal" Process Engine Is Running

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1752]
## Description

When the "internal" process engine (default: `http://localhost:8000`) of the BPMN Studio is not running the Studio does not work.

That means that the web version only works when a process engine is running on the url configured via `processEngineRoute` in `aurelia_project/environemnt/dev.ts`.

## Reproduction

- Make sure no process engine is running on `http://localhost:8000`
- Run the web version of the BPMN Studio
- Try to connect another process engine
- **Notice that the Studio is unable to connect to another process engine**

**Comment by alexanderkasten** [comment]
Same for the Electron Version
