### ISSUE TITLE
🐛 Export as BPMN breaks umlauts

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#1755]
## Description

Exporting a diagram will result in a diagram with broken umlauts.

## Reproduction

1. Open a remote engine with a deployed process containing strings with umlauts

1. export the diagram as BPMN

   ![image](https://user-images.githubusercontent.com/4034128/65416338-e29b4d00-ddf7-11e9-9370-3bc06d7eb62b.png)

1. Open the exported diagram in a solution

   ![image](https://user-images.githubusercontent.com/4034128/65416277-cc8d8c80-ddf7-11e9-9c6d-694cd901da45.png)

1. see the broken umlauts; this is the exported process I used

   [Bier_brauen_defekt.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/3641566/Bier_brauen_defekt.bpmn.zip)

## My setup

BPMN Studio 5.6.2

**Comment by rrrene** [comment]
@cmg-dev Du hast vollkommen recht. Die Funktion nutzt eine andere Routine als die "Speichern unter ..."-Funktion und während das `encoding` stimmt, ist das `fileencoding` falsch (`latin1`).

@alexanderkasten bitte bei Gelegenheit die Möglichkeit für den BPMN-**Export** komplett entfernen ("Speichern unter ..." deckt heute den gleichen Use Case ab und ist weniger fehleranfällig).

**Comment by alexanderkasten** [comment]
@rrrene Soll der BPMN-Export in der Webversion bleiben? Da gibt es nämlich kein `Speichern unter...`.

**Comment by rrrene** [comment]
@alexanderkasten Nein. Das ist ein getrenntes Problem, dass wir das Menü nicht in der Webversion haben. :wink:

**Comment by alexanderkasten** [comment]
@rrrene Wenn ich den BPMN Export entferne haben wir keine Möglichkeit mehr von remote Solutions ein BPMN File zu bekommen. Das Speichern unter funktioniert aktuell nur auf dem Filesystem

**Comment by alexanderkasten** [comment]
Das npm Paket `downloadjs` scheint das Problem zu sein und kein utf8 zu supporten.

**Comment by rrrene** [comment]
Evtl. `downloadjs` patchen: https://github.com/rndme/download/blob/master/download.js

**Comment by cmg-dev** [comment]
Das würde mit aktuell tatsächlich etwas helfen :)
