### ISSUE TITLE
🐛Opening a remote solution is not sensitive for url prefix

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#1756]
## Description

Opening a remote solution is not sensitive for url prefix.

This is problematic, for writing instructions etc. 

## Reproduction

1. Open the *Open Remote Solution* dialog
1. Enter something like `http://demo.de`
1. See the result:

   ![image](https://user-images.githubusercontent.com/4034128/65416773-dfed2780-ddf8-11e9-8ef1-0b2396834331.png)

## My setup

BPMN Studio 5.6.2

**Comment by rrrene** [comment]
@cmg-dev Kannst du bitte nochmal ausformulieren, was genau das wahrgenommene Problem ist? Den Ausdruck "URL Prefix" kenne ich nicht. Meinst du das Schema? Auch ist mir nicht klar, wie der erste Eintrag aus deinem Screenshot (`http://httdasd://dasdasd.com`) zustande.

Formuliere die Antwort gerne auf Deutsch. Ich finde es immer leichter, komplexe Sachverhalte in Sprachen darzustellen, die ich sicher beherrsche :+1:

**Comment by SteffenKn** [comment]
Ich denke was hier gemeint war ist dass wenn man das Protokoll mit angibt das Öffnen von Remote Solutions nicht funktioniert.
Bzw. das wenn man ein Protokoll mit angibt das nicht in das linke Feld übernommen wird.
