### ISSUE TITLE
♻️Close "Rename/Change/Move" Notification Faster

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1770]
## Description

Currently it takes kinda long to close a large amount of those Notifications in the down left corner of the Studio.

![Oct-07-2019 11-32-56](https://user-images.githubusercontent.com/17248802/66300799-3cbb0880-e8f6-11e9-8e84-079a1e9547e1.gif)

This amount of notifications pop up if you switch between branches in a repository with processes.

## Reproduction

- Open a Solution (FileSystem Folder)
- Move/Rename/Delete Diagrams

## Possible solution

Lower the delay of the closing popup.
Also it would be nice to add some css to make the "X"-Button always in the same place, regardless of the diagram name. (See Tabs in Chrome for example) This would make handling this popups even smoother.

**Comment by rrrene** [comment]
> This amount of notifications pop up if you switch between branches in a repository with processes.

@Vyperus Passiert das, selbst wenn du die Diagramme nicht editiert hast?

**Comment by SteffenKn** [comment]
> ## Possible solution
> Lower the delay of the closing popup.

This part is easy.

> Also it would be nice to add some css to make the "X"-Button always in the same place, regardless of the diagram name. (See Tabs in Chrome for example) This would make handling this popups even smoother.

I'm not quite sure how we're gonna place the button to do this.
Currently, the button is always placed in the upper right corner, but the height of the notification can vary. Placing the button at a fixed height would look bad in some cases.

The easiest way to archive this would probably be to place the button at the lower right corner, but imo this does not look that good either.

**Comment by Vyperus** [comment]
@rrrene As discussed I tested this again.

It seems like the following is happening:

If you open diagram (NOT change it) it is place in the "Open Diagrams" section. If you then switch the branch the described popups occur on all diagrams opened even if you did not change them.

**Comment by rrrene** [comment]
@Vyperus Das eigentliche Problem ist also, dass ich die "Die Datei hat sich geändert"-Meldung auch für Dateien bekomme, die ich geöffnet, aber nicht geändert habe. 

> If you then switch the branch the described popups occur on all diagrams opened

@SteffenKn Das sollten wir anders handhaben.

> the version that was "active" before you switched the branch will be saved

@SteffenKn Das sollten wir beheben. Hier sollte das "Die Datei hat sich geändert"-Ereignis zum Neuladen der Datei führen (auch für die gerade geöffnete Datei, wenn diese betroffen ist), aber *keine* Notification auslösen.

Wie immer lohnt sich bei Unsicherheit der Blick zu VS Code: Hier bekomme ich nur eine Benachrichtigung für Dateien, die ich editiert habe (bei denen also potentiell Konflikte entstehen).

Generell sollten wir mit den "Nur Symptome bekämpfen"-Maßnahmen in Zukunft vorsichtiger umgehen. Wenn der Motor meines Autos nennenswert Öl verliert, ist die Lösung auch nicht "regelmäßiger Öl nachfüllen" und "kürzere Strecken fahren", sondern das eigentliche Problem zu finden und zu beheben. :+1:

**Comment by SteffenKn** [comment]
@rrrene Das schnellere schließen der Notifications (wenn ich dies aktiv hervorrufe) sollte mMn aber  auf jeden Fall schneller gehen.
Wenn bspw. die Notifications richtigerweise kommen, da die Dateien geändert wurden hat man ja immer noch so eine lange Zeitspanne zwischen "ich klicke auf ein Notification um sie zu schliessen" und "die Notification ist weg".
