### ISSUE TITLE
🐛Inspect View of BPMN-Studio not working

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1774]
Disclaimer: I am not sure where this issue belongs, feel free to move it around.

## Description

What I did:

- Pull the master branch of the PE.
- Run `npm install`
- Run `npm run build`
- Run `npm start`

- Download BPMN-Studio 5.8.0
- Deploy some processes.
- Start a process.
- Go to Inspect.

![Bildschirmfoto 2019-10-07 um 14 48 19](https://user-images.githubusercontent.com/17248802/66313148-291d9b00-e912-11e9-9326-b68eebd705d9.png)

![Bildschirmfoto 2019-10-07 um 14 48 11](https://user-images.githubusercontent.com/17248802/66313151-2b7ff500-e912-11e9-9927-9a5e4c3a8cd7.png)

Since BPMN-Studio gets a 404 I am guessing there is some kind of route not registered on the PE? 

## Reproduction

See above.

## My setup

- BPMN-Studio: 5.8.0
- PE: 8.5.0

**Comment by alexanderkasten** [comment]
@Vyperus The master branch of the PE Runtime is on v9.0.0

**Comment by alexanderkasten** [comment]
@Vyperus Ist das nochmal aufgetreten? Ansonsten würde ich das Issue ersrmal schließen.

**Comment by Vyperus** [comment]
@alexanderkasten Nope ist nicht nochmal aufgetreten. Ich mach mal.
