### ISSUE TITLE
Weg zum Update unklar

### ISSUE THREAD

**Issue by nj0yeh** [process-engine/bpmn-studio#1788]
Beim Starten von BPMN Studio unter Mac erschien mir heute die Meldung "A new update is available. Please click on the BPMN Studio icon in the statusbar to start the download."

Hektisch, wie ich bin, habe ich die Meldung weggeklickt (ohne sie genau zu lesen) und mir dann überlegt, ich könnte das ja mal updaten. Dann habe ich im Menü des Programms nach einer entsprechenden Funktionalität gesucht und nicht gefunden. Also habe ich das Programm geschlossen und neu gestartet. Die Meldung kam zum Glück wieder. Zuerst habe ich (wieder ohne sie genau zu lesen) einfach auf den Text geklickt, denn so kann man bei vielen anderen Programmen das Update starten. Als das nicht geholfen hat, habe ich die Meldung genau gelesen und mich dann gefragt, wo die Statusbar ist. Zuerst habe ich auf das grüne Symbol im großen weiten Bereich unten rechts geklickt, was offensichtlich falsch war. Erst später fiel mir auf, dass die Statusbar unter dem großen Bereich ist. Das zugehörige Symbol erweckt nicht den Anschein, als könnte man damit ein Update starten.

**Comment by rrrene** [comment]
Machen wir :+1:
