### ISSUE TITLE
Dateiverknüpfung

### ISSUE THREAD

**Issue by nj0yeh** [process-engine/bpmn-studio#1789]
Ich habe Camunda und BPMN Studio installiert. Vor dem letzten Update waren meine .bpmn-Dateien mit BPMN Studio verknüpft. Nach dem Update sind sie mit Camunda verknüpft. Das konnte ich beheben, indem ich im Finder die entsprechende Option ausgewählt habe.

**Comment by alexanderkasten** [comment]
Das liegt daran, dass das Studio (Stable) auf die Alpha oder Beta Version geupdated hat. 
Die Alpha und Beta Versionen verfügen über keine File Association. 

Dass die Stable auf einen anderen Release Channel geupdated hat bzw das updaten erlaubt, wird von uns gefixt.

**Comment by alexanderkasten** [comment]
Wurde in https://github.com/process-engine/bpmn-studio/releases/tag/v5.8.1 gefixt. Da jetzt nur noch auf die richtigen Release Channel geupdated wird.
