### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by nj0yeh** [process-engine/bpmn-studio#1790]
Nach dem Öffnen eines BPMNs mittels Kommandozeile "open *.bpmn" wird das BPMN Studio zunächst nicht maximiert gestartet. Da ich aber fast immer mit maximierten Fenstern arbeite, ist meine erste Aktion also ein Doppelklick auf die Titelleiste, was dankenswerterweise jetzt zu einer Maximierung führt. Leider wird das BPMN, das von der Größe her dem kleinen Fenster angepasst war, dabei nicht mit vergrößert. Um dort reinzuzoomen, konnte ich keine Möglichkeit entdecken außer das Touchpad am Notebook zu benutzen. Da ich aber normalerweise mit externer Tastatur und Maus arbeite, erscheint mir das lästig.

Ich würde mir eine Funktion vielleicht in der Toolbar wünschen, um das BPMN an die aktuelle Fenstergröße anzupassen oder den Bereich auszuwählen, auf den vergrößert werden soll, und ein Zoomen mit einer der Mac-Funktionstasten und + oder - ermöglichen.

**Comment by alexanderkasten** [comment]
Um ein Diagramm neu auszurichten gibt es im PropertyPanel diesen Button:

![Bildschirmfoto 2019-10-10 um 10 42 50](https://user-images.githubusercontent.com/17065920/66553084-c7944100-eb4a-11e9-9338-8c76203e0947.png)

Das Zoomen funktioniert unter macOS, wenn du das Studio mit der geöffneten Design Ansicht im  Fokus hast und `cmd+` oder `cmd-` drückst.

Ich erstelle ein Issue, dass die zuletzt geöffnete Fenstergröße beim nächsten Start wieder genutzt wird. Dann braucht man das Diagramm nicht erneut Ausrichten.

**Comment by alexanderkasten** [comment]
#1793

**Comment by nj0yeh** [comment]
Danke. In das Property-Panel gehört dieser Button m. E. nicht hin.

Die Tastenkürzel funktionieren bei mir jetzt tatsächlich auch - keine Ahnung, warum es gestern nicht ging.

**Comment by rrrene** [comment]
> In das Property-Panel gehört dieser Button m. E. nicht hin.

👍
