### ISSUE TITLE
✨Add "Close All" Button

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#1806]
## Description

Currently it is not possible to close all diagrams in the "Open Diagrams" section in the Solution Explorer. This makes closing a lot of diagrams a lot more time intensive than it could be.

## Possible solution

Add a "Close All" button to the "Open Diagrams" section in the Solution Explorer to close all opened diagrams. 

## My setup

- BPMN-Studio 5.9.0-beta.3

**Comment by SteffenKn** [comment]
At first you're right a button in the SolutionExplorer might be helpful as it would be easy to find.
But there are already two ways to close all open diagrams:

1. Via the electron menu
![electron menu](https://user-images.githubusercontent.com/20394992/67189366-6132dc80-f3ee-11e9-8ef6-3473eb2142d2.jpeg)
2. Hit CMD + OPTIONS + W

**Comment by Vyperus** [comment]
@SteffenKn Ah thank you I didn't check that ;)
