### ISSUE TITLE
✨ Prozesse von externer ProcessEngine in Open Diagrams importieren

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#1818]
## Description

Wenn man einen Prozess auf einer externen ProcessEngine editieren will, geht dies nicht mehr.

Aktuell muss man den Prozess exportieren und dann lokal öffnen.

## Possible solution

Prozesse die auf einer externen ProzessEngine deployed sind. Sollten sobald man diese bearbeitet automatisch heruntergeladen und in `Open Diagrams` angezeigt werden.

Alternativ wäre auch ein Button `Edit locally` möglich

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt, ist aber im Atlas Studio vorhanden.
