### ISSUE TITLE
🐛Processes That Run into an Error Are Sometimes Still Running.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1830]
## Description

Sometimes processes that run into an error stay in running.

**Comment by SteffenKn** [comment]
I can not reproduce this bug, but @alexanderkasten had this problem a few days ago.

**Comment by ElRaptorus** [comment]
Ist das hier nochmal aufgetreten?

**Comment by SteffenKn** [comment]
Das Issue wurde hauptsächlich wegen dem Problem von @roblen45 geöffnet, @alexanderkasten hatte das Problem (oder ein ähnliches) ebenfalls.

Ich kann das jedoch nicht reproduzieren.

**Comment by ElRaptorus** [comment]
@roblen45  Ist das hier nochmal aufgetreten?

**Comment by ElRaptorus** [comment]
Da das hier scheinbar kein Issue mehr ist, mach ich das hier mal zu.
