### ISSUE TITLE
🐛 Token from Authority Does Not Get Updated Automatically.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1831]
## Description

The token from an authority needs to get updated automatically.

**Comment by SteffenKn** [comment]
Diesbezüglich sollten wir uns mal [Refresh Tokens](http://docs.identityserver.io/en/latest/topics/refresh_tokens.html) anschauen.

**Comment by Vyperus** [comment]
I think you are using the "Implicit Flow". In the Implicit Flow there is no such thing as a Refresh Token. What you want to have a look at then is the "Silent Refresh". 
Maybe this can help: https://www.scottbrady91.com/OpenID-Connect/Silent-Refresh-Refreshing-Access-Tokens-when-using-the-Implicit-Flow
