### ISSUE TITLE
🐛 When Removing a Local Solution it Gets Displayed as Not Connected.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1851]
## Description

When removing a local solution (e.g. via finder) it gets displayed as a not connected remote solution.

## Reproduction

![Local Solution Remove Bug](https://user-images.githubusercontent.com/20394992/68314065-dd4b4680-00b5-11ea-8f4d-b148665a40cc.gif)

## Possible solution

The local solution should rather be displayed as a removed folder somehow or it should be removed from solution explorer and a notification should be displayed.

## My setup

<img width="512" alt="Bildschirmfoto 2019-11-06 um 16 52 57" src="https://user-images.githubusercontent.com/20394992/68314076-e3d9be00-00b5-11ea-9e3e-188001e20a0e.png">

**Comment by ElRaptorus** [comment]
> The local solution should rather be displayed as a removed folder somehow...

Ich würde diese Variante bevorzugen. Vllt mit einem Marker _deleted from disk_ o.ä.
