### ISSUE TITLE
🐛 Changing the Authority of the InternalProcessEngine Does Not Work

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1859]
## Description

When changing the authority of the InternalProcessEngine the ProcessEngine still tries to use `http://localhost:5000` instead of the set authority.

## Reproduction

- Open up the BPMN Studio
- Change the authority of the InternalProcessEngine
- Notice that the ProcessEngine still tries to use `http://localhost:5000`

## My setup

v5.8.1

**Comment by ElRaptorus** [comment]
Wird die Authority in der Config-File umgeschrieben? 

Wenn ja, dann muss die interne PE neugestartet werden, damit die Änderungen wirksam werden. 

Die Config für den IAM Service wird nur einmalig beim Starten geladen und dann intern vom IAM Service gehalten. 

Ein dynamisches Ändern der Config ist bisher nicht möglich.

**Comment by SteffenKn** [comment]
Ich konnte bisher nicht finden wo wir das überhaupt "versuchen" für die PE zu setzen.
