### ISSUE TITLE
🐛 Paging for Processes doesn't work correctly

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#1871]
## Description

I think the BPMN gets 10 processes first and sorts the processes after that.

Therefore I received the following results:

<img width="1332" alt="Bildschirmfoto 2019-11-13 um 16 07 41" src="https://user-images.githubusercontent.com/36449148/68776636-b7cbb900-0630-11ea-9e17-37f2b42631e9.png">

and on the second page:

<img width="1329" alt="Bildschirmfoto 2019-11-13 um 16 07 55" src="https://user-images.githubusercontent.com/36449148/68776710-d7fb7800-0630-11ea-8ac1-fc6f820ce89e.png">

## My setup

BPMN Studio v5.9.0

**Comment by SteffenKn** [comment]
@roblen45 What exactly is the problem? The fact that the latest processes are not displayed first?
