### ISSUE TITLE
🐛Bad Request Error Message as JSON

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1907]
## Description

Wenn wir einen Prozess starten der nicht `executable` ist. Bekommen wir als HTTP Error einen Bad Request Error mit der Message 
````
{message: "The process model is not executable!"}
````

Wenn wir im Studio den Error abfangen und nun eine Notification mit `error.message`
anzeigen, steht natürlich noch `{message: "The process model is not executable!"}` in der Notification.

<img width="332" alt="Bildschirmfoto 2019-12-12 um 14 50 50" src="https://user-images.githubusercontent.com/17065920/70717556-e18b0500-1cee-11ea-96bb-d71a54b6c798.png">

<img width="366" alt="Bildschirmfoto 2019-12-12 um 14 51 08" src="https://user-images.githubusercontent.com/17065920/70717573-e94aa980-1cee-11ea-8c62-e1b7e1769379.png">

## Reproduction

- neues Diagramm mit BPMN-Studio erstellen
- gesetztes `executable` flag entfernen
- deploy & start 

## Possible solution

Es reicht wenn nur `The process model is not executable!` von der Runtime zurück gegeben wird.

**Comment by ElRaptorus** [comment]
Ich hab das issue mal nach BPMN-Studio verschoben, da es hier gelöst wurde.
