### ISSUE TITLE
🐛 BPMN Studio shows wrong sub process (call activity) during process execution

### ISSUE THREAD

**Issue by hartmutreichelt** [process-engine/bpmn-studio#1908]
## Description

During process execution in BPMN Studio (5.11.0-beta.1) the wrong sub-process (call activity) is displayed if it runs several times through the call activity.

## Reproduction

The process contains a call activity (BPMNStudio_Bug_Pic1, BPMNStudio_Bug_Pic2) which returns a value from a list of possible return values. At a certain value, the calling process steps into the call activity again through a loop in the parent process (BPMNStudio_Bug_Pic3, BPMNStudio_Bug_Pic4). If the sub-process is called for the second time, however, the instance of the first call is displayed (BPMNStudio_Bug_Pic5). Using the Inspect view (BPMNStudio_Bug_Pic6) you can select the correct instance of the sub-process (BPMNStudio_Bug_Pic7).

## Possible solution

The correct instance of a called sub-process should always be displayed.

![BPMNStudio_Bug_Pic1](https://user-images.githubusercontent.com/52411304/71728177-a9359d00-2e3c-11ea-8b83-ea6c750c4e56.png)
![BPMNStudio_Bug_Pic2](https://user-images.githubusercontent.com/52411304/71728179-a9ce3380-2e3c-11ea-82e1-d69644700bd6.png)
![BPMNStudio_Bug_Pic3](https://user-images.githubusercontent.com/52411304/71728180-a9ce3380-2e3c-11ea-92e7-7ccba87f43ff.png)
![BPMNStudio_Bug_Pic4](https://user-images.githubusercontent.com/52411304/71728181-a9ce3380-2e3c-11ea-8c27-f7ab67e27b30.png)
![BPMNStudio_Bug_Pic5](https://user-images.githubusercontent.com/52411304/71728182-a9ce3380-2e3c-11ea-9c34-8b1cadbf9657.png)
![BPMNStudio_Bug_Pic6](https://user-images.githubusercontent.com/52411304/71728183-a9ce3380-2e3c-11ea-955f-18a1f7ea7f32.png)
![BPMNStudio_Bug_Pic7](https://user-images.githubusercontent.com/52411304/71728184-aa66ca00-2e3c-11ea-928e-29d8f24909a0.png)

**Comment by alexanderkasten** [comment]
Fixed in v5.11.0
