### ISSUE TITLE
🐛 BPMN View breaks if Definition ID matches a Process ID

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1930]
## Description

Apparently, the Camunda Viewer is not able to render a process, if its ID matches the BPMN's definition ID.

I noticed this while working on the AtlasEngine, where the DefinitionID will be a processes main identifier, instead of a participant's ID.

## Reproduction

- Take [this BPMN](https://github.com/process-engine/bpmn-studio/files/4064592/runtime_domain_test_boundaryevent.bpmn.zip)
- Open it in BPMN Studio and Camunda
- The diagram should be displayed correctly
- Change the Definition ID to "runtime_domain_test_boundaryevent"
- Open it in BPMN Studio
- Notice that the process is shown as empty
- Open it in Camunda
- Notice the same thing

Since this is also occuring with the Camunda editor, I am somewhat certain that this is an issue with the Camunda Engine, not BPMN Studio.
But somebody should probably verify this. 

UPDATE:
The effect is better to reproduce when using multiple processes within a BPMN file.
- Take [this BPMN](https://github.com/process-engine/bpmn-studio/files/4064620/multiple_processes.bpmn.zip)
- Change the Definition ID to `process_1`
- Notice that the upper process is not rendered
- Change the Definition ID to `process_2`
- Notice that the lower process is not rendered

**Comment by SteffenKn** [comment]
IDs must always be unique.
The problem here is that BPMN Studio does not check the Definition ID when validating IDs.

**Comment by ElRaptorus** [comment]
My bad. Didn't realize this applied to _every_ ID for _every_ element.
