### ISSUE TITLE
Error Boundary Events are not self explanatory

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#1933]
Wir sollten bei ErrorBoundary-Events im UI erklären, was von "Name", "Code" und "Message" welche Bedeutung hat.

**Comment by ElRaptorus** [comment]
@rrrene Ich hatte gerade eine kurze Diskussion mit @moellenbeck und wir sind zu dem Schluss gekommen, dass das einzige Pflichtfeld für ein `ErrorBoundaryEvent` das `code` Feld sein sollte. 
Die anderen sollten nur beschreibend sein, aber nicht auf den abgefangenen Error gematched werden. 

Wenn wir das so umbauen, dann sollte das in die Beschreibungen mit einfließen.

**Comment by ElRaptorus** [comment]
In der Runtime wurde jetzt das Matching auf das "Name" Feld entfernt. 
Name ist jetzt nur noch ein reines Metadatenfeld, dass der Benutzer nach belieben füllen kann um seinen Fehlern einen sprechenden Namen zu geben.

"Message" wird derzeit noch gematched, allerdings nur dann, wenn im `ErrorBoundaryEvent` etwas in das entsprechende Feld eingetragen wurde. Gleiches gilt für Code.

Sollte in der Beschreibung berücksichtigt werden.

**Comment by SteffenKn** [comment]
@rrrene Hast du eine Vorstellung wie das aussehen soll oder soll ich mir was überlegen?
