### ISSUE TITLE
🐛 Modeler Breaks When Element ID Includes Space

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1943]
## Description

As soon as a resizable element has an id that contains a space, the modeler breaks.

## Reproduction

![modeler bug](https://user-images.githubusercontent.com/20394992/72729596-cafa8800-3b8f-11ea-9635-8daa094144ca.gif)

To reproduce this in the stable version the diagram needs to be saved after changing the id.

## My setup

<img width="512" alt="Bildschirmfoto 2020-01-20 um 14 15 20" src="https://user-images.githubusercontent.com/20394992/72729474-8838b000-3b8f-11ea-95a7-83d4068b2a2e.png">

**Comment by SteffenKn** [comment]
Diesbezüglich sollten wir auch nochmal Gedanken bezüglich des bpmn-js updates machen, dann wäre dieses Problem auch "richtig" gefixt.

**Comment by alexanderkasten** [comment]
#1638

**Comment by rrrene** [comment]
> dann wäre dieses Problem auch "richtig" gefixt

@SteffenKn Das Problem wäre richtig gefixt, wenn die Validierungsregel, die in #1944 von zwei (!) anderen Teammitgliedern approved worden ist, nicht auf "kein Leerzeichen (ASCII-Code 32)" prüfen, sondern validieren würde, dass die eingegebene ID ein valider QName ist.

Das wurde doch mehrfach im Daily besprochen!

**Comment by rrrene** [comment]
Und wieso bist du hier nicht mehr assigned gewesen?

**Comment by SteffenKn** [comment]
@rrrene Das Issue ist ja auch durch den PR **nicht** geschlossen worden:
> Diesbezüglich sollten wir auch nochmal Gedanken bezüglich des bpmn-js updates machen

Sobald wir bpmn-js geupdatet haben und uns überlegt haben wie wir mit solchen Diagrammen umgehen sollen die nicht QName konforme Ids besitzen ist das Problem gefixt.
So wie ich das auch schon mehrfach in deinem Beisein gesagt habe.

Ich finde es nur mehr als ungünstig mit invaliden Diagrammen die beispielsweise in Version 5.12.0 noch valide waren und funktionsfähig waren in Version 5.13.0 nicht mehr zu unterstützen. Ich habe um das Problem zu fixen schon mal in meiner Freizeit (!) etwas rumprobiert ([siehe branch](https://github.com/process-engine/bpmn-studio/commits/feature/add_qname_validation)).

> @SteffenKn Und wieso bist du hier nicht mehr zugewiesen gewesen?

Ich habe meine Zuweisung gelöscht weil Alex ja einen PR auf hat zum Updaten von bpmn-js auf hat, was ja der erste Schritt in Richtung Lösung des Problems ist.

**Comment by SteffenKn** [comment]
Folge Issue: https://github.com/process-engine/bpmn-studio/issues/1977
