### ISSUE TITLE
🚸  Hide Deploy Button on remote solutions

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#1954]
## Description

Right-clicking on a diagram of a remote solution will show the "deploy" button. 
Essentially, this means "deploy the deployed diagram to where its already deployed".

## Reproduction

- Right-click on any diagram of a remote solution
- Note that the "deploy" button is shown an clickable

![Bildschirmfoto 2020-01-28 um 11 07 16](https://user-images.githubusercontent.com/15343316/73254426-aff6cc00-41be-11ea-84c9-979b2bb8fff6.png)

## Possible solution

Do not display this button on remote solutions.

**Comment by SteffenKn** [comment]
IMHO this button makes sense because imagine you have multiple remote solutions connected to your BPMN Studio and you want to deploy a diagram from one remote solution to another.

If this button would not exist, you would have to export the diagram, open it with the BPMN Studio and before you could deploy it to the second remote solution.

**Comment by ElRaptorus** [comment]
Fair point.
But then the button should only be visible, when you are actually connected to multiple ProcessEngines, to avoid confusion.
Otherwise, where could I deploy an already deployed diagram to?

Also I'd recommend changing the command name, since this is a somewhat different UseCase than the usual "deploy", where I want to initially place my local diagrams on a ProcessEngine. 
Dunno, maybe `Send to [remote Solution]` or something similar.

**Comment by rrrene** [comment]
Bitte das ursprünglich von Christian vorgeschlagene Verhalten implementieren. 

Diagramme nicht auf der Platte, sondern nur auf einer PE zu haben, ist meiner Einschätzung nach kein nachhaltiger Use-Case.

Evtl. will man später mal Solutions über Deploy Targets hinweg „syncen“, aber dafür benötigen wir einen gefestigteren Solutionbegriff als heute und dann sollte die „Single Source of Truth“ technisch nicht eine der PEs sein, auf die gesynct wird. 👍🏻
