### ISSUE TITLE
🐳 Docker Container unter ReleaseChannel taggen

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1959]
## Description

Die Docker Container der ProcessEngine Runtime und des BPMN Studios sollten abhängig vom ReleaseChannel (alpha, beta, stable) auch unter diesen Tags in der neusten Version published werden.

**Comment by rrrene** [comment]
Folgende Konfiguration ergab sich aus einem Gespräch mit Robin und Paul:

- `4`, '5' - neuste Version der jeweiligen Major
- `latest` - neuste Stable

`alpha`, `beta`, `stable` werden nicht eingeführt.
