### ISSUE TITLE
✨ feat: Portable Version

### ISSUE THREAD

**Issue by ichtestemalwieder** [process-engine/bpmn-studio#1975]
Hello, 

first of all thanks very much for this amazing project. Just stumpled upon it and it seems this is a fully fledged node.js workflow/process engine? Absolutely great! 

Feature Reqeust: 
It would be great if the bpmn studio could also be released as a portable version (that must not be installed trough an installer/setup). 

Motivation: 
It's more trushtworty, less invasive, fits better various developper needs... 

Thanks for the great work.

**Comment by rrrene** [comment]
Hi @ichtestemalwieder, thx for your suggestion. It's now in our backlog!
