### ISSUE TITLE
🐛LET Ansicht für Subprozesse & TokenViewer funktioniert nicht richtig

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1986]
## Description

![Bildschirmfoto 2020-03-11 um 09 00 02](https://user-images.githubusercontent.com/17065920/76395005-b6a85f80-6376-11ea-81b8-79a08db1d181.png)

Die farbliche Darstellung sollte auch für die im Subprozess enthaltenen Elemente geschehen.

Zusätzlich funktioniert der TokenViewer für die im Subprozess enthaltenen Elemente nicht.

## Reproduction

Kann man dem Screenshot entnehmen.

## My setup

![Bildschirmfoto 2020-03-11 um 08 59 10](https://user-images.githubusercontent.com/17065920/76394942-9a0c2780-6376-11ea-8153-fef3d57cfc87.png)

**Comment by SteffenKn** [comment]
Das ist kein Bug.
Der LET unterstützt einfach noch keine Subprozesse, aber das sollten wir auf jeden Fall mal nachziehen 👍
