### ISSUE TITLE
✨ Display Name Property für Prozessdefinitionen

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#2000]
Wir benötigen sobald #1999  durch ist für die Prozessdefinitionen eine Art "Display Name" Property, damit sich der Benutzer beim Abfragen von Prozessdefinitionen einen lesbaren Namen anzeigen lassen kann.

Dieser Displayname könnte der Name der .bpmn Datei sein.
Damit würde sich z.B. auch die einmal andiskutierte Meldung "Haben sie den Prozess kopiert/verschoben?" gut umsetzen lassen.

Siehe auch https://github.com/process-engine/bpmn-studio/pull/1999#issuecomment-606594112

**Comment by rrrene** [comment]
> Wir benötigen sobald #1999 durch ist für die Prozessdefinitionen eine Art "Display Name" Property

Bitte nicht immer alles verkomplizieren. 

In der Definition sind Prozesse, die gepflegte IDs und Namen haben (in 99,9% der Fälle sogar nur einer). Bitte diese anzeigen.
