### ISSUE TITLE
Cannot open folders with cli

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#2007]
## Description

`open` is a built in commandline tool to open applications on macos, see `man open`.

Using open I would like to open a solution folder in BPMN-Studio.

## Reproduction

`open -a BPMN\ Studio processes`

Should open the processes folder in bpmn-studio.

Note that running `open -a BPMN\ Studio processes/a_process.bpmn` works. 

## Possible solution

Support opening folders.

## My setup

<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/4148404/79228982-97fc2380-7e62-11ea-8f7a-1bb3958283c1.png">

**Comment by rrrene** [comment]
Die Idee ist genau richtig, aber das werden wir in BPMN Studio leider nicht mehr einbauen. 

Die Atlas CLI wird zukünftig Ordner mittels Atlas Studio öffnen können.

**Comment by Paulomart** [comment]
Looking forward to that feature :)
