### ISSUE TITLE
Multiline error messages are not displayed correctly in log view

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#2010]
## Description

Error messages get truncated after the frist line in the log view.

![grafik](https://user-images.githubusercontent.com/4148404/79430843-d3653200-7fc9-11ea-86f5-47d1ea64686b.png)

## Reproduction

Create a process that throws a multiline error message: For example use an invalid payload configuration.

## Possible solution

Display all lines of the error message in the log view.

## My setup

<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/4148404/79430981-0efffc00-7fca-11ea-931e-8268d2006155.png">

**Comment by rrrene** [comment]
:+1:

**Comment by rrrene** [comment]
@alexanderkasten Wir sollten in der Log-View auch einen "Details"-Button einbauen, wie in der Taskliste. Dann können wir die ErrorMessage "getrost" mit `...` abschneiden und im Modal dann voll anzeigen.

**Comment by alexanderkasten** [comment]
@rrrene Abgeschnitten wird diese schon falls sie zu lang werden sollte. Voll wird die Message/Error im TokenViewer an dem Element angezeigt. Was würdest du noch im Modal sehen wollen? 
Die Informationen die auch in der Tabelle als Spalten angegeben sind und falls es ein Log von einer FlowNodeInstanz ist würde ich noch den Token mit in das Modal geben.

Was hältst du davon?

**Comment by rrrene** [comment]
Klingt gut. :+1:
