### ISSUE TITLE
Add example to timer events help texts

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#2013]
Wir müssen etwas augenfälligere Beispiele für die Date-, Duration- und Cycle-Notationen angeben.

- **Date:** Als Beispiele "den 06.12.2030" sowie "den 06.12.2030 um 19:15" nehmen.
- **Duration:** Als Beispiele "5 Sekunden" und "12 Stunden" angeben.
- **Cycle:** Als Beispiele "jeden Tag um Mitternacht" sowie "jeden Montag-Freitag zu jeder vollen Stunde" nehmen.

Mir ist selber nicht klar, wo der optimale Ort im Text für diese Beispiele ist. Ich würde sie erstmal "oben" bei den grundsätzlichen Erläuterungen zum jeweiligen Format anfügen und gucken, wie das aussieht 👍

Die Beispiele sind komplett willkürlich, falls irgendeins davon nicht passt, einfach melden.

**Comment by Paulomart** [comment]
Ich fänds cool, wenn es auch ein Beispiel gäbe wie man den Token im Duration Feld verwendet.
