### ISSUE TITLE
Only opened processes are shown in selection for call activity

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#2014]
## Description

Only opened processes are shown the call activity dropdown:

## Reproduction

![grafik](https://user-images.githubusercontent.com/4148404/79838928-0c2f4d80-83b4-11ea-87ca-38f624d1538c.png)

![grafik](https://user-images.githubusercontent.com/4148404/79838992-2e28d000-83b4-11ea-92ce-8d9de46e6530.png)

## Possible solution

Show all processes in the current solution in the dropdown.

## My setup

<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/4148404/79839039-3c76ec00-83b4-11ea-9153-d0e5b8196f9a.png">

**Comment by Paulomart** [comment]
Also: When selecting a process in the dropdown, by default no startevent is selected: If there is only one startevent, it should select that.

**Comment by alexanderkasten** [comment]
Wir haben uns entschieden das erst einmal so zu lassen und das im AtlasStudio richtig zu machen.
