### ISSUE TITLE
♻️ Make sure errors aren't suppressed

### ISSUE THREAD

**Issue by heikomat** [process-engine/bpmn-studio#202]
#### Describe your issue

In a lot of places where the code interacts with the bpmn-moddeler using callbacks, a lot of errors are suppressed. This means the callback has an error-parameter, but it isn't checked or rethrown, it's just ignored.

We should throw errors in these places, so the software doesn't fail silently

#### Possible solution

Whenever an Error is provided to a callback, throw it or a new Error that gives context.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Errors sure aren't suppressed anymore.
