### ISSUE TITLE
Portable-Versionen auf Windows langsamer als installierbare?

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#2021]
Bitte einmal prüfen, ob die Portable-Version des Studios langsamer startet als die installierbare Version.

**Comment by alexanderkasten** [comment]
Irgendwie startet die Portable bei mir überhaupt nicht. Ich muss das noch mal auf anderen Windows Systemen testen

**Comment by alexanderkasten** [comment]
@rrrene Der @SteffenKn konnte das verifizieren und sagt das dauert sehr lang die Portable Version zu starten.

**Comment by rrrene** [comment]
@alexanderkasten Wenn wir keine Idee haben, woran das liegt, dann bitte die Portable-Version wieder aus dem Release-Prozess entfernen.
