### ISSUE TITLE
 🐛 Unable to close all opened diagrams if there are unsaved changes

### ISSUE THREAD

**Issue by Alex5M** [process-engine/bpmn-studio#2037]
## Description

The UI freezes when attempting to close all opened diagrams if there are at least two diagrams with unsaved changes.

The screen looks like this
![Bildschirmfoto 2020-06-15 um 12 34 17](https://user-images.githubusercontent.com/53556773/84648992-111d0300-af06-11ea-9e21-38f3c01e0771.png)
and none of the buttons seem to do anything. Pressing Esc doesn't close the dialog either.

Video:

![Bildschirmvideo aufnehmen 2020-07-08 um 16 04 51 (1)](https://user-images.githubusercontent.com/53556773/86930045-d38f4c80-c136-11ea-9c2f-d7b35aa7c3c1.gif)

Error log:
[-1594217008995.log](https://github.com/process-engine/bpmn-studio/files/4891107/-1594217008995.log)

## Reproduction

1. Open at least 2 diagrams
1. Make changes to both without saving them
1. Press the 'x' for closing all opened diagrams
![Bildschirmfoto 2020-06-15 um 12 33 39](https://user-images.githubusercontent.com/53556773/84649009-1712e400-af06-11ea-80b5-d0973fa61c2c.png)

## Expected behavior

"Cancel" is expected to close the dialog without closing any diagrams.
"Don't save" is expected to close all opened diagrams without saving.
"Save" is expected to save all diagrams before closing them.

## My setup

- BPMN Studio v6.0.0-beta.10

Also tested on BPMN Studio v6.0.0-beta.13

**Comment by alexanderkasten** [comment]
Can you still reproduce this behavior? @Alex5M

**Comment by Alex5M** [comment]
The issue seems to inconsistently appear for only 1 diagram. However when editing at least 2 diagrams it appears consistently. I've updated the issue to reflect this.

**Comment by Alex5M** [comment]
Edit:
* Add video to better describe issue
* Add log file
