### ISSUE TITLE
No option to allow self signed certificates

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#2039]
## Description

If some setups you want to connect to processengines that run behind a ssl proxy: This works fine. 

But you cannot connect to processengines that present an invalid or self signed certificate.

## Reproduction

Try to connect to a host that presents an invalid or self signed certificate. BPMN-Studio says that if cannot reach the processengine.

https://self-signed.badssl.com/
<img width="494" alt="grafik" src="https://user-images.githubusercontent.com/4148404/86374439-dd233b00-bc84-11ea-8ee7-cc7f20354d5a.png">

## Possible solution

Provide an option to skip the certificate check for a processengine. This should indicate the security issues that arise.

**Comment by rrrene** [comment]
@Paulomart Kannst du das bitte auf deutsch formulieren? Ich verstehe bei obigem Text ohne den Kontext unserer vorangegangenen Unterredung nicht, was du möchtest und ich bin mir sicher, dass du im Deutschen weniger Orthograhie- und Grammatikfehler machen würdest 😉

**Comment by Paulomart** [comment]
We have already found a different solution. Thanks for your help.
