### ISSUE TITLE
✨ Autocomplete für Payloads and Gateway Conditions

### ISSUE THREAD

**Issue by KaiLuettmann** [process-engine/bpmn-studio#2048]
_Diese Funktion wurde vom Kunden in einem Workshop bei der Flaschenpost gewünscht!_

## Description
**Als ein** Entwickler für Geschäftprozesse
**möchte ich** eine Autovervollständigung bei der Entwicklung von Payloads von ServiceTasks und Gateway Conditions im BPMN Studio benutzen.
**um** die Zeit einzusparen, die sonst für kopieren und einfügen der Namen verwendet wird.

![Bildschirmfoto 2020-07-10 um 15 31 20](https://user-images.githubusercontent.com/33122946/87159977-77f1ca00-c2c2-11ea-99c1-014faca88db8.png)
![Bildschirmfoto 2020-07-10 um 15 31 06](https://user-images.githubusercontent.com/33122946/87159982-79bb8d80-c2c2-11ea-8860-41ccd4c2fc7e.png)

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt, ist aber im Atlas Studio vorhanden.
