### ISSUE TITLE
✨ Veränderung der Breite des Payload-Fensters bei ServiceTasks

### ISSUE THREAD

**Issue by KaiLuettmann** [process-engine/bpmn-studio#2049]
_Diese Funktion wurde vom Kunden in einem Workshop bei der Flaschenpost gewünscht!_

## Beschreibung
**Als** Entwickler für Geschäftprozesse, 
**möchte ich** gerne das Fensters bei der Entwicklung eines Payloads von einem ServiceTasks ebenfalls in der Breite verändern können,
**um** den Payload in einem wohlgeformten Format (ohne unnötige Zeilenumbüche) lesen und anpassen zu können.

Diese Funktion würde die Produktivität meiner Entwickungsaktivitäten erhöhen.
![Bildschirmfoto 2020-07-10 um 15 31 20](https://user-images.githubusercontent.com/33122946/87160765-c5bb0200-c2c3-11ea-91f3-604b09d55170.png)

**Comment by rrrene** [comment]
Wir könnten mal gucken,  ob das mit  wenigen Handgriffen zu machen ist. /cc @alexanderkasten
