### ISSUE TITLE
✨ Zeige StartParameter in der "Inspect-Ansicht"

### ISSUE THREAD

**Issue by KaiLuettmann** [process-engine/bpmn-studio#2050]
_Diese Funktion wurde vom Kunden in einem Workshop bei der Flaschenpost gewünscht!_

## Beschreibung
**Als** Entwickler für Geschäftsprozesse
**möchte ich** gerne die Startparameter der Prozessinstanzen in der "Inspect" Ansicht sehen,
**damit ich** Prozessinstanzen auf der Grundlage der Startparameter identifizieren kann.
![Bildschirmfoto 2020-07-10 um 15 50 37](https://user-images.githubusercontent.com/33122946/87161650-1f6ffc00-c2c5-11ea-8808-c176411ce5e4.png)

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt, ist aber im Atlas Studio vorhanden.
