### ISSUE TITLE
🐛 Groß/Kleinschreibung in Formfields

### ISSUE THREAD

**Issue by asiebelist** [process-engine/bpmn-studio#2061]
## Description

Wenn die Felder eines Form Fields großgeschrieben sind und anschließend in einem ServiceTask an einen ExternalTask-Worker in der Payload übergeben werden, kommt diese dort nicht an.
Im Token sind die FormField-Namen dann kleingeschrieben.

## Possible solution

Entweder alle FormField-Namen mit einem kleinen Buchstaben beginnen lassen (workaround) oder die Weitergabe innerhalb des Tokens anpassen.

**Comment by alexanderkasten** [comment]
@SteffenKn Ich denke das Problem ist auf Seite der Engine(s).
@asiebelist Mit welcher Version des Studios und der Engine ist das aufgefallen? Hast du die im Studio integrierte Engine genutzt?

**Comment by asiebelist** [comment]
> @asiebelist Mit welcher Version des Studios und der Engine ist das aufgefallen? Hast du die im Studio integrierte Engine genutzt?
Ja, es war das Studio in der Version 6.0.0-beta.17 und die darin integrierte Engine

**Comment by ElRaptorus** [comment]
> Ich denke das Problem ist auf Seite der Engine(s)

Kann eigentlich nicht sein, da das "formFields", bzw. "FormFields" Wrapper Property aus der Engine vollständig rausgeflogen ist.

**Comment by alexanderkasten** [comment]
Wunder mich jetzt auch. 
@asiebelist Kannst du einmal zeigen wie du das in die Payload übergibst?

**Comment by asiebelist** [comment]
> Wunder mich jetzt auch.
> @asiebelist Kannst du einmal zeigen wie du das in die Payload übergibst?
> 
> Edit: Oder mir das Diagramm zukommen lassen?

Das BPMN liegt [hier](https://github.com/atlas-engine/LibraryExamples) und das Problem trat bei dem UserTask `KundenIdentifizieren` für das Field `kundenId` und anschließend mit der im Token enthaltenen Wert für `istAutorisiert`. Wenn einer der Bezeichnungen groß geschrieben wird/wurde ist dieser über den Token nicht mehr zugreifbar.

**Comment by alexanderkasten** [comment]
@asiebelist @S3bastianGriesa @ElRaptorus Ich habe mir das mal angeschaut. Das Problem liegt nicht auf Seiten des BPMN Studios und ich denke auch nicht an der Engine, denn mit einem TS ExternalTaskWorker (Client.TS v1.0.0) funktioniert das alles auch mit groß geschriebenen Properties. Die Engine reicht die Sachen wie Payload etc direkt so an den Client und gibt das Result wie es ist auch zurück. Da läuft wohl was im Client .Net falsch. 

Das Issue ist hier am falschen Ort. @asiebelist Würdest du ein neues im Client .Net eröffnen?

**Comment by S3bastianGriesa** [comment]
Wurde zum .NET-Client verlagert: https://github.com/atlas-engine/Client.NET/issues/52
