### ISSUE TITLE
🐛  Diagramm kann nicht deployed werden, wenn "executable==false".

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#2075]
## Description

Wenn bei einem Diagramm das Flag "executable == false" gesetzt ist, kann das Diagramm nicht deployed werden.
Die Meldung weisst aber nicht auf die Ursache hin:

![Bildschirmfoto 2020-08-31 um 10 08 23](https://user-images.githubusercontent.com/36449148/91697954-3ff45e00-eb72-11ea-92cf-ff5506dcac61.png)

## Possible solution

Meldung verbessern

## My setup

BPMN Studio 6.0.0

**Comment by alexanderkasten** [comment]
So wie ich das gesehen habe ist es so, dass das Diagramm deployt wird, allerdings nicht in der Liste der ProcessModels auftaucht (weil es nicht executable ist). Diese Fehlermeldung im Studio kommt daher dass das Studio, nach dem Deploy, versucht das Diagramm in der Design Ansicht von der Engine zu laden. Die Engine sagt nun aber 404 NotFound, weil es nicht in der Liste ist. 

@SteffenKn @S3bastianGriesa Hier müsstet ihr vielleicht eine entsprechendere Fehlermeldung werfen, wenn ein Diagramm angefragt ist, welches existiert aber nicht ausführbar ist.

**Comment by S3bastianGriesa** [comment]
Das Problem scheint im ProcessEngine.CompatibilityProxyAdapter zu liegen: 

https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/blob/develop/src/consumer_api/proxy_services/process_model_proxy_service.ts#L257

https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/blob/develop/src/consumer_api/proxy_services/process_model_proxy_service.ts#L85

Da sollten wir definitiv eine sprechendere Fehlermeldung einbauen.

Aber liegt der Fehler nicht schon da, dass ein non-executable BPMN überhaupt deployed werden kann? Ich denke wir sollten bereits bei dem Deployment-Versuch einen Fehler werfen, damit ein non-executable BPMN gar nicht erst in die Datenbank geschrieben wird. Oder gibt es einen Anwendungsfall, in dem das Sinn ergeben würde? 🤔

**Comment by alexanderkasten** [comment]
> Das Problem scheint im ProcessEngine.CompatibilityProxyAdapter zu liegen:
> 
> https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/blob/develop/src/consumer_api/proxy_services/process_model_proxy_service.ts#L257
> 
> https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/blob/develop/src/consumer_api/proxy_services/process_model_proxy_service.ts#L85
> 
> Da sollten wir definitiv eine sprechendere Fehlermeldung einbauen.
> 
> Aber liegt der Fehler nicht schon da, dass ein non-executable BPMN überhaupt deployed werden kann? Ich denke wir sollten bereits bei dem Deployment-Versuch einen Fehler werfen, damit ein non-executable BPMN gar nicht erst in die Datenbank geschrieben wird. Oder gibt es einen Anwendungsfall, in dem das Sinn ergeben würde? 🤔

@S3bastianGriesa Soweit ich weiß ist es gewollt non-executable Prozesse deployen zu können. 
Ich könnte ja ein Diagramm mit mehreren Prozessesn deployen wollen obwohl darin nur 1 oder 2 executable sind.

**Comment by S3bastianGriesa** [comment]
>@S3bastianGriesa Soweit ich weiß ist es gewollt non-executable Prozesse deployen zu können.
Ich könnte ja ein Diagramm mit mehreren Prozessesn deployen wollen obwohl darin nur 1 oder 2 executable sind.

Okay, verstehe ich. Allerdings können non-executable Prozesse nicht mehr vernünftig (via Studio oder CLI) entfernt werden, da diese über die API nicht sichtbar sind. Da schafft man sich eine ganze Menge Leichen an, die die Datenbank auf Dauer zumüllen

**Comment by S3bastianGriesa** [comment]
Ich würde jetzt erstmal die Fehlermeldung verbessern und dann das Thema mit den non-executable Prozessen nochmal für nächste Woche mit in das techn. Meeting nehmen

**Comment by alexanderkasten** [comment]
> > @S3bastianGriesa Soweit ich weiß ist es gewollt non-executable Prozesse deployen zu können.
> > Ich könnte ja ein Diagramm mit mehreren Prozessesn deployen wollen obwohl darin nur 1 oder 2 executable sind.
> 
> Okay, verstehe ich. Allerdings können non-executable Prozesse nicht mehr vernünftig (via Studio oder CLI) entfernt werden, da diese über die API nicht sichtbar sind. Da schafft man sich eine ganze Menge Leichen an, die die Datenbank auf Dauer zumüllen



> Ich würde jetzt erstmal die Fehlermeldung verbessern und dann das Thema mit den non-executable Prozessen nochmal für nächste Woche mit in das techn. Meeting nehmen

Oh ja stimmt, das wirft bei mir gerade ein paar Fragen auf. 
Sollte nächste Woche auf jeden Fall noch mal besprochen werden.
