### ISSUE TITLE
🐛Property Panel freezes after clicking to a Flow Node

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#2076]
## Description

When navigating through the flow nodes, the Property Panel gets stuck at some point and clicking on a different flow node does not update anymore. I recorded a screen capture [[1]].

## Reproduction

Happens after sometime after clicking around; not clear what triggers this.

## My setup

MacOs Catalina 10.15.6
BPMN Studio 6.0.0

[1]: https://1drv.ms/v/s!AktaDumyOsxsiY9RDKaFcVB6RqmaRg?e=Pfh0WK

**Comment by alexanderkasten** [comment]
Thanks for opening the issue. I'll take a closer look at the problem

**Comment by cmg-dev** [comment]
I will see if I can reproduce this somehow reliable but it happens a lot.

The diagram has 30+ elements, but they are mostly unconfigured, aka just plain service tasks. Maybe this helps.

**Comment by alexanderkasten** [comment]
@cmg-dev The referenced PR fixes the bug hopefully. If you can still reproduce the behaviour just reopen this issue

**Comment by cmg-dev** [comment]
I've installed 6.1.0 as suggested by @alexanderkasten and will report how the Studio behaves. :)
