### ISSUE TITLE
🐛No the displayed Form Field is not selected by default.

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#2077]
## Description

When using the enum in a form, the displayed value does not get passed into the token.
Instead the default value is taken. I have captured some screen records for this [[1]][[2]].

## Reproduction

Create a form field like in the image below, add two or more choices to the enum and use the live executing tracker to show the form. When viewing the form do not click into the list and click continue. See in the token inspect that the default value got passed into the token instead of the first selected item.

## Possible solution

Use the selected entry in the list, even if nothing has been clicked.

As a user this would be less confusing as it is questionable that the default field has to be maintained for this. 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4034128/91862463-449e3c80-ec6e-11ea-8aa4-8f9a35b5891f.png">

see #2076 

[1]: https://1drv.ms/v/s!AktaDumyOsxsiY9SYU2M3Rfyn1WknA?e=ihpKhv
[2]: https://1drv.ms/v/s!AktaDumyOsxsiY9TZ2xNa3jZy_31wQ?e=IdcgXv

**Comment by alexanderkasten** [comment]
Danke für das öffnen des Issue. Ich werde mir das Problem genauer anschauen
