### ISSUE TITLE
Deploy a diagram uses the process id instead of the name used in Solution Explorer

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#2078]
## Description

This is less a bug than a quality of life thing [[1]]

## Reproduction

Deploy the diagram to the engine and see that the process id is taken instead of a useful name, like the name shown in the Solution Explorer.

## Possible solution

Use the digram name as deploy name or the process name as the filename when shown in the Solution Explorer. Either way the names should align in my opinion. As Changing the `Process_Id` is not intuitive nor trivial.
 
## My setup

see #2077 

[1]: https://1drv.ms/v/s!AktaDumyOsxsiY9VqkO2P3ZwuThyrg?e=8hDs5w

**Comment by ElRaptorus** [comment]
Dass die Engine die IDs als Key für ein deploytes XML verwendet ist vollkommen richtig, da nur die IDs garantiert eindeutig sind. 

Für den Solution Explorer fänd ich es aber auch definitiv besser, wenn dort der Name des Prozesses und nicht dessen ID stehen würde. :+1:

**Comment by rrrene** [comment]
Das beschriebene Verhalten ist seit Jahren stabil und wir sollten so spät im Produktlebenszyklus keine neuen Inkonsistenzen einführen. 

Wir werden hier leider keine Zeit investieren können. 👍

**Comment by cmg-dev** [comment]
> Dass die Engine die IDs als Key für ein deploytes XML verwendet ist vollkommen richtig, da nur die IDs garantiert eindeutig sind.

Never wanted to change that 👍 As I surely understand the problem.

My colleagues are guaranteed to be confused by this.

Maybe I worded my _Possible Solution_ too complex when I wrote to:

> Use the digram name as deploy name or the process name as the filename when shown in the Solution Explorer. Either way the names should align in my opinion. As Changing the Process_Id is not intuitive nor trivial.

Emphasising on the _or_ part, I wanted to suggest that the name the Solution Explorer displays, is the same in the Open Diagrams and Solution as it is displayed in the deployed Engine, so that they align.
