### ISSUE TITLE
🐛 Submission of forms does not work anymore in 6.1.0 

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#2081]
## Description

When clicking _Continue_ on a User Form the Studio does not proceed. Developer Tools report an error.

In 6.0 it worked that way perfectly fine.

## Reproduction

You can use the BPMNs [bpmns.zip](https://github.com/process-engine/bpmn-studio/files/5167313/bpmns.zip)

The error reported in the dev tools is: 

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/4034128/92090704-0882ed00-edd0-11ea-90de-b3404459713d.png">

You can see the videos in action as well as the workaround [[1]][[2]].

## Possible solution 

1. The Lane _needs_ to be able to work for anyone. So not specifying the persons responsible for the lane is BPMN conform and should be supported, this means, that any person who can see the process, can execute the task
2. If you decide not to do it this way, an error should get displayed that this will cause a problem in the Engine.

## My setup

MacOS Catalina
BPMN Studio 6.1.0

[1]: https://1drv.ms/v/s!AktaDumyOsxsiY9WjTjjJvIwXSQQaQ?e=jgxccg
[2]: https://1drv.ms/v/s!AktaDumyOsxsiY9Xa9N5sDKaXdF7mA?e=moh29C

**Comment by ElRaptorus** [comment]
@cmg-dev FYI: 
Wir konnten das Problem auf ein Issue mit der AtlasEngine zurückverfolgen. 

Wird in diesem Zyklus noch gefixt und kommt dann in das Oktober Release mit rein. 

Bis dahin kannst du dir damit behelfen, dass du die Lane ganz entfernst, statt einen Leernamen zu benutzen.

**Comment by alexanderkasten** [comment]
> @cmg-dev FYI:
> Wir konnten das Problem auf ein Issue mit der AtlasEngine zurückverfolgen.
> 
> Wird in diesem Zyklus noch gefixt und kommt dann in das Oktober Release mit rein.
> 
> Bis dahin kannst du dir damit behelfen, dass du die Lane ganz entfernst, statt einen Leernamen zu benutzen.

Bei mir gehts auch ohne Lane nicht

**Comment by alexanderkasten** [comment]
Fixed in https://github.com/process-engine/bpmn-studio/releases/tag/v6.2.0-beta.1
