### ISSUE TITLE
🐛 Ändern des Prozessnamens ändert nur den Namen des Participants

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/bpmn-studio#2083]
## Beschreibung

Wenn ich im Modeller den Namen eines Prozesses über die Prozesstitelleiste ändere (Siehe Clip), dann wirkt sich diese Änderung lediglich auf den Participant, nicht aber auf den tatsächlichen Prozessnamen aus.

Ich **muss** den Namen des Prozesses im Property Panel unter `Pool - Name` ändern. Es gibt keine andere Möglichkeit.

Das ist wenig intuitiv. 

## Reproduktion

![Screen Capture_select-area_20200904090321](https://user-images.githubusercontent.com/15343316/92209642-a5579000-ee8d-11ea-87ca-b5207b55d7c5.gif)

## Lösung

Ich würde erwarten, dass sich auch der Name des Prozesses ändert, wenn ich die Titelleiste im Modeller bearbeite. 

Ich weis, das Atlas Studio Release steht vor der Tür, aber wenn es nicht allzu viel Aufwand ist, würde ich das hier noch für eine sinnvolle Ergänzung halten.

**Comment by alexanderkasten** [comment]
Was würde es denn bringen, den Name eines Elements zu ändern, der nirgendwo angezeigt wird?

**Comment by ElRaptorus** [comment]
Der Name des Prozesses wird z.B. in der Atlas UI als Anzeigename benutzt, oder als Name für Prozessinstanzen.

**Comment by alexanderkasten** [comment]
Das wird dann nach heutiger Bekanntgabe im Daily, nicht mehr ins BPMN Studio eingebaut. 

Im Atlas Studio ist das aber schon implementiert.
