### ISSUE TITLE
🐛 BPMN Studio reconnect to remote AtlasEngine fails

### ISSUE THREAD

**Issue by larspapen** [process-engine/bpmn-studio#2085]
## Description

Trying to reconnect to the remote AtlasEngine does not work.
The Google Authorization Window wont open until you cleared the site data of BPMN Studio 6.1.0

## My setup
- OS (`OS X` + `version`) MacOS Mojave 10.14.6:
- Node (`node --version`): v.14.8.0
- NPM (`npm --version`): 6.14.7
- Docker (`docker version --format '{{.Server.Version}}'`): 19.03.12

**Comment by alexanderkasten** [comment]
Kannst du das Problem näher beschreiben?

**Comment by larspapen** [comment]
Als ich das BPMN Studio geöffnet habe, habe ich gesehen, dass meine Atlas Engine nicht mehr verbunden war.

Sah dann so aus:
![image](https://user-images.githubusercontent.com/29885012/92694477-6622b680-f347-11ea-95c7-4edf68895026.png)

Try to login funktionierte nicht d.h. das Fenster 
![image](https://user-images.githubusercontent.com/29885012/92694544-83578500-f347-11ea-82bb-38feef433bb2.png)
tauchte nicht mehr auf.

![image](https://user-images.githubusercontent.com/29885012/92694585-910d0a80-f347-11ea-83b8-e7e9150306d8.png)

Nachdem ich die site data gelöscht habe, tauchten Fenster auf(ich habe mehrfach try to login gedrückt) und ich konnte mich anmelden.
![image](https://user-images.githubusercontent.com/29885012/92694664-ada94280-f347-11ea-9eee-bde8a939e098.png)
