### ISSUE TITLE
Rename the old ConsumerClient

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#209]
#### Describe your issue

The name "ConsumerClient" used by BPMN-Studio is confusing. We will rename it to "BPMN-Studio-Client" 

#### Possible solution

The repo needs to renamed fully and then published to npm.
Now all references in BPMN-Studio needs to be renamed as well.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
There is already an issue for it: https://github.com/process-engine/consumer_client/issues/17

**Comment by cmg-dev** [comment]
https://github.com/process-engine-pro/organization/issues/63
