### ISSUE TITLE
Windows: BPMN Studio Stable bietet Beta bei Update an

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#2095]
Unter Windows hat mir gerade eine frisch Installierte Version von BPMN-Studio Stable vorgeschlagen auf eine Beta Version zu updaten.

Installierte Version: Release v6.2.0

Runtergeladene Beta: 6.3.0-beta2

**Comment by rrrene** [comment]
@alexanderkasten Kannst du reproduzieren?

**Comment by alexanderkasten** [comment]
@rrrene Leider nicht.
