### ISSUE TITLE
Bring back "dropdown start button"

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#22]
#### Describe your issue

The StartButton on the processdef details page is not clearly saying that it **created** a new process.

#### Possible solution

TODO

#### See

https://github.com/process-engine/charon/issues/35

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
If you click on the button you get navigated to the "Initiale Prozessdaten eingeben"-Page of the Create Process. I think this should be enough information that, after you clicked on "weiter", a process is created.

**Comment by Paulomart** [comment]
The current implementation is a work around caused by https://github.com/process-engine/charon/commit/c6b1cb637c87ea19bf73b7d16bd762426a6cd91e if we revert this commit we have the old behavior. We want the old behavior, but with improved UX. Thus this issue is not resolved.

**Comment by Vyperus** [comment]
Since the waiting room is implemented it clearly says it created a process.
