### ISSUE TITLE
cmd + q not working

### ISSUE THREAD

**Issue by heikomat** [process-engine/bpmn-studio#220]
#### Describe your issue

When pressing cmd+q to quit the application, nothing happens

#### How can others reproduce the issue?

Try quitting the application with cmd + q

#### Possible solution

Implement support for the cmd + q shortcut (just like the cmd + a/c/v shortcuts)

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): OS X 10.13.3
- Node (`node --version`): 9.8.0
- NPM (`npm --version`): 5.6.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Did you test this on the latest release version?
I think this has already been fixed with #218.

**Comment by heikomat** [comment]
@SteffenKn this fix is not yet published, is it?

**Comment by SteffenKn** [comment]
@heikomat No, not yet. We wanted to publish #217, #218, #219 yesterday, but we could not, because we need @Vyperus for it.
