### ISSUE TITLE
Loading animation `gears.svg` not showing

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#223]
#### Describe your issue
Browser can't seem to render the gears.svg file. Shows instead the browsers icon for missing/broken image.
Filepath is correct and file exists.

#### How can others reproduce the issue?
Stop processEngine instance, open bpmn-studio(starts polling and tries showing that loading anim).

#### What's your setup
OSX, Chrome & Firefox

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
I need a little more insight on how to reproduce that error. Does it happen in electron app? Or did you use `au run` or `npm start` to start the application?

**Comment by Vyperus** [comment]
I was able to reproduce this with 'npm run build && npm start`.
This is actually a problem with the node-server used to start the application this way.

**Comment by LeoTT** [comment]
Right, it was the node server.
ContentType of svgs was wrong, this pr #240 fixes that.
