### ISSUE TITLE
xsi:type removed by BPMN-studio

### ISSUE THREAD

**Issue by R5on11c** [process-engine/bpmn-studio#233]
#### Describe your issue

The Camunda Modeler adds `xsi:type` within certain tags (`<di:waypoint>`).

When exporting any bpmn, BPMN-studio removes these `xsi:type` properties /
doesn't generate them to begin with. So even when xsi:type is included in an already
existing bpmn file, it will be gone when imported and exported in BPMN-studio.

Also, in self closing tags there is a space right before the slash in bpmn files created
by the Camunda Modeler, in BPMN-studio this is not the case. Something to consider.

#### How can others reproduce the issue?

Import and export any bpmn in Camunda Modeler and PMN-studio and compare the
results.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
@R5on11c Could you please provide a diagram that contains the tags mentioned?

**Comment by Paulomart** [comment]
There seems to be a upstream issue for exactly this, but it was resolved a long time ago: https://github.com/bpmn-io/bpmn-moddle/issues/3

**Comment by Paulomart** [comment]
https://github.com/bpmn-io/moddle-xml/blob/master/lib/write.js#L742

**Comment by Paulomart** [comment]
I found out that the `xsi:type` is read by the `moddle-xml` reader, but not written by it. This is caused by an `if` condition. Sadly I dont have a clue how to turn this condition to true.

**Comment by cmg-dev** [comment]
@Vyperus @alexanderkasten @SteffenKn 

Whats the status on this one?

Please close if obsolete.
