### ISSUE TITLE
🔍UX Review with Rene

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#234]
## Describe your issue

We want to execute an UX review, together with René.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
UX/UI Reviews are now happening every week, (Friday 11:00).
