### ISSUE TITLE
Importieren eines Prozesses überschreibt nicht die ID des Prozesses, “in den man rein importiert”

### ISSUE THREAD

**Issue by R5on11c** [process-engine/bpmn-studio#237]
#### Describe your issue

Wenn man einen Prozess importiert, wird nicht die ID des Prozesses überschrieben in dem der
andere Prozess importiert wurde. Das führt dazu, das die ID des alten Prozesses in den neuen
exportiert wird ohne das der Benutzer das weiss.

#### How can others reproduce the issue?

- Irgendeinen beliebigen Prozess erstellen oder bearbeiten
- Einen anderen Prozess importieren
- Den Prozess exportieren
- Das exportierte BPMN inspizieren und sehen das die ID und Referenz des Prozesses nicht stimmt.

#### Possible solution

Beim Importieren sollte die Prozess ID und Referenz mit importiert werden und / oder der komplette
Import eines bpmn Diagramms gesondert stattfinden. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
@alexanderkasten Do you think this is done with the changes in: https://github.com/process-engine/bpmn-studio/pull/243 ?

**Comment by alexanderkasten** [comment]
@Vyperus No

**Comment by alexanderkasten** [comment]
@SteffenKn Kannst du die Funktionalität, die auf der Processdef-List benutzt wird hier auch anwenden ? Das würde das Problem doch lösen oder ?

**Comment by Vyperus** [comment]
Der Import-Process-Button auf der Detail-Ansicht eines Prozesses ist heute nach Absprache mit @cmg-dev entfernt worden. In der neuen Funktionalität von @SteffenKn in der Listen-Ansicht kommt dieser Fehler nicht mehr vor.
