### ISSUE TITLE
favicon.ico not showing in firefox

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#244]
#### Describe your issue
Firefox does not load the favicon.ico.
EDIT: It works with `au run` or opening the index.html manually.  It also works with `npm start` and a different ico file. It's somehow the combination of `node-http-server` and that specific .ico-file.

#### How can others reproduce the issue?
Start the application with npm start, open `localhost:8080` with latest Firefox.

#### What's your setup

OSX, Firefox, not the electron app.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
Can't reproduce this issue, with Firefox 59.0.2 (64-Bit) it works for me.
is it still the case? @LeoTT

**Comment by LeoTT** [comment]
Odd, works now.
