### ISSUE TITLE
Erstellen eines Setups zum testen der Electron App auf Windows

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#253]
#### Describe your issue

Es soll eine Anleitung zum testen des BPMN-Studios auf Windows erstellt werden.

Zum Beispiel mit folgendem Inhalt: 
- Wo liegt eine Windows VM?
- Wie sind die Zugangsdaten? 
- Wie baue ich die Windows App?

Gegebenenfalls soll das Testformular für den Windows Fall angepasst werden, oder ein extra Testformular für Windows erstellt werden.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Ok I managed to get this working, I will provide the Information you asked for in apropriate way.
