### ISSUE TITLE
Firefox: xml-view does not scroll to bottom

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#265]
#### Describe your issue
xml-view does not scroll to the bottom of the file(only in firefox, it's fine with chrome). Happens in #242 
<img width="856" alt="screen shot 2018-04-24 at 16 53 18" src="https://user-images.githubusercontent.com/21304781/39195408-12e856e2-47e0-11e8-8ebc-abd55d0aeaf4.png">

#### How can others reproduce the issue?

Start application with `npm start` and go to `localhost:8080` with latest Firefox version.
Open xml view of any diagram.

#### What's your setup

Firefox

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
on current develop branch it works on chrome, firefox and safari
