### ISSUE TITLE
Default Flow allows condition

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#269]
#### Describe your issue
At the current state, you can change the property of a flow from a normal to a so called `default flow`.

Per definition, a default Flow (or Path) is always taken, when there is no other path, that a token could take. 

An example might be a xor split, where no condition matches the actual token value. In this case, the token would take the path of the default flow. You can compare this with some sort of `default` in a `switch ... case` statement. 

In the current implementation, you can assign a condition to the default flow, which breaks the bpmn specification. 

![screen shot 2018-04-26 at 17 12 35](https://user-images.githubusercontent.com/38498731/39314651-0bbf92fe-4975-11e8-9ecd-982518e94264.png)

#### How can others reproduce the issue?
* Select the flow on click on the wrench
* In the menu, click on "default Flow"
<img width="694" alt="screen shot 2018-04-26 at 17 07 34" src="https://user-images.githubusercontent.com/38498731/39314368-5fc777fa-4974-11e8-9b7b-eb962160d561.png">

#### Possible solution
Remove the option to set a default flow. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:
- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
The Solution would be to not allow a condition on a default flow. I will look into this.

**Comment by robpal94** [comment]
Does (or will) the process-engine Backend support this feature?

**Comment by ppoetschke** [comment]
Default flows are not supported yet by the PE imho. But they should be.
