### ISSUE TITLE
Validation for input formats (PropertyPanel) 

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#277]
#### Describe your issue

We need to check whether the format in an input field is valid to prevent bugs in the backend.
For example the timer-events should have the ISO 8601 format.
https://docs.camunda.org/manual/7.6/reference/bpmn20/events/timer-events/

#### Possible solution

The validation can be done with regex.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
Other then the camunda modeller, which blindly allows any input in the timespan field (as long the input contains at leas one character), BPMN Studio should notify the user that an entered timestamp or timespan, which does not conform the iso8601 format, is invalid.

**Comment by cmg-dev** [comment]
@alexanderkasten We can close this right?

**Comment by robpal94** [comment]
The ProcessEngine still gets confused, when specifying TimerDefintion format, which does not represents the ISO 8601 Format. 

IMO, it would be pretty nice, if the user gets some kind of mask, rather then struggling around with some more complicated `ISO` Formats.
