### ISSUE TITLE
♻️ Fonts Shall be in One Folder

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#284]
#### Describe your issue

Fonts are currents distributed in several folder.

```
bootstrap/fonts/
font-awesome/fonts/
fonts/
(...)
```

#### How can others reproduce the issue?

Find the folders.

#### Possible solution

Move the fonts to only one folder.
Adjust the aurelia.json.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
it also needs to be adjusted in the aurelia.json

**Comment by cmg-dev** [comment]
@alexanderkasten fair point.

I added it to the "Possible Solution" section.

**Comment by alexanderkasten** [comment]
It isn't possible to move all fonts to only one folder.
The css files of bootstrap/fontawesome needs exactly their path (bootstrap/fonts, @fortawesome/font-awesome

**Comment by SteffenKn** [comment]
Since @alexanderkasten said this is not possible, Im going to close this.
