### ISSUE TITLE
🔍Analyze why using node-http-server instead of http-server

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#286]
#### Describe your issue

It would be nice to know why using node-http-server instead of http-server

#### Possible solution

1. Have a look at https://www.npmjs.com/package/http-server & https://www.npmjs.com/package/node-http-server

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Uses `pushserve` now instead of either package.
