### ISSUE TITLE
Browser search function cmd-f overwritten (same for copy/paste)

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#291]
#### Describe your issue

Some might call this a feature, up for discussion.
I personally find it annoying when web applications overwrite browser functions(like `cmd-s`, `cmd-f` or rightclick). 

The bpmn studio overwrites `cmd-f` and `ctrl-f` for a `find` function of the diagram. 
In my case I wanted to search a specific tag in the xml view, using the browsers search ( 
which does not work because of this. #289 )

If this is a wanted feature you might want to add `cmd-s` for saving diagrams.

EDIT: same problem for `cmd-c` and `cmd-v`, which is even worse, because that affects electron too.

#### How can others reproduce the issue?

Use `cmd-f` in diagram view/xml view.

#### Possible solution

Use keyboard shortcuts only for electron app. 
Add button in toolbar for camundas diagram search.

#### What's your setup

OSX(not tested with windows/linux, which is different because of ctrl instead of cmd), Firefox(tested for chrome as well, same problem).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
I can search in the Modeler View for the elements, I consider this as done.
