### ISSUE TITLE
♻️ Implement reset.css

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#295]
#### Describe your issue

There is no reset.css in the BPMN-Studio.

#### Possible solution

https://meyerweb.com/eric/tools/css/reset/reset.css

#### What's your setup

Doesn't care.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Since the PR was closed. Can the issue be closed as well?
