### ISSUE TITLE
🐛When Resizing the Browser-Window under a certain width the navbar breaks

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#300]
#### Describe your issue

If the user resizes the browser window to small width, the navbar will "break".
<img width="510" alt="bildschirmfoto 2018-05-14 um 10 09 53" src="https://user-images.githubusercontent.com/17248802/39985464-02ddacb4-575f-11e8-8ecc-7953a60e9d2f.png">

#### How can others reproduce the issue?

Open BPMN-Studio in a Web-Browser, and resize the window.

#### Possible solution

Add a collapsed navbar for small widths.

#### What's your setup

This will happen in every web-browser.
It won't happen in electron, since we have a set minimal Width for the window there.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
I can reproduce this bug.

**Comment by Vyperus** [comment]
I think the best way is to close this issue and open another for refactoring the style of the navbar to be a little more responsive, when this is done we can get rid of the size restriction or at least most of it.
