### ISSUE TITLE
⚡️ The Internal ProcessEngine Runs on the UI Thread!

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#312]
#### Describe your issue

We dont know if the Internal ProcessEngine Runs on the UI Thread.

#### How can others reproduce the issue?

See `electron_app/electron.js`

#### Possible solution

Run the Internal ProcessEngine not on the UI thread.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
I really would have thought, that the process-engine started from `electron.js` and the electron window with the frontend run in different threads (and _maybe_ they do), but adding the following test to the `bin/start.js` of the electron-skeleton does indeed lock up the whole electron window with the spinning wheel of death:

```TypeScript
setTimeout(() => {
  console.log('start');
  let result;
  for (let i = 0; i < 2500000000; i++) {
    result = result + i;
  }
  console.log('end');
}, 10000);
```

**Comment by heikomat** [comment]
ok, i can confirm now that running the process-engine in the main is not the way to go. see `So where do I do CPU intensive work?` from [this blogpost](https://codeburst.io/deep-dive-into-electrons-main-and-renderer-processes-7a9599d5c9e2#7a80):

> I used to think the main process is the ideal place for “heavy lifting” because it wouldn’t block the UI. That’s wrong actually — if you do CPU intensive work in the main process, it’ll lock up all your renderer processes (and give you the infamous beachball on macOS). So CPU intensive tasks should run in a separate process — not an existing renderer with a UI in it (because it’ll lock that UI up) and not the main. The easiest way to do this is with Electron-remote. Electron-remote is pretty awesome and has a renderer process task pool that will split and balance a job across multiple processes.

This confirms: **blocking the main-thread will lock up all render threads!**

**Comment by cmg-dev** [comment]
@Paulomart ist this still the case?

**Comment by Paulomart** [comment]
Yes, there was no progress on this topic since @heikomat's comments.

**Comment by rrrene** [comment]
Nicht mehr anwendbar.
