### ISSUE TITLE
🐛 Problems When Updating BPMN-Studio

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#316]
#### Describe your issue

When updating BPMN-Studio the internal ProcessEngine sometimes stops working.

This because an incompatible data format changed made in the database.

#### Possible solution

Delete all data of the ProcessEngine and start again.

> **Warning:**
>
> Every deployed diagram will be lost after doing this.

**On MacOS**:

`rm -fr ~/Library/Application Support/bpmn-studio/`

ProcessEngine Runtime:
`rm -fr ~/Library/Application Support/process_engine_runtime/databases`
The local database should reside, where you run `npm run electron-start-dev`.

**If this doesn't help you feel free to contact us by sending an e-mail or creating an issue.**

**Comment by roblen45** [comment]
We need  to add instructions for windows

**Comment by SteffenKn** [comment]
Should we keep this open in case that anyone still has not updated from 1.x?
