### ISSUE TITLE
PropertyPanel: bessere Editiermöglichkeit für JSON und andere Werte ermöglichen

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#326]
**Beschreibe das Problem**

Im PropertyPanel müssen teilweise längere Werte hinterlegt werden, wie bspw. Markdown oder JSON-nahe Konstrukte. Das der Nutzer hier nie seinen ganzen Text sehen kann, ist nicht sehr professionell.

Hier wäre es wichtig, eine bessere Editiermöglichkeit für diese Werte zu ermöglichen (bspw. könnte ein Popup einen mehrzeiligen Editor einblenden).

![image](https://user-images.githubusercontent.com/311914/40293588-e6ee1f98-5cd1-11e8-9f3a-28aed1b74786.png)

**Comment by cmg-dev** [comment]
Closing this, as we've moved this to the new feature tracking software.
