### ISSUE TITLE
PropertyPanel: Resizing springt bei Doppelklick nicht auf Standardbreite zurück

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#327]
**Beschreibe das Problem**

In den meisten Desktopanwendungen kann der Nutzer mit einem Doppelklick ein Resizing optimieren oder auf einen Standardwert zurücksetzen (siehe Excel, Photoshop, aber auch JIRA).

**Comment by cmg-dev** [comment]
This has been implemented. 

Double click the window border will trigger an action.

**Comment by rrrene** [comment]
> This has been implemented.

Kannst du kurz den Commit (oder einfach die Code-Stelle) verlinken, wo das passiert ist?
