### ISSUE TITLE
UI allgemein: Outlines dezenter gestalten oder entfernen

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#331]
**Beschreibe das Problem:**

Die Outlines, welche beim Fokussieren eines Elements gezeichnet werden sind noch sehr browser-ähnlich und durch die blaue Farbe auffällig. Sie sollten entweder dezenter gestaltet werden, so dass der User eine visuelle Rückmeldung bekommt, dass er das Textfeld selektiert hat oder ganz entfernt werden.

**Comment by SteffenKn** [comment]
Ich finde aktuell keine browser-ähnlichen Outlines mehr finden, daher schließe ich das Issue.
