### ISSUE TITLE
UI allgemein: Wofür ist der „Navigate back“-Button gedacht?

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#333]
**Beschreibe das Problem:**

Der Back-Button wirkt auf mich irgendwie "fremd" und deplaziert im Bedienkonzept, daher die ernstgemeinte Frage: Wofür ist der „Navigate back“-Button gedacht?

![image](https://user-images.githubusercontent.com/311914/40294234-09ed4aa2-5cd5-11e8-81d7-bf8c4babd837.png)

**Comment by cmg-dev** [comment]
Dieser hat *eigentlich* die Funktion, von sub-process-calls zurück zu springen.

Beispiel wäre das:

1. Diagramm 1 hat Sub-Process-Call auf Diagramm 2.
1. Auf das Shape in Diagram 1 kann ich einen Doppelklick machen und komme zu Diagramm 2.
1. Der Zurück-Knopf, würde mich wieder zu Diagram 1 bringen.

@rrrene 
A1: Ja, wir brauchen den Button.

Q1: Wie wäre es denn besser platziert?

**Comment by SteffenKn** [comment]
Im Termin mit Rene wurde der Vorschlag genannt den Back Button auf dem Modeler oben mittig zu platzieren in einer Ansicht die auch den Prozessnamen anzeigt, auf den man zurückkehren würde.
