### ISSUE TITLE
UI allgemein: inkonsistentes UI - verschiedene Aktionen, um einen Prozess bearbeiten

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#335]
**Beschreibe das Problem:**

Stichwort inkonsistentes UI: Zur Bearbeitung eines Prozesses sind in verschiedenen Teilen des Studios verschiedene Aktionen nötig.

Manchmal muss der Nutzer auf den Namen eines Prozesses klicken, um einen Prozess bearbeiten zu können und manchmal ist der Name nicht klickbar, sondern es gibt einen Button „Details“.

Hier schön in der gleichen Ansicht zu sehen:

![image](https://user-images.githubusercontent.com/311914/40294377-9c291f04-5cd5-11e8-8068-0fd66348b509.png)

**Comment by SteffenKn** [comment]
Der Details Button existiert nicht mehr. Entweder man geht in die Think View und klickt auf den Prozess oder man klickt auf den Prozessnamen im Solution Explorer.
Daher sehe ich das Issue als geschlossen an. Falls ich das falsch sehe kann das Issue wieder geöffnet werden.
