### ISSUE TITLE
Fenstertitel: inkonsistente UI - Fenstertitel fehlt in allen Ansichten außer Design

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#339]
Stichwort inkonsistente UI: Der Fenstertitel fehlt in allen Ansichten außer "Design".

![image](https://user-images.githubusercontent.com/311914/40295688-9277189e-5cda-11e8-86d7-635bd2980b3c.png)

**Comment by Vyperus** [comment]
This is now also visible at the "inspect-view", I think this is rendering this issue obsolete.
