### ISSUE TITLE
Process Solution Explorer: Click-Targets sind zu klein

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#343]
**Beschreibe das Problem:**

Die Click-Targets der einzelnen Prozesse sind zu klein (sie beschränken sich auf den Text des Namens, anstatt dass der Nutzer die ganze Zeile klicken kann).

Einfach gesprochen: Ich möchte auf Höhe des Namens ganz rechts im Explorer klicken und den Prozess auf der Höhe öffnen:

![image](https://user-images.githubusercontent.com/311914/40296286-84d45b50-5cdc-11e8-88bd-8384a79d50f0.png)

**Comment by Vyperus** [comment]
Closed with #437
