### ISSUE TITLE
Solution Explorer: Breite nicht veränderbar

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#344]
**Beschreibe das Problem:**

Der Solution Explorer ist in seiner Breite nicht veränderbar.

**Comment by Paulomart** [comment]
Will this be added or not?

**Comment by alexanderkasten** [comment]
@Paulomart Maybe someday

**Comment by Paulomart** [comment]
Why was the issue then closed? I think this would be really useful.

**Comment by alexanderkasten** [comment]
@Paulomart Because it is labeled with `Triage Prio 2` and we closed all of them. 
This issue was opened since 21th May 2018 and nothing happened.
