### ISSUE TITLE
Notifications generell reflektieren

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#349]
**Beschreibe das Problem:**

Notifications z.B. beim Verlassen von Dialogen oder Speichern von Diagrammen erscheinen überflüssig.

Das gilt sowohl für den Erfolgsfall und die analoge Notification.

Hier ein veraltetes (!) Beispiel:

![image](https://user-images.githubusercontent.com/311914/40297214-50a97dee-5cdf-11e8-9d07-50f432125d1b.png)

**Comment by Paulomart** [comment]
Is this fixed?

**Comment by alexanderkasten** [comment]
@Paulomart  No
