### ISSUE TITLE
Leinwand: auf Mac panning und zooming mit Fingergesten ermöglichen (aktuell werden nur Mausrad-Gesten unterstützt)

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#351]
**Beschreibe das Problem:**

Das Rein- und Rauszoomen geschieht bei BPMN.io scheinbar per Mausrad. 

Auf dem Mac führt dieses Verhalten dazu, dass ich mit zwei Fingern nicht, wie sonst üblich, die Leinwand verschieben (panning) kann.

Dies wären aus meiner Sicht sehr sinnvolle Produktivitätserweiterungen die wir, sollte diese Funktionalität noch nicht existieren, auch sehr gut zurück-contributen könnten. :+1:

 **Update:** Ich kann mit der "zwei Finger auseinander ziehen"-Geste zoomen. Das Beschriebene wäre eine sinnvolle Ergänzung hierzu.

**Comment by rrrene** [comment]
Hier ist das Feature drin, dass man mit zwei Fingern die Leinwand bewegen kann: https://demo.bpmn.io/new

**Comment by alexanderkasten** [comment]
Wir nutzen aktuell noch bpmn-js Version 0.25.0.
Es gibt schon eine 2.0.1 Version, wahrscheinlich ist die Funktionalität da mittlerweile automatisch mit drin.
