### ISSUE TITLE
Dashboard: TaskList: Was passiert hier?

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#356]
**Beschreibe das Problem:**

Der Nutzer kann in die Taskliste wechseln und findet diese leer vor.

Er hat keine Möglichkeit zu verstehen, wofür diese Ansicht gut ist.

Daher die ernstgemeinte Frage: Was passiert hier?

![image](https://user-images.githubusercontent.com/311914/40298295-fd395dba-5ce2-11e8-894a-57d362cda851.png)

**Comment by cmg-dev** [comment]
This is obsolete.
