### ISSUE TITLE
Dashboard: ProcessInstanceList: Was passiert hier?

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#357]
**Beschreibe das Problem:**

Der Nutzer kann in die Prozessinstanzliste wechseln und findet diese leer vor.

Er hat keine Möglichkeit zu verstehen, wofür diese Ansicht gut ist. Sogar ich habe, obwohl ich mit den Konzepten vertraut bin, Schwierigkeiten zu verstehen, was ich als Nutzer in dieser Ansicht tun soll ...

Daher die ernstgemeinte Frage: Was passiert hier?

![image](https://user-images.githubusercontent.com/311914/40298359-2f2d359e-5ce3-11e8-85e1-3569f05d5191.png)

**Comment by SteffenKn** [comment]
Ich denke dieses Issue wird gelöst sobald das Dashboard anstatt die Prozessinstanzen nur noch Tasks anzeigt.

**Comment by cmg-dev** [comment]
This is obsolete.
