### ISSUE TITLE
Dashboard: ProcessInstanceList: Was bedeuten die States?

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#358]
**Beschreibe das Problem:**

Welche Bedeutung haben die States in der Prozessinstanzliste?

Hier wäre ein Hilfe-Icon mit erklärendem Popover hilfreich.

![image](https://user-images.githubusercontent.com/311914/40298438-7188848e-5ce3-11e8-814a-142d0484f5a3.png)

**Comment by SteffenKn** [comment]
Den State gibt es in der aktuellen Prozessinstanz Liste nicht mehr. Außerdem werden nur noch die laufenden Prozesse angezeigt.
