### ISSUE TITLE
UX allgemein: viele Beschriftungen wirken wie Variablen- oder Datenbank-Namen

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#359]
**Beschreibe das Problem:**

In vielen Ansichten sprechen die Beschriftungen nicht die Sprache des Benutzer von BPMN Studio, sondern die des 5Minds-Programmierers, der am Studio arbeitet.

Begriffe wie `ProcessDefinitionKey` richten sich mit Sicherheit nicht empathisch an den Junior-Prozessberater, der BPMN Studio bedient.

![image](https://user-images.githubusercontent.com/311914/40299371-517c710c-5ce6-11e8-970d-59f30ef39990.png)

**Comment by Vyperus** [comment]
After reviewing this I only found this "very" technical columns in places where they absolutely necessary. I will close this for now.
