### ISSUE TITLE
UX allgemein: Beispielprozesse - Sinn nicht ersichtlich; Beispielprozesse aus Doku fehlen

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#361]
**Beschreibe das Problem:**

Der Sinn der Beispielprozesse "Prozess erstellen" und "Prozess löschen" erschließt sich dem Endnutzer überhaupt.

**Die Beispielprozesse aus der Doku fehlen gänzlich** und müssen vom interessierten Nutzer ernsthaft abgetippt werden.

Die Tatsache, dass meiner Erinnerung nach der "Prozess erstellen"-Prozess tatsächlich zum Erstellen von Prozessen innerhalb von BPMN Studio verwendet wird, wird (a) nicht kommuniziert, ist (b) eher ein internes Gimmick und hebt (c) die oben beschriebene Verwirrung um fehlende "Hello World"-Besipielprozesse keinesfalls auf.

**Comment by ppoetschke** [comment]
M.E. müsste hier der Zugriff auf interne Prozesse beschränkt bzw. verhindert werden, also Prozesse, die für die Funktion von BPMN-Studio essentiell sind und von den Entwicklern von Studio und nicht von Endanwendern erstellt wurden.

**Comment by SteffenKn** [comment]
Die "Prozess erstellen" und "Prozess löschen" Prozesse gibt es nicht mehr.
Ich denke dieses Issue wäre am besten und am vollständigsten gelöst, wenn wir die fertigen Beispiel Prozesse aus der Doku heraus herunterladbar machen würden.
