### ISSUE TITLE
Statusbar: „Connected to“-Info - Icon anstatt Text nutzen

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#367]
**Beschreibe das Problem:**

Der Mehrwert der  „Connected to“-Info in der Statusbar für den Endnutzer erscheint nicht ersichtlich.

Dies gilt insbesondere da ein Klick auf diese Info keine Informationen zur aktuellen Verbindung zur ProcessEngine liefert, sondern den Settings-Dialog öffnet und die aktuellen Änderungen am Diagramm (wie #363 beschrieben) verwirft.

**Comment by rrrene** [comment]
Nach Besprechung mit @moellenbeck wird der Mehrwert klar.

Wäre dafür, das Ganze analog zur Git-Branch-Angabe in VS Code, etwas knackiger zu gestalten: 

![image](https://user-images.githubusercontent.com/311914/40598146-5cc316f0-6246-11e8-9846-485008c13845.png)

**Comment by rrrene** [comment]
Leider wurde dieser Kommentar von @cmg-dev nicht vollständig umgesetzt: https://github.com/process-engine/bpmn-studio/pull/448#discussion_r191236624

1. Bitte das Plug-Icon entfernen.
2. [Diese Zeile fixen](https://github.com/process-engine/bpmn-studio/blob/826b1cd0671c22b55afa2fa9c4a448ec6aa1d2d6/src/modules/status-bar/status-bar.ts#L49) - wie passiert es, dass so ein Build-Warning auf `develop` nicht auffällt?

**Comment by SteffenKn** [comment]
Bzgl. 2.:
Das Rückgängig machen [dieses Commits](https://github.com/process-engine/bpmn-studio/pull/448/commits/a4fb494f0933c1dfb6b3d5d9d8b787b169206581) fixt den Bug.
