### ISSUE TITLE
Dateimanagement: keine „Datei speichern“-Funktionalität

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#370]
**Beschreibe das Problem:**

Es gibt keine klassischen „Datei speichern“-Funktionalität (CMD+S), die den Nutzer auf authentische Weise mit dem lokalen Dateisystem und seinen hier gespeicherten Prozessen interagieren lässt.

**Comment by Vyperus** [comment]
This was implemented a long time ago. CMD+S for macOS and Strg+S on Windows are working now.
I will close this for now.
