### ISSUE TITLE
PropertyPanel: Unklarer Bezeichner in Form Fields UI

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#376]
**Beschreibe das Problem:**

Gerade beim Erstellen von #375 aufgefallen: Was bedeutet `YW` im Kontext der Form Fields?

![image](https://user-images.githubusercontent.com/311914/40301344-1f113d78-5cec-11e8-9253-98a40042b770.png)

**Comment by Vyperus** [comment]
Closed with https://github.com/process-engine/bpmn-studio/commit/e0dedb06ad6f4171a9e1c1fbcea797b2a8c05630
