### ISSUE TITLE
Werkzeugleiste links: Distribute Elements Horizontally - Tooltip falsch

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#378]
**Beschreibe das Problem:**

Das Werkzeug "Distribute Elements Horizontally" hat den Tooltip "Distribute Elements Vertically".

![image](https://user-images.githubusercontent.com/311914/40324033-8625eeaa-5d37-11e8-8dcd-ff1db0da0020.png)

**Comment by Vyperus** [comment]
Closed in #433
