### ISSUE TITLE
Werkzeugleiste links: Tools sind Buttons mit Opacity anstatt Icons mit grauer Farbe

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#379]
**Beschreibe das Problem:**

Bei den Tools wird mit Opacity anstatt mit grauer Farbe gearbeitet, um die Tools auszugrauen.

Dies hat unerwartete Seiteneffekte, die man hätte leicht zu bemerken können, wenn man das Studio selber nutzen oder wenigstens testen würde:

![image](https://user-images.githubusercontent.com/311914/40324099-c9b1b50a-5d37-11e8-93b1-3299ae914a01.png)

**Comment by Vyperus** [comment]
Closed in #433
