### ISSUE TITLE
Werkzeugleiste links: Colorpicker - Dropdown erbt Hover-Effekt vom Eltern-Element

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#380]
**Beschreibe das Problem:**

Der Grund, dass der Colorpicker einen halb durchsichtigen Effekt bekommt, ist, dass das Element den Hover-Effekt seines Elternelements erbt.

Das ist schlicht schlechtes HTML-Design und wäre schnell bei einer qualitativen Endkontrolle des Umbaus der Werkzeugleiste aufgefallen.

![image](https://user-images.githubusercontent.com/311914/40324158-fa6dabea-5d37-11e8-87ba-1a535e1d3760.png)

**Comment by Vyperus** [comment]
Closed in #433
