### ISSUE TITLE
Menu: About-Dialog ist der Standard-Electron-Dialog

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#384]
**Beschreibe das Problem:**

Der: About-Dialog unter "BPMN Studio" / "About BPMN Studio" ist der Standard-Electron-Dialog.

![image](https://user-images.githubusercontent.com/311914/40324846-1829b8b6-5d3a-11e8-8575-d8afad401216.png)

**Comment by Paulomart** [comment]
This is only the case if the application was run using `npm run start-electron-dev`. The production build contains the right dialog:

<img width="396" alt="grafik" src="https://user-images.githubusercontent.com/4148404/40346961-d0d1d13c-5d9e-11e8-8f92-0d41471c27cc.png">

**Comment by rrrene** [comment]
@Paulomart Ah. Da hast du recht :+1:

Dann ist das hier eher ein perspektivisches Issue (wenn überhaupt).

Ich hatte halt gedacht, dass wir da langfristig einen eigenen Dialog machen, der auch unter Windows funktioniert. So à la Adobe:

![image](https://user-images.githubusercontent.com/311914/40353915-eea47598-5db2-11e8-89de-95e77b0ba494.png)

**Comment by Paulomart** [comment]
I think this can be closed now? @rrrene please see #921.

**Comment by Vyperus** [comment]
Sure thing I did miss this in the PR.
