### ISSUE TITLE
UX allgemein: Suche nicht präsent genug

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#386]
**Beschreibe das Problem:**

Ein Suche, wie im Camunda Modeller, die per CMD+F aktiviert wird und das Diagramm durchsucht, fehlt komplett. 
EDIT: Gibt es schon, aber die Suche ist nicht präsent genug.

Aus meiner Sicht ist Feature-Parität mit den Bearbeiten-Komponenten des Camunda Modellers die Voraussetzung zur internen Adaption des BPMN Studios.

![image](https://user-images.githubusercontent.com/311914/40325132-ef1ce712-5d3a-11e8-9cc6-12d17589e9d8.png)

**Comment by cmg-dev** [comment]
Ha! Niemals!

Versuche STRG+F.
