### ISSUE TITLE
UI-Entwicklung: Existieren im Frontend Logs? Wo sind diese einsehbar?

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#390]
**Beschreibe das Problem:**

Gibt es im Frontend eigene Logs? Wo sind diese, bpsw. in der Electron App, einsehbar?

**Comment by cmg-dev** [comment]
Diese sind aktuell NUR in der Developer Konsole einsehbar.

Ich bin mir nicht sicher, ob wir das brauchen und wie wir das bauen würden.

**Comment by rrrene** [comment]
Der Gedanke war, dass es spätestens mit Einführung von Plugins Sinn ergibt, ein Log à la VS Code anzubieten, dass auch direkt in der UI einsehbar ist (heisst dort, glaube ich, "Output").
