### ISSUE TITLE
UI-Entwicklung: Seeds für die Applikation fehlen scheinbar - mit Datenmengen verschiedener Größe

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#391]
**Beschreibe das Problem:**

Während der UI-Entwicklung wäre es für einen professionellen Eindruck sehr hilfreich, wenn der Entwickler das BPMN Studio mit einer Reihe von verschieden großen Prozessen seeden könnte, um tägliche Anwendungsszenarien der Kunden wie bspw. das Bearbeiten großer, verschachtelter Prozesslandschaften und das Bearbeiten vieler kleiner Prozesse nachstellen und vergleichen zu können.

**Comment by ppoetschke** [comment]
@rrrene Könntest Du die Idee dahinter vielleicht etwas näher erläutern? Wir hatten schon vor einiger Zeit dahingehend Überlegungen angestellt, den Anwender mit einfacheren branchenspezifischen Standardprozessen zu unterstützen. MMn. ist die Zielsetzung entscheidend, Beispielprozesse, um die Funktionsweise und Modellierung von Prozessen zu erläutern oder quasi Template-Prozesse, um die Produktivität out-of-the-box zu erhöhen.

**Comment by rrrene** [comment]
> den Anwender mit einfacheren branchenspezifischen Standardprozessen zu unterstützen

Dieses Issue bezieht sich rein auf die UI-Entwicklung und die Unterstützung des Entwicklers.

> Beispielprozesse, um die Funktionsweise und Modellierung von Prozessen zu erläutern

Ich glaube, ich verstehe, was du meinst. Wahrscheinlich geht #361 in diese Richtung?

**Comment by ppoetschke** [comment]
#361 trifft es auch nicht ganz. Ich denke, es wird 3 Arten geben.
- synthetische kleine Prozesse, die für sich genommen kaum Sinn machen, aber bestimmte Aspekte der Modellierung und Parametrisierung verdeutlichen. Da fallen auch die Prozesse für Integration tests darunter und die hier angesprochenen Beispiele.
- Beispiele, die Anwendungsfälle von Prozessen darstellen und sich nicht nur auf die Modellierungsregeln, sondern auch das Zusammenspiel mit Business Logic zeigen, also von Hello World über Face ID, Mailversand bis zu einfachen Bestell- oder Genehmigungsprozessen.
- Für bestimmte Branchen oder Anwendungen fertig modellierte Prozesse, z.B. Urlaubsantragsprozesse, Rechnungsgenehmigungen, Reklamationsbearbeitung, Gesprächsleitfäden für Callcenter etc. Diese Prozesse werden bei Bedarf vom Anwender angepasst und erweitert, können aber massiv die Time-to-deliver der Lösung senken. Es ist aber auch durchaus denkbar, dass diese Template-Prozesse oder -Lösungen Teil eines weiteren kommerziellen Pakets sind.
