### ISSUE TITLE
📝 Document all functional elements

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#393]
## Describe your issue

Documentation about the events in the BPMN Studio is missing entirely.

## How can others reproduce the issue?

search for a document.

## Possible solution

Document all Events and Event Flows.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Wir brauchen definitiv für's Bewerben der PE eine Liste der funktionierenden BPMN-Elemente. @ElRaptorus hatte hier einmal die noch nicht funktionierenden Activities zusammengefasst: https://github.com/process-engine/process_engine_runtime/issues/163
