### ISSUE TITLE
🐛 Creating/Importing a Process Definition destroys the Diagramm when the ProcessKey is identical to the id of any Element

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#399]
#### Describe your issue

Creating or importing a BPMN diagram with a key, that is identical to the id of any existing element, causes an error and the element is removed.

This is because the ID of the process becomes the key that is set when a process definition is created or the name that is set when a diagram is imported.

![duplicate_id](https://user-images.githubusercontent.com/20394992/40363843-fc665534-5dd0-11e8-8489-1792686677a8.gif)

The error message looks like this:

```
Error: duplicate ID <StartEvent_1>
    at error (:9000/scripts/vendor-bundle.js:109538)
    at Context.addElement (:9000/scripts/vendor-bundle.js:109610)
    at ElementHandler.BaseElementHandler.handleNode (:9000/scripts/vendor-bundle.js:109723)
    at ElementHandler.handleChild (:9000/scripts/vendor-bundle.js:109917)
    at ElementHandler.BaseElementHandler.handleNode (:9000/scripts/vendor-bundle.js:109725)
    at handleOpen (:9000/scripts/vendor-bundle.js:110215)
    at :9000/scripts/vendor-bundle.js:110268
    at parse (:9000/scripts/vendor-bundle.js:112587)
    at Saxen.parse (:9000/scripts/vendor-bundle.js:111965)
    at :9000/scripts/vendor-bundle.js:110285
    at :9000/scripts/vendor-bundle.js:99234
```

This happens both when creating a process definition and when importing a process diagram.

#### How can others reproduce the issue?

- Open the BPMN Studio.
- Click on the button "Create Process Definition".
- Choose any name
- Set "StartEvent_1" as key
- Open the detailed view
- Note that there is no start event and an error message.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
💥 ...

**Comment by SteffenKn** [comment]
This is caused by the [process_engine](). This [function](https://github.com/process-engine/process_engine/blob/develop/src/process_engine_service.ts#L222) changes the process id to the parameter "name" when it is valid.

Changing this part (line 235-245):

```
const diagramKey: string = nameIsInvalid ? processes[0].id : name;

if (!nameIsInvalid) {
  const xmlWithCorrectName: string = xml
                                      .replace(`id="${processes[0].id}"`, `id="${name}"`)
                                          .replace(`processRef="${processes[0].id}"`, `processRef="${name}"`);
   await this.processDefEntityTypeService.importBpmnFromXml(context, {name: diagramName, xml: xmlWithCorrectName});
} else {
  await this.processDefEntityTypeService.importBpmnFromXml(context, {name: diagramName, xml: xml});
}
```

to this

```
const diagramKey: string = processes[0].id;
await this.processDefEntityTypeService.importBpmnFromXml(context, {name: diagramName, xml: xml});
```

would fix the issue.

But I am not quite sure if this would have no side effects.

**Comment by SteffenKn** [comment]
This was an issue with the old process_engine. Since we using the process_engine_runtime this will no longer occur.
