### ISSUE TITLE
Weitere WidgetTypen unterstützen

### ISSUE THREAD

**Issue by heikomat** [process-engine/bpmn-studio#4]
Aktuell unterstützt charon folgende Widgets:

- Form
- Confirm

Wir wollen auch folgende untersützen:

- [ ] Checkbox
- [ ] Textbox
- [ ] Dropdown
- [ ] ImportXMLDiagram (Teil von #15)
- Eventuell gibt es noch weitere

Leider gibt es keine Spezifikation für diese Wigets, diese müssen noch geschrieben/gefunden werden.

**Comment by cmg-dev** [comment]
We have integrated this, if it seemed useful to us.
