### ISSUE TITLE
Notification Toaster overlaps control elements

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#428]
#### Describe your issue
Since Version 1.2.1, the control buttons for _save_, _export_ and _execute_ where moved to the right side. 

![screen shot 2018-05-24 at 15 37 36](https://user-images.githubusercontent.com/38498731/40489489-882d11c2-5f69-11e8-9f7f-4a85f8bb4829.png)

A problem is, that they are now overlapped by any incoming toaster notification. This is very annoying if you want to save and execute a process. When you click on save, you have to wait until the notification disappeared if you want to click on the execute button. 

#### How can others reproduce the issue?
* In the bpmn editor, click on _save_
* Try to instantly click another control button

#### Possible solution
* Move the Control buttons back to the left, so that they would not be overlapped by the toaster notification
* Let the user dismiss the notification directly (*without any blocking animation, that takes 0.5 seconds*)
* Dont let the toaster notification block the mouse input. IMO. the Unity Desktop from the operation System Ubuntu handles this very well. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
Die Notifications wären in der Tat besser in der unteren linken Ecke der Leinwand aufgehoben.

Off-topic: Das ist meiner Meinung nach ein Paradebeispiel für eine Situation, in der ich einfach keine Notification erwarte. 

Mir fällt auf Anhieb auch keine einzige professionelle Desktop Software ein, bei der ich auf "Speichern" drücke und anschließend eine Benachrichtigung darüber bekomme, dass ich gespeichert habe. Selbst Google Docs & Co. machen das nicht (was nicht heißt, dass es keinen visuellen Input zum erfolgreichen Speichern gibt, nur eben keine Notification).

**Comment by robpal94** [comment]
Ja, wenn ich so drüber nachdenke gebe ich dir recht. Mir ist auch nie wirklich aufgefallen, dass man eine Benachrichtigung für das erfolgreiche Speichern erhält. 

Allerdings sollte man die Platzierung der Notifications vielleicht trotzdem einmal überdenken, da es ja durchaus auch mal zu Ereignissen kommen kann, bei welchen eine Notification ausgelösst wird. persönlich finde ich es allgemein auch immer etwas unschön, wenn Dinge andere Dinge überlagern.

**Comment by rrrene** [comment]
Ich glaube, wie gesagt, dass links unten auf der Leinwand ein guter Ort ist:

![image](https://user-images.githubusercontent.com/311914/40498747-26bae178-5f80-11e8-98d0-ed9f57ffb4d2.png)

**Comment by rrrene** [comment]
@SteffenKn Die Notification klebt nun links unten in der Fensterecke. Was ich aber meinte, war 

> Die Notifications wären in der Tat besser in der unteren linken Ecke **der Leinwand** aufgehoben.

Mit "die Leinwand" meine ich das weiße BPMN.io-Canvas-Element. Hier eine aktualisierte Skizze:

![image](https://user-images.githubusercontent.com/311914/40598064-cd25b336-6245-11e8-956d-4a8593d39bb7.png)

**Comment by rrrene** [comment]
Hintergrund: Wenn wir unten links in die Werkzeugleiste mal Icons platzieren wollen, überlappen die Notifications wieder Kontrollelemente 😉 

![image](https://user-images.githubusercontent.com/311914/40598087-fbe1d4f2-6245-11e8-8b95-93810dad591d.png)
