### ISSUE TITLE
Form element to define a static label in User Tasks

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#432]
#### Describe your issue
At the current state, it is not directly possible to define a static label in a user task, when using the form editor. The only offered forms are: 
* `string` 
* `long`
* `boolean`
* `date`
* `enum`
* `custom`

It is possible, but then you cant add any other form fields (in my understanding). Also, the method to add a static label is "very hacky" imo and should be simplified. 

#### How can others reproduce the issue?
Try to create a user task, that displays a static label and no other form fields, using the build in form editor.

#### Possible solution
Add an option to define a new static label to the form editor.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This can be done when using the confirm widget.
