### ISSUE TITLE
⬆️ Font Awesome Updaten

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#453]
#### Describe your issue

Font Awesome is not up to date.
For that reason, some icons don't look like they should:

| BPMN-Studio | fontawesome.com |
| ----------- | --------------- |
| <img width="70" alt="plug" src="https://user-images.githubusercontent.com/20394992/40620469-356ce088-6299-11e8-9a55-680df9fcbd34.png"> | <img width="70" alt="plug" src="https://user-images.githubusercontent.com/20394992/40620503-55ac7f8e-6299-11e8-888b-abf9b97d1e41.png"> |
| <img width="70" alt="lock" src="https://user-images.githubusercontent.com/20394992/40620529-6aca3fb4-6299-11e8-9e31-e11ac69dfb13.png"> | <img width="70" alt="lock" src="https://user-images.githubusercontent.com/20394992/40620564-87a4aebc-6299-11e8-8249-75489d3da871.png"> |

#### Possible solution

Update Font Awesome.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I think this is because we are using 4.x and the newest version is 5.x
