### ISSUE TITLE
♻️Refactor Usage of direct references of HTML elements in the view-model

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#455]
Currently we are using a direct reference of HTML elements to control the behaviour of certain elements.

In most cases this is not the best way to solve the problem at hand and it needs to be refactored.

In detail:

We need to localize any occurence of things like:

`<div class="djs-palette-container tool-list tool-list--vertical" ref="paletteContainer">`

Then find out why we need the direct reference like "paletteContainer" and eventually refactor it.
In this case a component which displays and handles the logic behind this palette would be sufficient.

**Comment by rrrene** [comment]
> Momentan nutzen wir direkte Referenzen auf HTML-Elemente, um das Verhalten bestimmter Elemente zu kontrollieren. In den meisten Fällen ist dies nicht der beste Weg, ein gegebenes Problem zu lösen und es muss daher geändert werden.

Wir müssen solche Issues definitiv konkreter formulieren! Ich war heute morgen ja bei der initialen Diskussion dabei, aber wahrscheinlich könnte ich schon morgen nicht mehr sagen, was hier zu tun ist.

**Comment by cmg-dev** [comment]
This is actually a good way to do this in a View-Model scenario!

Aurelia will encapsulate the referenced call to the element. This is very neat!

Keep this.
