### ISSUE TITLE
Aurelia: Repeater sauberer einsetzen

### ISSUE THREAD

**Issue by rrrene** [process-engine/bpmn-studio#457]
**Beschreibe das Problem:**

Wir produzieren regelmäßig leere DIVs durch folgende Konstruktion (man beachte, dass die unteren beiden DIVs keinen Klassen oder andere Attribute besitzen):

```html
<div class="index-tab">
  <div repeat.for="section of sections">
    <div if.bind="section.canHandleElement">
```

Dies wäre besser durch 

```html
<div class="index-tab">
  <template repeat.for="section of sections">
    <template if.bind="section.canHandleElement">
```

sauberer gelöst.

[Aurelia Doku zu Templating Basics](https://aurelia.io/docs/templating/basics#repeaters)

[Original-Kontext der Diskussion mit @cmg-dev](https://github.com/process-engine/bpmn-studio/pull/445#discussion_r191807610)

**Comment by LeoTT** [comment]
Hier ist eine Liste von Stellen wo Template besser wäre. Umfasst nur klassenlose divs mit `if.bind` oder `repeat.for`. 

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/form-widget/form-widget.html#L4

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/forms/sections/basics/basics.html#L49

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/general/sections/basics/basics.html#L18

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/general/general.html#L5

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/general/general.html#L6

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/general/sections/pool/pool.html#L24

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/property-panel.html#L4

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/form-widget/form-widget.html#L3

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.html#L10

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/navbar/navbar.html#L60

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/navbar/navbar.html#L65

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/process-list/process-list.html#L5

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/process-list/process-list.html#L32

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-list/processdef-list.html#L9

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-list/processdef-list.html#L50

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-start/processdef-start.html#L6

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-start/processdef-start.html#L12

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/forms/forms.html#L6

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/property-panel/indextabs/general/general.html#L6

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/status-bar/status-bar.html#L14

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/task-dynamic-ui/task-dynamic-ui.html#L7

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/task-dynamic-ui/task-dynamic-ui.html#L12

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/task-list/task-list.html#L31
