### ISSUE TITLE
♻️Refactor Private Member Names in bpmn-io.ts

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#463]
## Describe your issue

Obvious. Have a look at bpmn-io.ts.

## How can others reproduce the issue?

Look.

#### Possible solution

Rename with `_` Prefix.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This will be done in this PR: https://github.com/process-engine/bpmn-studio/pull/434
