### ISSUE TITLE
Enable no-any rule again

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#469]
#### Describe your issue

At the moment the `no-any` rule is disabled and the `typedef` rule is enabled.
This forces developers to use `any` where no type is better.
EDIT: I don't mean to encourage using no type, but if in doubt it is the lesser evil.

#### 1. Because you lose the ability to express that you actually mean *anything* as a type
```ts
// is this function able to log anything? or is the expected type just unknown? who knows?
function log (anything: any): void {
...
}
```

#### 2. Because you kill type inference
```ts
// this is correct but annoying
const options: {
    host: string,
    port: number,
    userName: string,
    password: string,
} = {
    host: 'localhost',
    port: 8912,
    userName: 'admin',
    password: 'admin',
}

// this looks a bit better, but type information lost -> properties no longer known
const options: { 
 [index: string] : string | number,
} = {
    host: 'localhost',
    port: 8912,
    userName: 'admin',
    password: 'admin',
}

// absolute typeloss -> this is currently encouraged by tslint settings
const options: any = {
    host: 'localhost',
    port: 8912,
    userName: 'admin',
    password: 'admin',
}

// type inference gets type
const options = { // tslint:disable-line:typedef
    host: 'localhost',
    port: 8912,
    userName: 'admin',
    password: 'admin',
}
```
I prefer the last example. This does not mean I would get rid of the `typedef`rule, I just think it's reasonable to disable tslint for it sometimes.

#### Possible solution

Remove the expection from `tslint.json`.

Replace occurences of `any` with actual type or (if not possible) with no type + `tslint-disable-line`.

Here is a list of the occurences(59):
https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/app.ts#L7

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts#L10

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/IBpmnModdle.ts#L6

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/IBpmnModeler.ts#L4

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/IBpmnModeler.ts#L8

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/IBpmnModeler.ts#L9

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/IBpmnModeler.ts#L11

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/bpmnmodeler/IModeling.ts#L5

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/choose-dialog/IChooseDialogOption.ts#L3

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/eventbus/IEventBus.ts#L5

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/eventbus/IEventBus.ts#L8

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/eventbus/IEventBus.ts#L13

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/eventbus/IEventBus.ts#L16

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/eventbus/IEventBus.ts#L20

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/contracts/processengine/IErrorResponse.ts#L2

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/main.ts#L21

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/main.ts#L64

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/main.ts#L69

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/authentication/authentication.service.ts#L65

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/bpmn-io/bpmn-io.ts#L46

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/bpmn-io/bpmn-io.ts#L93

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/bpmn-io/bpmn-io.ts#L94

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/bpmn-io/bpmn-io.ts#L210

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/bpmn-io/bpmn-io.ts#L233

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/choose-dialog/choose-dialog.ts#L9

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/config-panel/config-panel.ts#L19

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/confirm-widget/confirm-widget.ts#L6

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/confirm-widget/confirm-widget.ts#L8

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/dynamic-ui/dynamic-ui.service.ts#L20

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L12

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L18

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L23

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L32

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L45

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L47

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L93

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L111

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/import-process-button/import-process-button.ts#L125

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-detail/processdef-detail.ts#L124

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-detail/processdef-detail.ts#L167

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-detail/processdef-detail.ts#L177

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-detail/processdef-detail.ts#L235

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-list/processdef-list.ts#L80

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-list/processdef-list.ts#L230

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processdef-start/processdef-start.ts#L76

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processengine/processengine.repository.ts#L30

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processengine/processengine.repository.ts#L67

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/processengine/processengine.repository.ts#L110

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/waiting-room/waiting-room.ts#L21

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/modules/waiting-room/waiting-room.ts#L29

https://github.com/process-engine/bpmn-studio/blob/3aa9d7177391cde4e1b14162bf0f92dee26e0f3e/src/resources/http-repository-tools.ts#L3

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
I definitely would prefer the 4th option:

```ts
interface IDatabaseConfig  {
    host: string,
    port: number,
    userName: string,
    password: string
};

--- 

const options: IDatabaseConfig = {
    host: 'localhost',
    port: 8912,
    userName: 'admin',
    password: 'admin'
}
```

Pros: 

1. We have a name for the construct.
1. Typings work as desired.

Cons:

1. We have to find a **good** name (this is hard).
1. We have to find a nice place for those interfaces.

@LeoTT @5ebastianMeier What do you think?

**Comment by LeoTT** [comment]
I like that approach, but I also agree that finding a suitable name and place for interfaces will be a bit of work.

Coming with TS 3.0 there will be another option: [the unknown type](https://blogs.msdn.microsoft.com/typescript/2018/07/12/announcing-typescript-3-0-rc/#the-unknown-type)
Widespread usage of that should not be desirable, but it describes exactly the thing that `any` is being used for now (and should not imo).

**Comment by 5ebastianMeier** [comment]
The `unknown` type is definitely something I'd want to use more often, because it forces typecasts where `any` just allows any usage you desire.

I would also prefer the 5th option.

This will get used in conjunction with a direct method call quite a lot, where you just assign a parameter to a variable to have a more elegant and self explanatory method call.

In those cases it might happen that we have to import an interface type as a type annotation although we didn't need to, because type inference can resolve the type for us from another package.

Imagine the following:

```
import {IMyInterface} from 'my_contracts';

export class Example {
   public initialize(): void {
      const someComplexArgument: IMyInterface = {
         a: 'a',
         b: 'b',
         c: 'c',
         d: 'd',
         e: 'e',
      };
      this.myService.someMethod(someComplexArgument);
   }
}
```

It doesn't get more type safe through this usage and we have an extra import on the top.

In my private projects I currently experiment with type inference wherever possible and it results in much cleaner code.

The upside of type annotations is that is can make reviews easier when done on GitHub. Without IntelliSense and other fancy tools, you lose some information that might help to understand the code better or identify errors.

I believe this is the minority of cases, but you be the judge.

This form - with or without the extra type annotation - is the one I prefer. If we can find a new take on where and how we want to use type annotations: so much the better.
