### ISSUE TITLE
🐛 Doppelklick geht nur, wenn Studio noch nicht offen ist.

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#498]
Ein Doppelklick importiert ein Diagram nur, wenn das Studio noch nicht offen ist.

Neueste Version.

**Comment by alexanderkasten** [comment]
Edit: Passiert nur auf MacOS

**Comment by SteffenKn** [comment]
Unter Windows wird einfach ein 2. Fenster geöffnet. Ist das das gewünschte Verhalten oder sollte hier auch das Diagramm im gleichen Fenster geöffnet werden?
