### ISSUE TITLE
Layout of icons(start & print) in menu bar breaks

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#499]
#### Describe your issue

When you make the screen smaller, the layout of the start and print icons break.
They are supposed to be next to each other, not stacked.

<img width="207" alt="screen shot 2018-06-19 at 09 26 35" src="https://user-images.githubusercontent.com/21304781/41582878-1b45076a-73a3-11e8-9ce9-a0ac8a87c4ac.png">

EDIT: Field for user also has layouting problems (goes to bottom of menu bar). Seems related.
<img width="288" alt="screen shot 2018-06-19 at 09 53 28" src="https://user-images.githubusercontent.com/21304781/41584129-c33020ba-73a6-11e8-93cc-85a24dcc34cb.png">

#### How can others reproduce the issue?

Open studio, make screen smaller.

#### What's your setup

Tested with chrome & firefox, same bug for both.
#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Seems to be the same bug as #300

**Comment by LeoTT** [comment]
Not quite. In that issue the window is resized to a point where the elements don't fit and a different layout would be necessary.
Just tested the bug I have, breaks at 1110px width for me, plenty of space technically.

**Comment by SteffenKn** [comment]
Ok i will have a closer look at this
