### ISSUE TITLE
🐛 When Changing the Diagram via the Process Solution Explorer While Editing the Text of Any Element, the Text Field Will Still Be Displayed.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#500]
#### Describe your issue

When changing the Diagramm via the Process Solution Explorer while editing the text of any element, the text field will still be displayed:
![textbox bug](https://user-images.githubusercontent.com/20394992/41586150-532abd7e-73ac-11e8-9d11-62f681c198dc.gif)

#### How can others reproduce the issue?

- Open up the BPMN-Studio
- Go to the Detail View
- Edit the text of any element
- Change the diagram via the Process Solution Explorer
- Notice that the text field will still be displayed 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
This no longer happens in develop. I suspect this was a drive-by fix: https://github.com/process-engine/bpmn-studio/commit/ef4027e71491d5f31561e812300b77fb80c77b6c
