### ISSUE TITLE
Studio changes process-id to process-name at bpmn-export

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#514]
#### Describe your issue

the studio changes the process-id to process-name in the exported bpmn-file.

#### How can others reproduce the issue?

Export a diagram where process-id and process-name are different.

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`):
- Node (`node --version`):
- NPM (`npm --version`):
- Docker (`docker version --format '{{.Server.Version}}'`):

> You can remove this section if it's irrelevant to the issue
> (for example for certain questions or feature requests).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
How did you import the diagram? Was the name/id correct after importing?

**Comment by SteffenKn** [comment]
I think this has to do with the bug that is described in here: https://github.com/process-engine/bpmn-studio/issues/399

**Comment by SteffenKn** [comment]
This was an issue with the old process_engine. Since we using the process_engine_runtime this will no longer occur.
