### ISSUE TITLE
Add OpenID Connect support to login

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#516]
#### Describe your issue

To login using the [Process Engine Identity Server](https://hub.docker.com/r/5minds/processengine-identity_server/), the current login feature needs to be modified to support OpenId Connect.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Well it does.
