### ISSUE TITLE
🐛Jenkinsfile anpassen

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#519]
#### Describe your issue

Im Jenkinsfile werden Sachen wie ` 'node_modules/, scripts/, package.json'` nach dem ersten build step gestashed und für den nächsten step wieder unstashed.
Wir können font-awesome aktuell nur nutzen, weil wir den Ordner mit eingecheckt haben.
Das wäre nicht nötig, wenn bei dem stashen auch andere generierte Dateien und Ordner berücksichtigt werden, wie z.B. `@fortawesome` oder `bootstrap`.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Which folders must be included after the `npm run build` stage?

@alexanderkasten @Vyperus
