### ISSUE TITLE
Inkonsistente Variablenbenennung

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#529]
#### Describe your issue

Bei meiner Review von https://github.com/process-engine/bpmn-studio/pull/520#pullrequestreview-135321126 sind mir gerade mehrere Vorkommnisse von inkonsistentem Camel Case aufgefallen.

Die Anmerkungen aus der Review sind vermutlich nicht alle, daher sollten wir nach Pfadfinder-Prinzip dafür sorgen, dass diese immer sofort gefixt werden, sobald sie jemandem auffallen.

Die Punkte aus der Review sollten allerdings in einem eigenen PR schnell behoben werden können.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
This should just be ok now :)
