### ISSUE TITLE
Ausbau des BPMN-Studio Client

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#530]
## BPMN-Studio Client gegen ConsumerAPI Service tauschen

Der [BPMN-Studio Client](https://github.com/process-engine/bpmn-studio_client/blob/develop/src/processengine/processengine_repository.ts) soll kurz- bis mittelfristig nicht mehr verwendet werden, da er lediglich die Anbindung an den alten Stack ermöglicht.

Langfristig soll das BPMN-Studio laut meinem Kenntnisstand die ManagementAPI verwenden. Diese befindet sich z.Z. aber noch in der Konzeptionsphase. Daher wäre eine Zwischenlösung, die auch kurzfristig die Umstellung auf den neuen Stack ermöglicht wünschenswert.

Der ConsumerAPI Client bietet glücklicherweise fast alle Methoden, die der BPMN-Studio Client heute bietet, ebenfalls an.

### Gegenüberstellung

Methode in BpmnStudioClient | Methode in ConsumerApiService
---------|----------
 getProcessDefList | getProcessModels
 startProcessById / startProcessByKey | startProcessInstance 
 getUserTaskList | X 
 getUserTaskListByProcessDefId | getUserTasksForProcessModel
 getUserTaskListByProcessInstanceId | getUserTasksForCorrelation
 proceedUserTask | finishUserTask
 cancelUserTask | X 

Die Methode `getUserTaskList`, die alle UserTasks ohne nähere Eingrenzung holen soll, kann für die Umstellung zunächst ignoriert werden. Hier müsste diskutiert werden, ob diese weiter erwünscht ist und ggf. die ConsumerAPI um diese Funktion erweitert werden.

Die Methode `cancelUserTask` kann ersatzlos wegfallen, da das Backend nichts hiervon mitbekommen muss. Der UserTask verbleibt im Status `suspended` und das Frontend verwirft einfach den ggf. vorhandenen State, bzw. navigiert zu einer anderen Ansicht.

## Unterstützung des neuen Objektmodells

Durch die Umstellung auf den ConsumerAPI Service ändern sich auch die Signaturen und wir erhalten Referenzen auf das Objektmodell, das in der `consumer_api_contracts` definiert wird.

Dieses Objektmodell hat den Vorteil, dass darin keine Verweise auf das neue Objektmodell der Process Engine existieren, sondern alle Referenzen auf Typen innerhalb der `consumer_api_contracts` zeigen.

Jedoch bedeutet das auch, dass im BPMN-Studio zunehmend mit Typen aus `consumer_api_contracts` gearbeitet würde.

Hier wäre zu diskutieren, ob das BPMN-Studio je nach Anwendungsfall mit einem Mix aus `consumer_api_contracts` und später `management_api_contracts` arbeitet, nur mit einem von beiden oder sogar eigene Typen definiert.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Den BPMN-Studio Client gibt es nicht mehr. Aktuell wird die Management API benutzt.
