### ISSUE TITLE
Leere Extension Properties

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#531]
#### Describe your issue

Offenbar ist es durch die Modellierung im BPMN-Studio möglich, zahlreiche leere Extension Properties an beliebigen FlowNode-Typen zu produzieren.

Diese leeren Properties werden nicht im Property Panel angezeigt und der Benutzer kann somit nicht sehen, dass diese unnötigen Angaben im Diagramm existieren.

```
        <bpmn:serviceTask id="MyServiceTask" name="My Service Task">
            <bpmn:extensionElements>
                <camunda:executionListener class="" event="" />
                <camunda:properties />
                <camunda:properties />
                <camunda:properties>
                    <camunda:property name="module" value="MyService" />
                    <camunda:property name="method" value="myMethod" />
                    <camunda:property name="params" value="[&#39;1234&#39;]" />
                </camunda:properties>
            </bpmn:extensionElements>
            <bpmn:incoming>
                    SequenceFlow_03ab5x2
                </bpmn:incoming>
            <bpmn:outgoing>
                    SequenceFlow_144j7k7
                </bpmn:outgoing>
        </bpmn:serviceTask>
```
#### How can others reproduce the issue?

Bislang ist nicht klar, wie dieses Verhalten zu reproduzieren ist.

#### Possible solution

Der Benutzer sollte angezeigt bekommen, dass diese leeren Felder existieren, sodass er direkt über die UI die Möglichkeit hat diese wieder zu entfernen.

Gleichzeitig sollte versucht werden dieses Verhalten zu reproduzieren und analysiert werden, wie es vermieden werden kann.

Der BPMN Parser ist beim Versuch diese Properties zu lesen bereits auf Fehler gelaufen und wird in Folge dessen nun robuster gemacht.

Trotzdem sollte es unser Ziel sein solche unnötigen Angaben zu vermeiden, da es auch in Kombination mit anderen Process Engines wieder zu solchen Fehlern kommen könnte.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
@5ebastianMeier das Issue gab es schon mal und wurde hier https://github.com/process-engine/bpmn-studio/pull/522 von mir gefixed 🤔 
Bist du sicher, dass diese leeren ExtensionProperties mit dem aktuellen Develop stand des BPMN-Studios generiert werden ? Wenn man alte Diagramme nutzt sind die Extensions immer noch vorhanden, beim erstellen neuer Diagramme sollte das aber eigentlich nicht mehr passieren.

**Comment by 5ebastianMeier** [comment]
@alexanderkasten "Bislang ist nicht klar, wie dieses Verhalten zu reproduzieren ist."

Du müsstest bitte einmal prüfen, ob das mit dem BPMN-Studio reproduzierbar ist.

**Comment by robpal94** [comment]
Nach aktuellem Stand ist es mit einem neu erstelltem Diagramm nicht mehr reproduzierbar.

**Comment by robpal94** [comment]
Anscheinend ist der Bug wieder zurück. Mit dem aktuellem Stand fügt das Studio wieder vermehrt leere camunda properties am XML der Prozessdiagramme hinzu.
