### ISSUE TITLE
Invalid Line Breaks are Not Removed

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#532]
#### Describe your issue

Wenn das BPMN-Studio ein Diagramm öffnet, indem solche Formatierungen enthalten sind:
```
                <bpmn:flowNodeRef>
                        Task_2347t238947t
                    </bpmn:flowNodeRef>
                <bpmn:flowNodeRef>
                        Task_13123
                    </bpmn:flowNodeRef>
                <bpmn:flowNodeRef>
                        Task_0f9v413
                    </bpmn:flowNodeRef>
                <bpmn:flowNodeRef>
                        Task_0oliufj
                    </bpmn:flowNodeRef>
```

Führt das bislang zu folgenden eingelesenen Werten im BPMN-Parser des Backends:

```
       '\n                        Task_2347t238947t\n                    ',
       '\n                        Task_13123\n                    ',
       '\n                        Task_0f9v413\n                    ',
       '\n                        Task_0oliufj\n                    ',
```

Der Parser des Backends wird im Rahmen dieser Issue robuster gemacht, sodass das Backend künftig hiermit klarkommt (siehe https://github.com/process-engine/process_engine/issues/118).

#### How can others reproduce the issue?

Vermutlich ist dieser Fehler nicht direkt durch die Modellierung im BPMN-Studio entstanden, sondern durch die manuelle Bearbeitung in einem externen Code Editor.

#### Possible solution

Da der Export vermutlich trotzdem solche Merkmale beibehält sollte das BPMN-Studio im Rahmen der Validierung des Dokuments dennoch solche Vorkommnisse entfernen.

Das führt zu weniger Folgefehlern und schafft eine bessere Kompatibilität zu anderen BPMN Tools.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
Ein möglicher Lösungsansatz kann im PR https://github.com/process-engine/process_engine/pull/119/files zu oben erwähnter Issue gefunden werden.

**Comment by Vyperus** [comment]
Die Formatierungen entstehen wohl genau dann wenn wir das Diagram zum exportieren als .bpmn formatieren.

`const formattedXml: string = beautify(xml);`

Die XML-View formatiert das XML zwar auch, sollte dies aber nicht speichern.

Das würde bedeuten das der Fehler erst entsteht wenn ein zuvor formatiertes und exportiertes Diagram wieder importiert wird. @5ebastianMeier

**Comment by 5ebastianMeier** [comment]
@SteffenKn Grundsätzlich hast du recht. Aber, dass dadurch oben benannte Artefakte entstehen ist neu.

Die Formatierung, die oben zu sehen ist, sieht kaputt aus - dort gibt es falsche Einrückungen.
Vermutlich ist die Formatierung auch nicht durch das BPMN-Studio, sondern durch ein Beautify Plugin in VS Code entstanden.

Trotzdem wäre die Erwartungshaltung, dass die Diagramme ohne die Artefakte und mit korrekter Formatierung das BPMN-Studio verlassen.

**Comment by robpal94** [comment]
Wenn ich ein Diagramm einfach normal als BPMN - XML exortiere sieht es ganz normal formatiert aus (so wie ich es denke ich auch bedacht war). Die obigen Artefakte mit den entsprechend folgenden Leerzeichen waren bei mir im exportiertem XML nicht vorhanden.

<img width="1257" alt="screen shot 2018-07-11 at 10 15 52" src="https://user-images.githubusercontent.com/38498731/42559102-73eda6ae-84f3-11e8-9282-1c1da4e8871f.png">

**Comment by 5ebastianMeier** [comment]
Das Verhalten ist im BPMN-XML Parser des Backends inzwischen behoben worden.

Im BPMN-Studio war mein letzter Stand, dass wir eine eigene UserStory daraus machen wollten.

In der User Story soll dann das allgemeine Verhalten bei der Verbesserung von Validierungsfehlern am Dokument spezifiziert und implementiert werden.

Bis für diese Story eine Issue existiert bzw. ein Termin vereinbart/abgehalten wurde, würde ich dieses Issue gerne geöffnet lassen.

/cc @cmg-dev @roblen45

**Comment by SteffenKn** [comment]
Is this still a thing?

**Comment by cmg-dev** [comment]
No it isn't.
