### ISSUE TITLE
Inconsistent behaviour between BPMN-Studio and Camunda

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#536]
We should discuss the behavior of BPMN-Studio handling empty property-elements.
The quest to answer is:

**Should BPMN-Studio delete empty property-elements automatically on save?**

The following text and images shows the XML and the UI important to the discussion.

## Setup

The following XML/UI is given:

### In Camunda:

<img width="392" alt="bildschirmfoto 2018-07-10 um 13 24 54" src="https://user-images.githubusercontent.com/17248802/42507253-c551ff04-8444-11e8-97f6-2e838cbe4fc1.png">

<img width="251" alt="bildschirmfoto 2018-07-10 um 13 25 15" src="https://user-images.githubusercontent.com/17248802/42507261-cd90d42e-8444-11e8-9bc9-4c9b6815fea4.png">

**Camunda won't delete this on save**

### In BPMN-Studio:

<img width="450" alt="bildschirmfoto 2018-07-10 um 13 26 46" src="https://user-images.githubusercontent.com/17248802/42507306-fb5dcbc8-8444-11e8-922b-413e96efbae4.png">

<img width="253" alt="bildschirmfoto 2018-07-10 um 13 26 35" src="https://user-images.githubusercontent.com/17248802/42507314-ff17ba80-8444-11e8-92e7-b264d4e54c34.png">

**Comment by cmg-dev** [comment]
We discussed this tomorrow morning.

This is part of a much bigger UX-Story. The goal of this story is to help the user as much as possible.

I would phrase goal like this:

*Provide a mechanism, that helps the user to resolve issues with the Document.*

**Comment by cmg-dev** [comment]
Nobody need those empty fields! Delete them...
