### ISSUE TITLE
Delete Tasks

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/bpmn-studio#54]
#### Describe your issue

It would be nice to be able to delete tasks from the Task List.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
#34

**Comment by heikomat** [comment]
This needs to be conceptualized first. we need to answer the question: what is supposed to happen, if a user decides to not handle a userTask.

**Comment by Paulomart** [comment]
UserTasks will remain pending until you finish them.
