### ISSUE TITLE
✨ Features for the Diff View

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#541]
#### Describe your issue

1. Make colors of diff changeable.
This is very useful for colour-blind people, for example.
1. Moving to Element when clicked on change in change list.
1. Resize functionality for the Viewers.
1. Add different views to make it look like in this screenshot as well?:
> ![image](https://user-images.githubusercontent.com/20394992/43703846-54accd4a-995e-11e8-81a8-8e7a277ab9f7.png)
Maybe by allowing the user to resize the diffs to 100% width. So that the viewers are then displayed among each other. Or by using buttons.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
> I think this dialog should default to the currently selected diagram:
> 
> <img width="499" alt="grafik" src="https://user-images.githubusercontent.com/4148404/53866717-7fc89c80-3ff2-11e9-83d4-370f8bd30243.png">
> 
> Also I think this dropdown should highlight the currently seleceted:
> 
> <img width="186" alt="grafik" src="https://user-images.githubusercontent.com/4148404/53866910-f6fe3080-3ff2-11e9-9d24-880b16ea24fa.png">
> 

@Paulomart
