### ISSUE TITLE
🐛 Padding of Icons is not Equal

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#583]
#### Describe your issue

<img width="74" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887662-cbeb8246-8aa6-11e8-907f-dbd39f489bed.png">
<img width="165" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887678-d2ffa666-8aa6-11e8-8712-9722852b93c0.png">
<img width="96" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887688-da6518b4-8aa6-11e8-916d-8d59983bb361.png">
<img width="72" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887709-e32dfab0-8aa6-11e8-9f91-859173305929.png">
<img width="32" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887729-ee8fb22c-8aa6-11e8-9d26-100df68f18d0.png">

<img width="213" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887811-14e91b70-8aa7-11e8-91cf-409a7f0c60e5.png">

vs 

<img width="240" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42887827-1a460bd2-8aa7-11e8-9415-2dd168abb384.png">

In many places we have icons, but all use a different padding/margin.

#### Possible solution

Create a ruleset for icon layout.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@Paulomart is this still a thing?

**Comment by Paulomart** [comment]
I think so.
