### ISSUE TITLE
Can't set the same ID in different UserTask Form Fields.

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#590]
#### Describe your issue
It's not possible to assign the same ID to two independent UserTask Form fields.

We need to discuss, if it is allowed to have multiple UserTasks with the same form field id's and how we want to solve this. 

#### How can others reproduce the issue?
* Create two UserTasks
* Try to add a form field with the same id in both UserTasks

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
I do remember that this was a wished feature and was implemented on purpose, but I don't know the exact reason anymore.

**Comment by cmg-dev** [comment]
@robpal94 This is actually a feature...

this was introduced on my behalf, as this interferes currently with our implememtation of the Management Client.
