### ISSUE TITLE
🐛 Windows Setup Does Not Work

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#593]
#### Describe your issue

The Windows setup generated by Jenkins does not work, because it is not built with Windows.

#### How can others reproduce the issue?

- Try to run BPMN-Studio on windows using latest release 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Duplicate of https://github.com/process-engine/bpmn-studio/issues/525.

**Comment by Paulomart** [comment]
Duplicate #525
