### ISSUE TITLE
Sidebar Resizeable

### ISSUE THREAD

**Issue by heikomat** [process-engine/bpmn-studio#6]

**Comment by Vyperus** [comment]
Can i get some more Information on this please?

**Comment by heikomat** [comment]
@Vyperus This issue was copy-pasted over from the old charon-repo. This issue is about the sidebar in the bpmn-modeler, the part on the right where you can set your extensions like "uiName" and form-elements and such things.

This sidebar currently has a fixed with. We want the width of that sidebar to be changebale via dragging

**Comment by moellenbeck** [comment]
@heikomat @Vyperus but we want to replace the sidebar (PropertyPanel) as soon as possible. I think @5ebastianMeier and @ppoetschke will discuss a mvp solution in the week after next week.

**Comment by Vyperus** [comment]
Where are we standing on this topic?
