### ISSUE TITLE
Show process token of current task

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/bpmn-studio#61]
#### Describe your issue

It would be nice to have a look at the process token in the different tasks of a process.
Maybe add a button in the 'Task List' for each task which displays the token or provide a REST route to get the current process token by TaskId.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I think this will be fixed by https://github.com/process-engine/bpmn-studio/pull/883
