### ISSUE TITLE
When exporting a diagram, the export filetype is not correctly shown in the explorer window

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#647]
#### Describe your issue
When exporting the diagram, the file type is always set to _all files (*.*)_. In a perfect world, it would be set to the filetype that the user wants to export. 

<img width="620" alt="screen shot 2018-07-26 at 14 08 25" src="https://user-images.githubusercontent.com/38498731/43261592-8c22fa3a-90dd-11e8-9dae-7cb6c22c6fe1.png">

#### How can others reproduce the issue?
* Try to export a diagram
* Look at the filetypes dropdown menu

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I love the window title of the select dialog..

**Comment by SteffenKn** [comment]
Is this still happening with electron 2.0.0?

**Comment by Paulomart** [comment]
> Is this still happening with electron 2.0.0?

Yes
