### ISSUE TITLE
Process Instance List is always empty

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#649]
#### Describe your issue
The ProcessInstance list is always empty, even if a process instance is running.

![jul-26-2018 14-22-28](https://user-images.githubusercontent.com/38498731/43262175-7d1e7d3c-90df-11e8-91ac-85bd7d4907ed.gif)

#### How can others reproduce the issue?
* Start a process instance
* Navigate to the process instance list

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
This will be fixed with #598
