### ISSUE TITLE
Can't resize window

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#651]
#### Describe your issue
When trying to resize the window, strange things are happening. Sometimes, the window gets dismissed. In general, the resizing behaves very strange. 

This may be an issue with VMWare, since it dynamically changes the "screen resolution" in Windows. We should test this on a standalone window machine. 

![jul-26-2018 14-26-25](https://user-images.githubusercontent.com/38498731/43262451-723a8842-90e0-11e8-85be-fe09081975df.gif)
 

#### How can others reproduce the issue?
* Start BPMN Studio
* Resize the window

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I think your screen resolution of the windows machine is smaller then the minum size of bpmn-studio.

**Comment by Paulomart** [comment]
@robpal94 Please retry with a bigger screen resolution.

**Comment by robpal94** [comment]
With a bigger screen resolution, it works fine.

**Comment by Vyperus** [comment]
I wasn't able to reproduce this with the latest version of BPMN-Studio. I will close this for now.
