### ISSUE TITLE
Can't leave `sign in with google`

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#672]
#### Describe your issue
Related to #598 

When you click on login and use google as external login, there is no way to navigate back. In order to cancel the login you have to close bpmn-studio.

#### What's your setup

Tested with osx and bpmn-studio on feature/migrate_bpmn_studio_to_new_stack branch.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
This bug is similar to this one: https://github.com/process-engine/bpmn-studio/issues/675

For both, we need to either fix how our Electron version handles the redirect - or customize the IdentityServer pages, to offer those functions we're missing.

**Comment by cmg-dev** [comment]
We should Customize the page of the IdentityServer in the first place.

This is not an entirely well designed fix, but it will help.
