### ISSUE TITLE
We NEED a ConfigurationService

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#673]
#### Describe your issue

We NEED a ConfigurationService.

Directly accessing a config is very fragile and can lead to strange user experience, that is sadly hard to debug.

For example:
```
    this._getProcessesIntervalId = window.setInterval(async() => {
      await this.updateProcesses();
      this.updateList();
    }, environment.processengine.poolingInterval);
```

#### Possible solution

Add a ConfigurationService,

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
#1219

**Comment by Vyperus** [comment]
So after a long discussion we decided to not add a config service.
