### ISSUE TITLE
Identityserver admin ui can be opened in studio

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#675]
#### Describe your issue

Related to #598 

Login page links to adminUI panel of the identity server. Admin UI will then be opened within the electron application.

#### How can others reproduce the issue?

<img width="261" alt="screen shot 2018-07-31 at 15 23 43" src="https://user-images.githubusercontent.com/21304781/43462793-5878bdca-94d7-11e8-9c75-923ca77cbcbf.png">

Go to login window, click on the link in the upper left corner.

#### Possible solution

Edit the template.

#### What's your setup

bpmn studio

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
Bug or Feature? 😄
