### ISSUE TITLE
`You are now logged out` may be wrong

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#676]
#### Describe your issue

Related to #598 
As soon as you click on logout, you will see a window, which claims that you are logged out and presents you a link to return you to your application.

However, you are technically not logged out at this point and if you cancel the dialogue(by closing the window) you can still access your diagrams etc.

#### What's your setup

Bpmn Studio

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
The link in the "logged out page" only finishes the progress and updates state in the client.
At this point in time the token should already have been invalidated.

This sounds to me like the token has not expired yet. From what I know about IdentityServer, the logout process is finished from its perspective when the "logged out page" is shown.

@cmg-dev can you confirm that?

**Comment by 5ebastianMeier** [comment]
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

As far as I understand it, the behavior described is also the behavior we're currently using.

**Comment by cmg-dev** [comment]
@LeoTT this is actually correct. We can reconfigure this, in the open-id-config in the studio.

This is something, we look into in the future.

**Comment by Vyperus** [comment]
This shouldn't happen anymore.
Fixed with: #1295
