### ISSUE TITLE
No redirect after logout

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#678]
#### Describe your issue
Related to: #598 
After logging out I can still see the diagram that I opened when I was logged in and the entries in the process solution panel. I can ultimatly do very little with that (because most actions require the access token) but I should not even be able to see that anymore.

#### How can others reproduce the issue?
- login
- open diagram
- logout

#### Possible solution

redirect to welcome page & empty the list in the solution panel

#### What's your setup

osx, bpmn studio

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
It's rather complicated to analyze on which route we are during login and then make a decision per route where to redirect.

We can safely navigate to the landing page if that's what we want.
