### ISSUE TITLE
There is no way to create diagrams

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#679]
#### Describe your issue

Related to #598 only.
In the current processEngine there is no way to create new diagrams.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
This is done.
