### ISSUE TITLE
Database button is irritating in browser

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#680]
#### Describe your issue

In the electron client you can choose between filesystem and database view.
When using browser there is no filesystem. Therefore only the database button exists. Does nothing and the tooltip `Show database view` helps even less. Unexperienced users can not know they are already in the database view.

<img width="256" alt="screen shot 2018-08-01 at 08 58 39" src="https://user-images.githubusercontent.com/21304781/43506253-d085ae8a-9569-11e8-84e2-dd70a2a902f7.png">
Talking about the button above `Solution panel`.

#### Possible solution

Hide that section of the panel for browsers.

#### What's your setup

osx, chrome

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This has been fixed with the new solution explorer
