### ISSUE TITLE
How to execute a Process with a UserTask? 

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#697]
#### Describe your issue
If I try to execute a process with the new BPMN Studio Release, this happens: 

![aug-02-2018 09-29-56](https://user-images.githubusercontent.com/38498731/43569165-ff778c90-9636-11e8-9849-de9a5bd64c06.gif)

I would expect the process to show me the dialog, defined by the UserTask. Isn't this the case anymore? 

##### Setup
Im using the released BPMN Studio 4.0.0 version, which I build myself. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Tested this yesterday evening and had it working.

Looks like a `properties` entry is missing in the user task (key: `uiName`, value: `Form`).
