### ISSUE TITLE
✨Find a Way to Display a Warning When Pool is About to be Collapsed

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#699]
## Describe your issue

Collapsing a pool/lane will lead to deleting ALL containing elements.

## How can others reproduce the issue?

1. Open a BPMN diagram that contains a Pool/Lane and Elements
1. Collapse the Pool/Lane.
1. Expand it again.
1. See, that the Pool/Lane is empty.

## Possible solution

No real solution possible; consider displaying a warning and a confirm action, that says:

> All elements will be deleted, when the pool is collapsed.

**Comment by Vyperus** [comment]
Actually I found a "feature-request" in the bpmn-js repo: https://github.com/bpmn-io/bpmn-js/issues/736

**Comment by rrrene** [comment]
Wir sollten verhindern, dass der Benutzer sich derart in den Fuß schießt. :+1:
