### ISSUE TITLE
Title Bar icons overlap with Identity Server Header

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#702]
#### Describe your issue
The Icons of the title bar are in conflict with the Logout Page of the Identity Server. 

#### How can others reproduce the issue?
* Log in
* Log out
* Look at the title bar of the opened Identity Server Window

![screen shot 2018-08-02 at 13 37 41](https://user-images.githubusercontent.com/38498731/43581517-874d4552-9659-11e8-9a96-e242ff316c3a.png)

#### Possible solution
Add a solid Task bar

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
This is associated with https://github.com/process-engine/bpmn-studio/issues/705

In Electron > 2 the title bar has a dedicated area that doesn't overlap.
