### ISSUE TITLE
Electron@2/3 not working

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#705]
#### Describe your issue

Currently we're having compatibility issues with Electron@2.

This issue aims to track features of Electron@2 we want to use and problems that prevent us from upgrading to Electron@2.

#### New Features we want to use

* File Type Filter in Open File/Folder Dialog
* Dedicated Title Bar
   * No Overlap between Window Buttons and e.g. IdentityServer Page Header

#### Known Problems

* Redirect from IdentityServer doesn't work, results in empty window

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
Ich habe mir das mal genauer angeschaut und herausgefunden, dass bei der electron@3.0.4 Version 
das Event `open-url` nicht geworfen wird und deshalb folgender Codeblock nicht ausgeführt wird: [L125](https://github.com/process-engine/bpmn-studio/blob/develop/electron_app/electron.js#L125)

Da nicht zurück auf die Index navigiert wird, bleibt dann das BrowserWindow weiß.

Ich vermute das es damit zutun hat, dass der Callback Request nach dem Login `failed`.

<img width="409" alt="bildschirmfoto 2018-10-11 um 11 13 42" src="https://user-images.githubusercontent.com/17065920/46796555-43e42080-cd4d-11e8-966b-b339203cac2f.png">

Bei der electron@1.7.9 Wird übrigens der Callback Request `cancelled` .
Das Event wird aber scheinbar vorher triggered.

<img width="488" alt="bildschirmfoto 2018-10-11 um 11 18 08" src="https://user-images.githubusercontent.com/17065920/46796665-8279db00-cd4d-11e8-9478-4109bbb4c3c4.png">
