### ISSUE TITLE
Failed to fetch Error Message when clicking the login button

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#706]
#### Describe your issue
If you click at the login button, the message _Error: Failed to fetch_ appears. The login works fine tho, but this Error message may disturb some users. 

![aug-02-2018 14-54-53](https://user-images.githubusercontent.com/38498731/43584993-402cfdce-9664-11e8-90e1-02d60aef5ff3.gif)

You have to watch carefully to see the notification appear.

#### How can others reproduce the issue?
* Start BPMN Studio
* Click at the login button
* Look at the bottom left corner

#### Possible solution
Dont show the notification. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
I've just checked it and it's neither fixed nor changed the error message.

@Vyperus you may have tested that wrong.

**Comment by alexanderkasten** [comment]
@SteffenKn now fixed?

**Comment by Vyperus** [comment]
Now fixed.
