### ISSUE TITLE
Diagram Creation Service Does Not Generate Ids

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#711]
#### Describe your issue

Currently the Diagram Creation Service does not generate Ids for the:
- Correlation
- Participant
- Lane

We should check if it is necessary to generate them or if it is ok to use the same ids for every diagram created by the BPMN-Studio.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
I just tested this behavior and couldn't come up with an error.
Closing this for now.
