### ISSUE TITLE
🐛AutoUpdater/notificator isn't working on windows

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#715]
#### Describe your issue

The electron auto updater isn't working on windows.

![bildschirmfoto 2018-08-03 um 08 48 40](https://user-images.githubusercontent.com/17065920/43628423-7ec5a874-96fa-11e8-90e2-b0d35326f36f.png)

#### How can others reproduce the issue?

- download an old windows release and install it
- start bpmn-studio

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
https://github.com/process-engine/bpmn-studio/issues/705
