### ISSUE TITLE
🐛 When There Is a Form Field Without a Type the Bpmn-Studio Thinks Its Type Is Custom Type

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#731]
#### Describe your issue

When there is a user task with a form field without type the BPMN-Studio thinks its type is custom type.

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Go to the Detail View of any diagram 
- Add a user task
- Add a form field without a type
- Save the diagram
- Reload the page
- Notice that the type of the form field now is custom type

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
Should we allow to save a diagram with a UserTask that contains an undefined Form Type?
