### ISSUE TITLE
Opening color picker breaks layout

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#744]
#### Describe your issue

When opening the color picker, a gap of white space opens between the property panel and the right toolbar.

All is fine:
![bildschirmfoto 2018-08-03 um 15 36 51](https://user-images.githubusercontent.com/16539774/43645755-2f0f752e-9733-11e8-83f9-b7af2023613a.png)

White space appears:
![bildschirmfoto 2018-08-03 um 15 36 42](https://user-images.githubusercontent.com/16539774/43645756-2f59ba44-9733-11e8-92b3-74ab52050a76.png)

#### How can others reproduce the issue?

Open the color picker.

#### Possible solution

I remember a similar problem where the overflow was misconfigured on a container.

That might be the issue here as well, because the space seems to have the same width as a scroll bar.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
Please provide information about your system and relevant software versions.

I can't really reproduce this on my machine, with the 4.0.1 release.

**Comment by 5ebastianMeier** [comment]
I remember that there was a mac-specific setting to disable automatic scrollbars somehow - I'll look up the setting once I'm back at my mac.

On Windows 10 I got the same issue:
![color_picker_scrollbar_error](https://user-images.githubusercontent.com/16539774/43662971-048eebce-9768-11e8-8ca8-dc0b35ae15b4.PNG)

I don't know yet if Windows offers a setting similar to the one described above.
