### ISSUE TITLE
Application Icon quality on Windows 10

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#755]
#### Describe your issue

When BPMN Studio is pinned to the Start Menu or the Taskbar of Windows 10, the image quality of the icon has a low image quality. The image quality on the file type thumbnail for `.bpmn`-files shows the full image quality though.

##### File Thumbnail
![icon_thumbnail](https://user-images.githubusercontent.com/16539774/43677695-9bdaded6-9806-11e8-9fb0-62b85ed8ba58.png)

##### Pinned to Start Menu
![icon_error](https://user-images.githubusercontent.com/16539774/43677680-68eb0ac8-9806-11e8-92eb-c6104ac0cc67.png)

##### Pinned to Taskbar
![icon_error_2](https://user-images.githubusercontent.com/16539774/43677681-690454ec-9806-11e8-8089-77e0b18c0494.png)

#### What's your setup

- Windows 10

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
@ElRaptorus Kannst du das nochmal prüfen und ggf. schließen?
