### ISSUE TITLE
Cannot select process from project explorer for call activity.

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#756]
#### Describe your issue

Cannot select process from project explorer for call activity.

#### How can others reproduce the issue?

Add a new process to project explorer without deploying it.

Create a call activity in a different process. 

You won't be able to select the first process for call activity

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
You can now select any process from the solution the process with the call activity is in.
