### ISSUE TITLE
Wrap charon into an electron app and provide new releases via git

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/bpmn-studio#77]
#### Describe your issue

- [x] Wrap it into a electron app (done #93)
- [x] Make the `process-engine-basepath` configurable via settings dialog (done #94) 
- [ ] Distribute it via electron updates

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

:white_check_mark: I've checked if this issue already exists
:white_check_mark: I've included all the information that i think is relevant
:white_check_mark: I've added logs and/or screenshots (if applicable)
:white_check_mark: I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
#93 resolves the first problem.

**Comment by Vyperus** [comment]
Eine super basic version habe ich hier: https://github.com/Vyperus/electron_autoupdate_example
