### ISSUE TITLE
Icon for Solution Explorer looks like typical "Share" icon

### ISSUE THREAD

**Issue by TwixRaider** [process-engine/bpmn-studio#770]
#### Describe your issue

The icon to toggle the solution explorer looks very much like the "Share" icons in apps. For new users this might be the last icon to try in their attempt to open BPMN files (see issue #769).

<img width="385" alt="grafik" src="https://user-images.githubusercontent.com/36530578/43765837-2e1d4500-9a31-11e8-8e92-ef5a2c731199.png">

#### Possible solution

Use an icon that would be more familiar to the user, especially if he uses other tools with features like that.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@TwixRaider What would be a better icon? :)

**Comment by TwixRaider** [comment]
@cmg-dev Are we limited to a icon font like Fontawesome or can we use any PNG file?

**Comment by TwixRaider** [comment]
How about using 2 icons in combination like this:

![closed](https://user-images.githubusercontent.com/36530578/44511346-79f31580-a6b7-11e8-96b6-4524776d5930.png)

With this there is also an indication of the current state of the solution explorer (opened/closed). The icons can be found here:

https://fontawesome.com/icons/window-maximize?style=regular
https://fontawesome.com/icons/caret-right?style=solid
https://fontawesome.com/icons/caret-left?style=solid

**Comment by Vyperus** [comment]
This is part of a bigger discussion, I will close this in favor of #878
