### ISSUE TITLE
🐛Saving Diagram fails on PE when User Task has no Element

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#771]
#### Describe your issue

If you create a diagram with a single user task and don't give it any elements, you can save it on your filesystem but not on your PE.
The Problem here is that the user doesn't get informed about this  error before saving.

However there is no request at the PE so this is not a Backend error but an error in the saveDiagram-Function of the process-def-detail component.

See this Screenshots for more details:

The diagram:
<img width="1299" alt="bildschirmfoto 2018-08-07 um 11 02 16" src="https://user-images.githubusercontent.com/17248802/43766010-ac57f6a4-9a31-11e8-94f8-5a9e7a1c01ac.png">

Error in Toastr:
<img width="354" alt="bildschirmfoto 2018-08-07 um 11 00 46" src="https://user-images.githubusercontent.com/17248802/43765981-9a80eb5c-9a31-11e8-9280-aab8f43fb494.png">

Error in console:
<img width="781" alt="bildschirmfoto 2018-08-07 um 11 02 02" src="https://user-images.githubusercontent.com/17248802/43765994-a542ecfc-9a31-11e8-992a-69da1e245378.png">

Fun fact:
If you add a Formfield to the user task and delete it right away you can now save the diagram.

#### Possible solution

Look for errors in validation that gets called before saving the diagram in process-def-detail view.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
Can't reproduce.

**Comment by robpal94** [comment]
When I try to deploy or save a diagram which contains a single UserTask to a ProcessEngine, the ProcessEngine returns the following error: 

```
POST http://localhost:8001/api/management/v1/process_models/bla/update 422 (Unprocessable Entity)
```

![screen shot 2018-08-10 at 09 14 34](https://user-images.githubusercontent.com/38498731/43944035-e109b588-9c7d-11e8-8273-55e04d4062c8.png)
