### ISSUE TITLE
The term "Solution" is misleading

### ISSUE THREAD

**Issue by TwixRaider** [process-engine/bpmn-studio#772]
#### Describe your issue

For users working with developer tools like Visual Studio, Visual Studio Code and others the term "Solution" is misleading because it refers usually to a kind of workspace that the user can create and manage be himself. It might imply that the user is able to add/remove/hide files and save the result as a custom "Solution".

<img width="232" alt="grafik" src="https://user-images.githubusercontent.com/36530578/43766465-c3e90e1a-9a32-11e8-9e05-d5ecb029aace.png">

<img width="261" alt="grafik" src="https://user-images.githubusercontent.com/36530578/43766429-b120c386-9a32-11e8-91dc-c950a3ebe376.png">

#### Possible solution

As in BPMN Studio a "Solution" refers to a folder in the file system, it should be called "Folder" instead of solution. 

Using "Open a Folder" for the button and "Opened Folders" for the label might be more clear to the user. This would be similiar to the naming in Visual Studio Code which also works with folders instead of (custom) solutions like Visual Studio does.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
This needs to be documented better.

@TwixRaider That VS users know solution from a different context is bad, but I do not think, that we can find a better name.

But certainly, we lack a documentation.

**Comment by cmg-dev** [comment]
We described what a Solution is in the User Guide section of our handbook.

Please have a look at the [documentation](https://www.process-engine.io/documentation/) and thank you :) WE explained a [Solution](https://www.process-engine.io/documentation/GLOSSARY.html#solution).
