### ISSUE TITLE
Refactor Navbar to fit smaller sizes / be more responsive

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#774]
#### Describe your issue

We should refactor the navbar to be more responsive. Then we can get rid of the size restriction in the electron app which caused more trouble than it is worth right now.
This needs to be done when we want to create an IPad App anyway.

#### Possible solution

refactor navbar to be more responsive and fit smaller window sizes.

#### Issues caused by size restriction

#300 
#651 

#### What's your setup

Every setup

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
I feel like we can get rid off the size restriction right now (or at least allow smaller windows).
The original style issues are no longer reproducable and in chrome dev tools IPad view is okay (clustered but nothing broken).

**Comment by cmg-dev** [comment]
This is a concern for a major BPMN-Studio overhaul. 

This will result in a component, that is better cut altogether. 

Include this in the upcoming structural changes
