### ISSUE TITLE
BPMN-Studio Needs to Store IdentityServer Configuration

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#776]
#### Describe your issue

When restarting BPMN-Studio the configuration of IdentityServer get lost.

#### How can others reproduce the issue?

Set IdentityServer configuration and restart Studio.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
A possible Solution is not trivial, as the web-version and the electron-version offer different capabilities.

**Comment by Vyperus** [comment]
It would be nice to have a route at the PE where the PE declares its authority, then you wouldn't have to configure it in BPMN-Studio anyway. I created a Feature-Package for that.
