### ISSUE TITLE
💬Shall We Remove Pre-Release Tags After Publishing a Stable Version?

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#777]
## Describe your issue

When Jenkins publishes a feature, it will also generate a tag on GitHub/in git.

This gets messy fast:

```bash
git tag --list
1.0.0
v0.1.0
v1.0.0
v1.0.0-rc1
v1.0.0-rc10
v1.0.0-rc11
v1.0.0-rc12
v1.0.0-rc13
v1.0.0-rc14
v1.0.0-rc15
v1.0.0-rc16
v1.0.0-rc17
v1.0.0-rc2
v1.0.0-rc3
v1.0.0-rc9
v1.0.1
v1.1.0
v1.1.1
v1.1.1-pre-b101
v1.1.1-pre-b102
v1.1.1-pre-b96
v1.1.1-pre-b97
v1.1.1-pre-b98
v1.1.1-pre-b99
v1.2.1-pre-b103
v1.2.1-pre-b104
v1.2.1-pre-b105
v1.2.1-pre-b106
v1.2.1-pre-b107
v1.2.1-pre-b109
v1.2.1-pre-b110
v1.2.1-pre-b111
v1.2.1-pre-b112
v1.2.1-pre-b113
v1.2.1-pre-b114
v1.2.1-pre-b115
v1.2.1-pre-b118
v1.2.1-pre-b119
v1.2.1-pre-b120
v1.2.1-pre-b121
v1.2.1-pre-b122
(...)
```

You get the idea, the problem is, that the transition from one release to another is not something we want to preserve. Take a look at the build, we did while developing the v3.0.0:

```
v2.0.0
v2.0.0-pre-b138
v2.0.0-pre-b139
v2.0.0-pre-b140
v2.0.0-pre-b141
v2.0.0-pre-b142
v2.0.0-pre-b143
v2.0.0-pre-b144
v2.0.0-pre-b145
v2.0.0-pre-b146
v2.0.0-pre-b147
v3.0.0
```

No one will ever gain something, by installing the *-pre-* Versions of the builds.

## How can others reproduce the issue?

Run `git tag --list`.

## Possible solution

My suggestion is: 

Delete the tags, if we publish a stable version.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@Paulomart Your opinion?

**Comment by Vyperus** [comment]
I would like to have a clear indicator on the version. 
Versions like: `4.2.0-pre-b362` are not telling me much.
Better: `4.2.0-pre-b1` 
This could indicate that since the stable release of `4.2.0` there was 1 feature added and build.

**Comment by Paulomart** [comment]
I see these problems:

- `-pre-bXX` is lying, its a `-post-bXX` since this is a version released __after__ a major.
- Resetting a the build number is not possible in Jenkins.
-  Removing old builds is okay for me -- but we would also need to delete them on GitHub. They a not deleted when deleting the tag.

**Comment by ElRaptorus** [comment]
Wurde mittlerweile erledigt.
