### ISSUE TITLE
🐛Reset the Build Number for Jenkins Publishes

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#778]
## Describe your issue

The build number we use only increases:

```
v1.2.1-pre-b129
v1.2.1-pre-b130
v1.2.1-pre-b131
v1.2.1-pre-b132
v1.2.1-pre-b134
v1.2.1-pre-b135
v2.0.0
v2.0.0-pre-b138
v2.0.0-pre-b139
v2.0.0-pre-b140
v2.0.0-pre-b141
v2.0.0-pre-b142
v2.0.0-pre-b143
v2.0.0-pre-b144
v2.0.0-pre-b145
v2.0.0-pre-b146
v2.0.0-pre-b147
v3.0.0
v3.0.0-pre-b149
v3.0.0-pre-b150
v3.0.0-pre-b152
v3.0.0-pre-b155
v3.0.0-pre-b156
v3.0.0-pre-b157
v3.0.0-pre-b158
v3.0.0-pre-b159
v3.0.0-pre-b160
v3.0.0-pre-b161
v3.0.0-pre-b162
v3.0.0-pre-b163
v3.0.0-pre-b164
```

It never resets.

## How can others reproduce the issue?

Look at the tags.

## Possible solution

Reset the build number for every feature.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Do you want to reset the build number everytime a new major version is released? What you see its only the develop build number.

**Comment by rrrene** [comment]
Wird durch das neue Release-Konzept abgedeckt. Soll heißen, das wird umgesetzt.
