### ISSUE TITLE
Implement LocalStorage Repository for Solution Explorer

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#781]
#### Describe your issue

The current UX in the web version of BPMN-Studio is not good enough.

We need a way to use BPMN-Studio in the web version like we use the electron version.

One way to offer something similar as the FileSystem Solution Explorer would be a LocalStorage version of it. From there the user can create, design and deploy diagrams like in the electron version.

#### How can others reproduce the issue?

Start the web version and try to work with it.

#### Possible solution

Create a LocalStorage version of the SolutionExplorer.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
This is essential for a good UX in the Web Version for the Studio.
