### ISSUE TITLE
Different between selecting a process from plan-view or design-view

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/bpmn-studio#788]
#### Describe your issue

After deploy a process from the _design-view_ the deploy button are visible. After go to the 
plan view the deploy button switches to the run-button.

<img width="1680" alt="processmodel-with-deploy-button" src="https://user-images.githubusercontent.com/169372/43983305-36ac8d72-9cfa-11e8-922d-a3ab3b112269.png">
<img width="1300" alt="processmodel-with-run-button" src="https://user-images.githubusercontent.com/169372/43983306-36cb1080-9cfa-11e8-8184-73de7a7d1974.png">

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): macos 10.13.6
- Node (`node --version`): -
- NPM (`npm --version`): -
- Docker (`docker version --format '{{.Server.Version}}'`): -

> You can remove this section if it's irrelevant to the issue
> (for example for certain questions or feature requests).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
The technical reason behind this that the start-button is only visible if you opened a diagram that is on the PE already. If you deploy it you don't automatically change the "view" so you are still viewing the diagram that is on your filesystem and not the one you deployed on the PE. That would be easy to change, so do I understand you correctly that you want the "view" to automatically change, in order to show the start-button, right after you deploy a process?

**Comment by cmg-dev** [comment]
@Vyperus I think the technical reason is obvious to @moellenbeck ;)

He wants to know: But Why?!

**Comment by cmg-dev** [comment]
This needs a user story, aka concept of how we want to run this.

**Comment by Vyperus** [comment]
This now got 2 Updates. @moellenbeck Please check if the solution we attempted suits your needs.

**Comment by Vyperus** [comment]
After iterating about this several times. I think we got a solution we are "ok" with. Please feel free to reopen this issue if you don't think so. I will close this for now.
