### ISSUE TITLE
Replace diff view icon

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#801]
#### Describe your issue

IMO the current Icon to open the diff view is a bit misleading. Also, if you open the diff - view, the icon did not change at all. This makes the usage of the Icon a but unnecessary because it meaningless. 

<img width="271" alt="screen shot 2018-08-16 at 14 05 13" src="https://user-images.githubusercontent.com/38498731/44207407-6e569a80-a15d-11e8-9187-57898ec06492.png">

I would use the following Icons: 
* [diff view](https://fontawesome.com/icons/columns?style=solid)
* [diagram view](https://fontawesome.com/icons/pencil-ruler?style=solid)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
This is Part of bigger discussion, I will close this Issue in favor of: #878
