### ISSUE TITLE
🐛Process list pager without function

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/bpmn-studio#803]
#### Describe your issue

A pager shows up, when multiple processes are defined. This pager does not work as expected.

#### How can others reproduce the issue?

Define multiple processes and click on pager elements

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
![aug-16-2018 17-27-27 gif](https://user-images.githubusercontent.com/38498731/44218422-f480da00-a179-11e8-94d0-8a1afaffb0c8.gif)
