### ISSUE TITLE
Can't display contents of token in user task

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#811]
#### Describe your issue

There is currently no way to display the token within a form or confirm dialogue of an user task.

#### Possible solution

We could allow templating syntax in form labels (like `{{token.history}}` or `${token.history}`).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
I think thats not a part of bpmn-studio
