### ISSUE TITLE
🔍Inspect Deps; `electron-rebuild` obsolete?

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#813]
## Describe your issue

electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

This was reported by Jenkins:
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/develop/324/pipeline/78/

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
As far as I can tell this is really obselete. I will test this on windows and then I will delete this in an upcoming PR.

**Comment by Vyperus** [comment]
I was able to run the build on windows. Since there are many commands in the JenkinsFile that use this I would like @Paulomart to give his statement about this.

**Comment by cmg-dev** [comment]
Okay so far we think we are able to remove this dependency.

Thanks so far.

**Comment by Paulomart** [comment]
This dependency is used to rebuild native package: https://github.com/process-engine/bpmn-studio/blob/637a1214c184f1b0ed19b84a2748fdc0e2bb02de/package.json#L31

**Comment by Paulomart** [comment]
@cmg-dev Short answer: Yes. Long answer: Maybe.

**Comment by cmg-dev** [comment]
okay, thanks @Paulomart
