### ISSUE TITLE
Improve Info Message on Diagram Creation When Diagram Name Contains Invalid Characters

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#823]
#### Describe your issue

Currently the user only gets told that the name is invalid.
This should refactored, so that the user gets told which letters are invalid.

Have a look at:
https://github.com/process-engine/bpmn-studio/pull/816#discussion_r211501734

#### Possible solution

https://github.com/process-engine/bpmn-studio/pull/816#discussion_r211501734

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
The Problem is, that with the usage of the `FluentRuleCustomizer` from aurelia, it is not possible to retrain only the characters of the `match()` method. 

The _dirty_ fix is, to only set the current value as error message and modify it before actually displaying it in the view model. 

Maybe we can find a better solution for this.

**Comment by SteffenKn** [comment]
Imo, we should use the old functionality to check the diagram name, as this would be easy to implement there.
Also, the 'diagramValidationRegExpList' was removed, which was intentionally implemented to make the diagram validation easily extensible and at the same time it was easy to see which characters could be used.

**Comment by nox-do** [comment]
Idea: Maybe avoid trailing blank(s) with diagram names. Furthermore trailing blanks seems to be ignored or dropped anyway (untested. Blanks at the end. Maybe handled the same way that they get dropped. In addition to 80d8274

**Comment by SteffenKn** [comment]
You're right trailing blanks get dropped as well as blanks at the end. This should be added to the Validation. 👍
