### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#829]
#### Describe your issue

<img width="346" alt="screen shot 2018-08-22 at 15 01 17" src="https://user-images.githubusercontent.com/21304781/44464923-5464fe00-a61c-11e8-9e62-e26183b4ac24.png">

Error was something database related, but not related to the issue that the error message links to.

https://github.com/process-engine/bpmn-studio/issues/316

#### Possible solution

Don't link to issues that might have nothing to do with the error. 
#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
But the given Solution in the Issue is basically correct, since we don't have Database Migration on the Backend yet. But I understand, that the title and content of the Issue may be misleading.

**Comment by alexanderkasten** [comment]
Then the issue should get an update.

**Comment by Vyperus** [comment]
The issue got an update. https://github.com/process-engine/bpmn-studio/issues/316
