### ISSUE TITLE
Firefox and Safari could not get task list

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/bpmn-studio#830]
#### Describe your issue

When opening the dashboard view in Firefox or Safari, a toast message displays with:
 
```JSON
Error receiving task list: Error.captureStackTrace is not a function. (In 'Error.captureStackTrace(this, this.constructor)', 'Error.captureStackTrace' is undefined)
```

#### How can others reproduce the issue?

Create a new user task without finishing it.
Then navigate to dashboard view.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
Der Bug tritt auf, weil in `@essential-projects/errors_ts` die Methode `captureStackTrace` benutzt wird.
Die ist scheinbar nicht in jedem Browser verfügbar.
Um dem Bug zu fixen, sollte vorher überprüft werden, ob die Methode verfügbar ist und ggf. auf eine andere vergleichbare Methode gewechselt werden bzw. nichts getan werden.
