### ISSUE TITLE
BPMN-Studio Sometimes Crashs When Adding a Task to a Newly Created Diagramm

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#836]
#### Describe your issue

Sometimes I get this error when creating a new diagram and adding a new task:

<img width="480" alt="bildschirmfoto 2018-08-23 um 11 54 16" src="https://user-images.githubusercontent.com/20394992/44518757-5e920580-a6cb-11e8-9b55-fc1e2e4e408e.png">

#### How can others reproduce the issue?

- Create a new diagram
- Add a task
- Have a look at the console

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
I can not reproduce the bug with BPMN-Studio v4.2.0

**Comment by robpal94** [comment]
Me neither, but we should keep an eye of that.

**Comment by Vyperus** [comment]
Even Better: Find out what potentially caused the error and with what we fixed it. As long nobody can say what this was and why it was happening we can't close this issue.
