### ISSUE TITLE
Ansicht nur mit technischen IDs

### ISSUE THREAD

**Issue by nj0yeh** [process-engine/bpmn-studio#862]
#### Describe your issue

Um einen Prozessablauf im .NET-Code besser verfolgen zu können, wäre es manchmal wünschenswert, eine Ansicht zu haben, in der die Prosa-Texte ("Namen") ausgeblendet sind und stattdessen die technischen IDs angezeigt werden.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
Ich habe das mal zur Diskussion frei gegeben.

Vor Q1 19 ist damit aber nicht zu rechnen.

**Comment by rrrene** [comment]
Wir werden uns des zugrundeliegenden Problems annehmen, aber wahrscheinlich (!) eher, wie schonmal besprochen, mit einer "tabellarischen Ansicht" anstatt des Überschreibens der Namen im Diagramm.
