### ISSUE TITLE
Bei der Vergabe von technische IDs unterstützen

### ISSUE THREAD

**Issue by nj0yeh** [process-engine/bpmn-studio#863]
#### Describe your issue

Bei der Vergabe von technischen IDs, die für .NET-Code wichtig sind, wäre es hilfreich, wenn hinterlegte Namenstemplates eingeblendet werden, z. B.:

- Sequence Flows haben immer den Namen des Ursprungs mit angehängtem "Result" (diese könnten bei einer Umbenennung sogar automatisch mit umbenannt werden!!!)
- Messages von Start-Events enden auf "Input"
- Intermediate Throw Events enden auf "Event", ihre Messages enden auf "Input"
- End-Events enden auf "Processed", ihre Messages enden auf "ProcessedResult"
- Event-based Gateways beginnen mit "WaitFor"
- Join-Gateways enden auf "Finished"
- Split-Gateways beginnen mit "Is" oder "Has"

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@nj0yeh Könntest du bitte ein Beispiel Diagramm bereitstellen, wie Du dir das vorstellst?

Ich kann der Beschreibung nicht ganz folgen.

Beachte: BPMN-Datein nimmt github nicht, aber .zip Dateien :)

**Comment by nj0yeh** [comment]
[KK-DualMessage-Routing.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/2428328/KK-DualMessage-Routing.bpmn.zip)

**Comment by rrrene** [comment]
Wir werden die Namenstemplates in absehbarer Zeit nicht als Feature aufnehmen. Die in diesem Issue angesprochene filterbare Tabelle sollte aber das hier beschriebene Problem ebenfalls bessern: https://github.com/process-engine/bpmn-studio/issues/862
