### ISSUE TITLE
Message-Ansicht

### ISSUE THREAD

**Issue by nj0yeh** [process-engine/bpmn-studio#864]
#### Describe your issue

Es kommt vor, dass während der Entwicklung eines BPMNs Messages generiert werden, die später nicht mehr benötigt werden. Diese sind nur schwer herauszufinden und dann manuell aus dem XML zu löschen.

#### Possible solution

Übersicht aller Messages und Anzeige, ob (oder sogar wovon) sie verwendet werden. In dieser Ansicht kann man die Messages auch direkt rauslöschen.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by moellenbeck** [comment]
@nj0yeh danke für den Hinweis, auf der "noch" nicht öffentlichen Roadmap gibt es einen Punkt, der die logische Validierung von Diagrammen ermöglichen wird (aktuell in Q4/2018), da wäre dieses Feature eine sinnvolle Ergänzung.

**Comment by cmg-dev** [comment]
@nj0yeh 

Dir würde eine Ansicht reichen, die alle Nachrichten auflistet und in der Du dann eine Anzeige hast, wie oft die Nachricht noch referenziert wird?

Das wäre nicht zu schwer zu implementieren und in Q4 18 noch bestimmt drin.

**Comment by nj0yeh** [comment]
> Dir würde eine Ansicht reichen, die alle Nachrichten auflistet und in der Du dann eine Anzeige hast, wie oft die Nachricht noch referenziert wird?

Wenn ich die unbenutzten Nachrichten dort dann auch direkt löschen könnte, wäre das hilfreich.

**Comment by rrrene** [comment]
Dies wird entweder durch die Tabelle aus https://github.com/process-engine/bpmn-studio/issues/862 abgedeckt oder den Linter abgedeckt. :+1:
