### ISSUE TITLE
🐛 Edit History gets lost when opening another view

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#865]
#### Describe your issue

When switching to the diff - view, die edit history gets lost. Because of this, a user cannot revert his changes using `ctrl/cmd + z`. 

#### How can others reproduce the issue?

* Open or create a new diagram
* Save
* Make some changes
* Open the diff view
* Close the diff - view
* Try to revert your changes using `ctrl/cmd + s`.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
also when opening the xml view.
The full command stack gets lost, because the modeler gets destroyed on the detached method

**Comment by Vyperus** [comment]
We can solve the xml-view and diff-view part by show binding the components instead of if binding, not sure if this will work absolutely fine in the first try.

**Comment by robpal94** [comment]
Using `show.bind?` instead of `if.bind` in 
```
<bpmn-xml-view if.bind="initialLoadingFinished" show.bind="showXMLView" xml.bind="xml"></bpmn-xml-view>
```
does not really solve the Problem.

**Comment by robpal94** [comment]
The cause of this issue is that calling `saveXML()` on the modeller also resets the commandStack internally.

**Comment by robpal94** [comment]
The problem here is, that the `xml` variable is passed to various modules (property-panel, diff-view, xml-view) which **can** modify it. If this gets modifies, the commandStack breaks.
