### ISSUE TITLE
Only Update Lists when there was an update

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#872]
#### Describe your issue

Right now all lists in BPMN-Studio (Solution Explorer in PE View for example) get refreshed everytime the component polls for new diagrams even though most of the time no update should happen since there is no new content to render.

#### How can others reproduce the issue?

Start BPMN-Studio.
Check for the refreshing of lists.

#### Possible solution

Check if there was an update to the content of the list, if not don't update the corresponding array.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
Maybe it is time to implement a polling service.
Currently there are two components fetching the same processmodel list every 1,5 seconds.
Also the dashboard (task-list) fetches the processmodel list.
