### ISSUE TITLE
💄 Different Shades for Highlighting Icons on Hover

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#874]
#### Describe your issue

We use different shades of grey/black for coloring icons on hover.
After a quick search I found:
- black
- #a5a5a5
- #5c5c5c
- #5e5e5e
- #a5a5a5
We also use opacity for some icons.

<img width="28" src="https://user-images.githubusercontent.com/20394992/44663192-1f87eb00-aa10-11e8-8d51-d147aff640b4.png">
<img width="19" src="https://user-images.githubusercontent.com/20394992/44663194-1f87eb00-aa10-11e8-8c1f-d7164c0eecc4.png">
<img width="16" src="https://user-images.githubusercontent.com/20394992/44663195-1f87eb00-aa10-11e8-82ed-2f8c7a16e1d8.png">
<img width="22" src="https://user-images.githubusercontent.com/20394992/44663196-20208180-aa10-11e8-9cfa-b0084c7d5caa.png">
<img width="28" src="https://user-images.githubusercontent.com/20394992/44663197-20208180-aa10-11e8-9f4e-0455bc8552b9.png">
<img width="21" src="https://user-images.githubusercontent.com/20394992/44663198-20208180-aa10-11e8-8594-967e8ebf72d0.png">

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
For active/hover: color: #5e5e5e
For disabled: opacity: 0.1
Normal: color: darkgray
