### ISSUE TITLE
💬 The Icon Font Set

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#878]
#### Describe your issue

Lately we had many small discussions about the icons in BPMN-Studio. This issue shall help us collecting all related issues and organize a meeting where we can discuss this in more detail.

Additionally I would like to consult @lsueslack to provide more insight and eventually provide some icons for the BPMN-Studio.

#### Related Issues

#801 (Show Diff and Diagram Icons)
#770 (The Solution Explorer Icon)

**Comment by cmg-dev** [comment]
@Vyperus 

I would certainly like to use Font Awesome more.

But I would recommend to obtain a commercial License.

**Comment by cmg-dev** [comment]
@roblen45 @moellenbeck What do you think?

**Comment by Vyperus** [comment]
Fontawesome is now used for every icon. I would still like to have a commercial license. @cmg-dev

**Comment by cmg-dev** [comment]
@Vyperus I believe this is fair and would certainly provide us with more options regarding the icons.

I support this.

@roblen45 @moellenbeck What do you think?
