### ISSUE TITLE
Saved .bpmn files are unformatted (no newlines/indentation)

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#879]
#### Describe your issue

Saved .bpmn files are unformatted (no newlines/indentation).

Looks like that:
<img width="602" alt="screen shot 2018-08-28 at 10 38 59" src="https://user-images.githubusercontent.com/21304781/44711419-9ecbfc00-aaae-11e8-9977-8c98b1c7b144.png">

#### How can others reproduce the issue?

Create/open a file, save the file. No upload to processEngine needed.

#### Possible solution

Save formatted files instead.

#### What's your setup

osx, electron

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Duplicate, my bad #410

**Comment by LeoTT** [comment]
Talked with @MaFa961, @SteffenKn and @alexanderkasten about this.
This error does often not appear. But the bug is still there sometimes.
Would be super helpful if someone was able to reproduce it safely. 

Pretty sure #410 is related (had the export-error and the error in the xml view at the same time).

**Comment by Vyperus** [comment]
So we found the Issue and we will merge the PR today. Looking forward to the new release ;)
