### ISSUE TITLE
🚸 Create Overlay to Indicate to the User Where the Process Resides

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#891]
#### Describe your issue

Currently it is still hard for the user to understand when he or she is working on a local diagram or on a PE. 
Currently the only indication is the start- and deploy-button in the upper right corner on the detail-views.

#### Possible solution

Create an overlay that indicates where the user is right now. (PE or local)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
An icon could be added to the name of the diagram (in the upper menu bar) that shows the user if he is working on a local diagram or on a deployed diagram.

**Comment by cmg-dev** [comment]
@Vyperus @SteffenKn 

This is addressed in the SolutionExplorer Mk II and in the Feature that @robpal94 is working on.

We will get the Icon left of the diagram name in the top bar.
