### ISSUE TITLE
Linebreak in diff view summary

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#906]
#### Describe your issue

The diffview offers a summary of the changes.
Under certain circumstances there is a linebreak.

see bottom right of:
https://github.com/process-engine/documentation/blob/d1aa6e486a0c4cb0c215952d221a42480b5dbe50/bpmn-studio/components/diff-view/images/diff-view-change-list.png

#### How can others reproduce the issue?

Make all kinds of changes (remove,add,move,edit) to a diagram. 
Resize the window. 
Open diff view.
Click on burger menu symbol.

#### Possible solution

I don't find that line helpful for a quick overview anyway.
Instead maybe a sort of legend with linebreaks(as table):
- Total changes: 13
- Removed: 2

> You can remove this section if it's irrelevant to the issue
> (for example for certain questions or feature requests).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Fixed in #917
