### ISSUE TITLE
BPMN-io Component xml variable

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#912]
#### Describe your issue

In the `bpmn-io.ts` file, there is a variable called `xml` whis is defined like this:
```
  @bindable() public xml: string;
```
This will be injected by either the `processdef-detail` or `diagramm-detail` component. The bpmn-io component on the other hand also binds this value to the following components: 
* property-panel
* xml-view
* diff-view

Also this variable seems to be kinda bound to the `modeler` itself. 
The problem with this is, that at some point, this variables content gets modified where it should't. This leads to Issues like this: https://github.com/process-engine/bpmn-studio/issues/865
which is resolve by a dirty quickfix. 

#### Possible solution

We should
* look where this variable is used and binded
* see, if we can remove bindings from this variable to make the whole structure more robust and prevent side effects like the mentioned issue. 
* Dont inject this variables reference to subcomponents of the bpmn-io component

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Since we managed to build the architecture in a way that this variable isn't bound this way anymore, I will close  this for now.
