### ISSUE TITLE
No SASS Variables used

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#918]
#### Describe your issue

I wonder why we are not using constructs offered by sass css in our scss files. 

For example: Variables. 
A great example would be the `bpmn-diff-view.scss` file. Here, we have multiple blocks that defines a border in different directions such as: 
```
.left-diff-view__canvasModel {
  width: 100%;
  height: 100%;
  border-bottom: 4px dashed #ccc;
}

.right-diff-view__canvasModel {
  width: 100%;
  height: 100%;
  border-left: 4px dashed #ccc;
  border-bottom: 4px dashed #ccc;
}
```

Why cant we just use a variable for this like: 
```
$border_definition: 4px dashed #ccc;
```

and write the snippet above like so: 
```
.left-diff-view__canvasModel {
  width: 100%;
  height: 100%;
  border-bottom: $border_definition;
}

.right-diff-view__canvasModel {
  width: 100%;
  height: 100%;
  border-left: $border_definition;
  border-bottom: $border_definition;
}
```

On other places, we could offload colors into variables, which are defined more then once. 
IMO this would increase the maintainability of the css files. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@robpal94 Please refer to @rrrene Styleguide. If this guide says its okay, then I'm fine with this.

https://github.com/5minds/css-guidelines

**Comment by rrrene** [comment]
@robpal94 Spoiler-Alarm: Das ist exakt die Art von SCSS-Variable, die der Styleguide verhindern will.

**Comment by Vyperus** [comment]
Since this Issue isn't leading anywhere anymore I will close this for now.
