### ISSUE TITLE
✨Check Diagram Validator by bpmn-js

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#919]
#### Summary

bpmn.io released a diagram validator for their editor. We could integrate this in BPMN-Studio.

https://twitter.com/bpmn_io/status/1038062130992480256?s=12

https://github.com/bpmn-io/bpmn-js-bpmnlint

It is a package that allows us to "lint" diagrams while they are designed. The rules that apply should be free configurable and easy to access.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
We will use this, but it has no place on the roadmap, yet.
