### ISSUE TITLE
XML View is empty

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#930]
#### Describe your issue

XML view is just blank for me.
<img width="1439" alt="screen shot 2018-09-12 at 10 02 33" src="https://user-images.githubusercontent.com/21304781/45410849-0ec3b000-b673-11e8-9373-74086067b930.png">

No errors thrown.

#### How can others reproduce the issue?

Pretty sure this happens for every diagram.

#### What's your setup

Electron, develop build.

Stable release seems to be ok, must have been a recent change.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
Is this still happening when testing with this PR: https://github.com/process-engine/bpmn-studio/pull/929/files ?

**Comment by LeoTT** [comment]
Yes.

**Comment by LeoTT** [comment]
Can be closed, pretty sure this happened because I messed with the node_modules and did not properly reinstall. Had some other people test it and can now not reproduce this bug myself. My bad.
