### ISSUE TITLE
🐛Distribute Elements Buttons keeps disabled when selecting multiple elements using the group tool

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#940]
#### Describe your issue

When selecting multiple elements with the modeller's group select tool, the DistributeElements buttons are still disabled. 

#### How can others reproduce the issue?

* Select more then 2 Elements with the group select tool
* Try to distribute the elements

#### Possible solution

For whatever reason, the the group select tools does not report to the modeller when selecting elements. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
The color picker stays also diasbled.
