### ISSUE TITLE
🚸 If Two Different Diagrams with the Same Name Are Opened, the User Can No Longer Distinguish Which One Is Which One.

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#944]
#### Describe your issue

For example when opening diagram "Sending Mails" from folder A and diagram "Sending Mails" from folder B, the solution explorer only lists "Sending Mails" and "Sending Mail", but not the location.
The user then is unable to see which one is from folder A or B.

<img width="204" src="https://user-images.githubusercontent.com/20394992/45614572-43b47600-ba6a-11e8-97e5-dfb91d1d77d3.png">

#### How can others reproduce the issue?

- Open up the BPMN-Studio
- Open two diagrams with the same name from different locations
- **Notice that you can no longer say which is which.**

#### Possible solution

- Add a way to see the location of the diagrams

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
I think we should only support opening one diagram with a given name.

Notify the user, if a diagram is already open with that name.

---

Other Variant: 

We could include the Path to the diagram.

@roblen45 What do you think?

**Comment by SteffenKn** [comment]
We could do it like this:
<img width="284" src="https://user-images.githubusercontent.com/20394992/48131822-addedf80-e291-11e8-9715-3596d06e056c.png">

(`package.json` is in the root folder)
