### ISSUE TITLE
✨Implement Help Section

### ISSUE THREAD

**Issue by LeoTT** [process-engine/bpmn-studio#951]
#### Describe your issue

There is no help section.
It could include things like `Documentation`, `Report a bug` and `Send feedback`.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
Hey, thanks. We already planned something like this here:

https://github.com/process-engine/bpmn-studio/issues/942
