### ISSUE TITLE
Process title shown in Navbar when navigating to the dashboard

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#971]
#### Describe your issue

If you navigate from the heatmap view to the dashboard view, the ProcessTitle is still shown in the navbar. 

![out](https://user-images.githubusercontent.com/38498731/45871978-20056e80-bd8f-11e8-837a-c62cc7f82c26.gif)

#### How can others reproduce the issue?

* Open the Detail view
* Click on _Inspect_
* Open the _Heatmap_
* Open the _Dashboard_
* Look at the NavBar

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
Thats not a bug. This is a desired behavior.
