### ISSUE TITLE
⬆️ Update Bootstrap

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#975]
#### Describe your issue

Bootstrap is out of date. For that reason, it should be updated.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
I think this will be a bigger tasks since it seems like bootstrap changed a lot.

**Comment by SteffenKn** [comment]
We need to check what needs to be done to update bootstrap.

**Comment by cmg-dev** [comment]
https://github.com/process-engine/bpmn-studio/network/dependencies#package.json

But this is a Security Issue... This needs to be adressed.
