### ISSUE TITLE
Heatmap Bubbles overlapping BoundaryEvents

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#992]
#### Describe your issue

When a task contains a boundary event, the current Token Count bubble overlaps the boudary event. 

<img width="1412" alt="screen shot 2018-09-28 at 11 19 06" src="https://user-images.githubusercontent.com/38498731/46199882-7be07200-c310-11e8-91ed-76c27c677d55.png">

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Releated #981

**Comment by cmg-dev** [comment]
Please move the Bubble to the upper right corner of the shape... then we are fine with this.

Please do so, just for the Task Shapes.
