### ISSUE TITLE
🐛BPMN-Studio doesn't work with 6.1.0 version of Node

### ISSUE THREAD

**Issue by Vyperus** [process-engine/bpmn-studio#994]
#### Describe your issue

As stated in the README BPMN-Studio should be able to run on Node Version 6.1.0 but fails on `npm install`.

#### How can others reproduce the issue?

Try `npm run reset` and `npm install` with Node 6.1.0-

#### Possible solution

Update the README.

#### What's your setup

- BPMN-Studio Version `develop`

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
Since node 6 is still an active supported lts version, shouln't we rather care about, why bpmn studio doesn't work with node 6?

**Comment by Vyperus** [comment]
Change Readme to support active LTS of node.
